export const OWNERS = ['Dedon', 'Caz', 'Perry P', 'Sam', 'Nick', 'Zack', 'Dylan', 'Jared']

export const ROUNDS = ['1st Rounder', '2nd Rounder', '3rd Rounder', '4th Rounder']

// Maps owner short names used in the future picks data to INITIAL_TEAMS ids
// Dedon=8, Caz=6, Perry P/Perri=7, Sam=2, Nick=3, Zack/Zach=5, Dylan=4, Jared=1
export const OWNER_TO_TEAM_ID = {
  'Dedon': 8,
  'Caz': 6,
  'Perry P': 7,
  'Perri': 7,
  'Sam': 2,
  'Nick': 3,
  'Zack': 5,
  'Zach': 5,
  'Dylan': 4,
  'Jared': 1,
}

export const TEAM_ID_TO_OWNER = {
  8: 'Dedon',
  6: 'Caz',
  7: 'Perry P',
  2: 'Sam',
  3: 'Nick',
  5: 'Zack',
  4: 'Dylan',
  1: 'Jared',
}

export const OWNER_COLORS = {
  'Dedon': 'bg-cyan-100 text-cyan-800 border-cyan-200',
  'Caz': 'bg-pink-100 text-pink-800 border-pink-200',
  'Perry P': 'bg-orange-100 text-orange-800 border-orange-200',
  'Perri': 'bg-orange-100 text-orange-800 border-orange-200',
  'Sam': 'bg-blue-100 text-blue-800 border-blue-200',
  'Nick': 'bg-green-100 text-green-800 border-green-200',
  'Zack': 'bg-purple-100 text-purple-800 border-purple-200',
  'Zach': 'bg-purple-100 text-purple-800 border-purple-200',
  'Dylan': 'bg-yellow-100 text-yellow-800 border-yellow-200',
  'Jared': 'bg-red-100 text-red-800 border-red-200',
}

export function getOwnerColor(owner) {
  return OWNER_COLORS[owner] || 'bg-gray-100 text-gray-800 border-gray-200'
}

// Each entry: { owner: string, notes: number[] }
// notes are footnote reference numbers e.g. [3] [10]
export const INITIAL_PICK_DATA = {
  2022: {
    '1st Rounder': [
      { owner: 'Dedon', notes: [] },
      { owner: 'Caz', notes: [] },
      { owner: 'Perry P', notes: [] },
      { owner: 'Sam', notes: [] },
      { owner: 'Nick', notes: [] },
      { owner: 'Zack', notes: [] },
      { owner: 'Dylan', notes: [] },
      { owner: 'Jared', notes: [] },
    ],
    '2nd Rounder': [
      { owner: 'Dedon', notes: [] },
      { owner: 'Caz', notes: [] },
      { owner: 'Perry P', notes: [] },
      { owner: 'Sam', notes: [] },
      { owner: 'Nick', notes: [] },
      { owner: 'Zack', notes: [] },
      { owner: 'Dylan', notes: [] },
      { owner: 'Jared', notes: [] },
    ],
    '3rd Rounder': [
      { owner: 'Dedon', notes: [] },
      { owner: 'Caz', notes: [] },
      { owner: 'Perry P', notes: [] },
      { owner: 'Caz', notes: [1] },
      { owner: 'Nick', notes: [] },
      { owner: 'Zack', notes: [] },
      { owner: 'Dylan', notes: [] },
      { owner: 'Jared', notes: [] },
    ],
    '4th Rounder': [
      { owner: 'Dedon', notes: [] },
      { owner: 'Caz', notes: [] },
      { owner: 'Perry P', notes: [] },
      { owner: 'Sam', notes: [] },
      { owner: 'Nick', notes: [] },
      { owner: 'Zack', notes: [] },
      { owner: 'Dylan', notes: [] },
      { owner: 'Jared', notes: [] },
    ],
  },
  2023: {
    '1st Rounder': [
      { owner: 'Dedon', notes: [] },
      { owner: 'Caz', notes: [] },
      { owner: 'Perry P', notes: [] },
      { owner: 'Caz', notes: [3] },
      { owner: 'Nick', notes: [] },
      { owner: 'Zack', notes: [] },
      { owner: 'Dylan', notes: [] },
      { owner: 'Zach', notes: [6] },
    ],
    '2nd Rounder': [
      { owner: 'Dedon', notes: [] },
      { owner: 'Caz', notes: [] },
      { owner: 'Perry P', notes: [] },
      { owner: 'Caz', notes: [3] },
      { owner: 'Nick', notes: [4] },
      { owner: 'Zack', notes: [] },
      { owner: 'Dylan', notes: [] },
      { owner: 'Jared', notes: [] },
    ],
    '3rd Rounder': [
      { owner: 'Dedon', notes: [] },
      { owner: 'Caz', notes: [] },
      { owner: 'Perry P', notes: [] },
      { owner: 'Sam', notes: [] },
      { owner: 'Nick', notes: [] },
      { owner: 'Zack', notes: [] },
      { owner: 'Dylan', notes: [] },
      { owner: 'Jared', notes: [] },
    ],
    '4th Rounder': [
      { owner: 'Dedon', notes: [] },
      { owner: 'Caz', notes: [] },
      { owner: 'Perry P', notes: [] },
      { owner: 'Sam', notes: [] },
      { owner: 'Zach', notes: [5] },
      { owner: 'Zack', notes: [] },
      { owner: 'Dylan', notes: [] },
      { owner: 'Jared', notes: [] },
    ],
  },
  2024: {
    '1st Rounder': [
      { owner: 'Sam', notes: [11] },
      { owner: 'Caz', notes: [] },
      { owner: 'Perry P', notes: [] },
      { owner: 'Caz', notes: [3] },
      { owner: 'Nick', notes: [] },
      { owner: 'Zack', notes: [] },
      { owner: 'Dylan', notes: [] },
      { owner: 'Jared', notes: [] },
    ],
    '2nd Rounder': [
      { owner: 'Jared', notes: [14] },
      { owner: 'Caz', notes: [] },
      { owner: 'Perry P', notes: [] },
      { owner: 'Sam', notes: [] },
      { owner: 'Zack', notes: [9] },
      { owner: 'Zack', notes: [] },
      { owner: 'Dylan', notes: [] },
      { owner: 'Jared', notes: [] },
    ],
    '3rd Rounder': [
      { owner: 'Dedon', notes: [] },
      { owner: 'Nick', notes: [4] },
      { owner: 'Perry P', notes: [] },
      { owner: 'Sam', notes: [] },
      { owner: 'Zack', notes: [8] },
      { owner: 'Zack', notes: [] },
      { owner: 'Dylan', notes: [] },
      { owner: 'Jared', notes: [] },
    ],
    '4th Rounder': [
      { owner: 'Dedon', notes: [] },
      { owner: 'Caz', notes: [] },
      { owner: 'Perry P', notes: [] },
      { owner: 'Caz', notes: [3] },
      { owner: 'Nick', notes: [] },
      { owner: 'Zack', notes: [] },
      { owner: 'Dylan', notes: [] },
      { owner: 'Jared', notes: [] },
    ],
  },
  2025: {
    '1st Rounder': [
      { owner: 'Jared', notes: [14] },
      { owner: 'Caz', notes: [] },
      { owner: 'Perry P', notes: [] },
      { owner: 'Zack', notes: [10] },
      { owner: 'Nick', notes: [] },
      { owner: 'Zack', notes: [] },
      { owner: 'Dylan', notes: [] },
      { owner: 'Zack', notes: [14, 21] },
    ],
    '2nd Rounder': [
      { owner: 'Dedon', notes: [] },
      { owner: 'Perri', notes: [16] },
      { owner: 'Zack', notes: [18] },
      { owner: 'Perri', notes: [17] },
      { owner: 'Jared', notes: [24] },
      { owner: 'Zack', notes: [] },
      { owner: 'Dylan', notes: [] },
      { owner: 'Jared', notes: [] },
    ],
    '3rd Rounder': [
      { owner: 'Dedon', notes: [] },
      { owner: 'Nick', notes: [12] },
      { owner: 'Perry P', notes: [] },
      { owner: 'Nick', notes: [19] },
      { owner: 'Zack', notes: [8] },
      { owner: 'Zack', notes: [] },
      { owner: 'Dylan', notes: [] },
      { owner: 'Sam', notes: [6, 10] },
    ],
    '4th Rounder': [
      { owner: 'Dedon', notes: [] },
      { owner: 'Caz', notes: [] },
      { owner: 'Perry P', notes: [] },
      { owner: 'Sam', notes: [] },
      { owner: 'Nick', notes: [] },
      { owner: 'Perri', notes: [18] },
      { owner: 'Dylan', notes: [] },
      { owner: 'Jared', notes: [] },
    ],
  },
  2026: {
    '1st Rounder': [
      { owner: 'Zack', notes: [20] },
      { owner: 'Caz', notes: [] },
      { owner: 'Perry P', notes: [] },
      { owner: 'Sam', notes: [] },
      { owner: 'Nick', notes: [] },
      { owner: 'Zack', notes: [] },
      { owner: 'Dylan', notes: [] },
      { owner: 'Jared', notes: [] },
    ],
    '2nd Rounder': [
      { owner: 'Jared', notes: [25] },
      { owner: 'Caz', notes: [] },
      { owner: 'Perry P', notes: [] },
      { owner: 'Zack', notes: [10] },
      { owner: 'Nick', notes: [] },
      { owner: 'Zack', notes: [] },
      { owner: 'Dylan', notes: [] },
      { owner: 'Perri', notes: [26] },
    ],
    '3rd Rounder': [
      { owner: 'Dedon', notes: [] },
      { owner: 'Caz', notes: [] },
      { owner: 'Zack', notes: [22] },
      { owner: 'Sam', notes: [] },
      { owner: 'Nick', notes: [] },
      { owner: 'Zack', notes: [] },
      { owner: 'Dylan', notes: [] },
      { owner: 'Jared', notes: [] },
    ],
    '4th Rounder': [
      { owner: 'Dedon', notes: [] },
      { owner: 'Caz', notes: [] },
      { owner: 'Perry P', notes: [] },
      { owner: 'Sam', notes: [] },
      { owner: 'Nick', notes: [] },
      { owner: 'Perri', notes: [22] },
      { owner: 'Dylan', notes: [] },
      { owner: 'Jared', notes: [] },
    ],
  },
  2027: {
    '1st Rounder': [
      { owner: 'Zack', notes: [21] },
      { owner: 'Caz', notes: [] },
      { owner: 'Perry P', notes: [] },
      { owner: 'Sam', notes: [] },
      { owner: 'Nick', notes: [] },
      { owner: 'Zack', notes: [] },
      { owner: 'Dylan', notes: [] },
      { owner: 'Jared', notes: [] },
    ],
    '2nd Rounder': [
      { owner: 'Jared', notes: [25] },
      { owner: 'Caz', notes: [] },
      { owner: 'Perry P', notes: [] },
      { owner: 'Sam', notes: [] },
      { owner: 'Nick', notes: [] },
      { owner: 'Zack', notes: [] },
      { owner: 'Dylan', notes: [] },
      { owner: 'Jared', notes: [] },
    ],
    '3rd Rounder': [
      { owner: 'Dedon', notes: [] },
      { owner: 'Caz', notes: [] },
      { owner: 'Perry P', notes: [] },
      { owner: 'Sam', notes: [] },
      { owner: 'Nick', notes: [] },
      { owner: 'Zack', notes: [] },
      { owner: 'Dylan', notes: [] },
      { owner: 'Jared', notes: [] },
    ],
    '4th Rounder': [
      { owner: 'Dedon', notes: [] },
      { owner: 'Caz', notes: [] },
      { owner: 'Perry P', notes: [] },
      { owner: 'Sam', notes: [] },
      { owner: 'Nick', notes: [] },
      { owner: 'Zack', notes: [] },
      { owner: 'Dylan', notes: [] },
      { owner: 'Jared', notes: [] },
    ],
  },
  2028: {
    '1st Rounder': [
      { owner: 'Dedon', notes: ['21*'] },
      { owner: 'Caz', notes: [] },
      { owner: 'Perry P', notes: [] },
      { owner: 'Sam', notes: [] },
      { owner: 'Nick', notes: [] },
      { owner: 'Zack', notes: [] },
      { owner: 'Dylan', notes: [] },
      { owner: 'Jared', notes: [] },
    ],
    '2nd Rounder': [
      { owner: 'Zack', notes: ['21*'] },
      { owner: 'Caz', notes: [] },
      { owner: 'Perry P', notes: [] },
      { owner: 'Sam', notes: [] },
      { owner: 'Nick', notes: [] },
      { owner: 'Zack', notes: [] },
      { owner: 'Dylan', notes: [] },
      { owner: 'Jared', notes: [] },
    ],
    '3rd Rounder': [
      { owner: 'Dedon', notes: [] },
      { owner: 'Caz', notes: [] },
      { owner: 'Perry P', notes: [] },
      { owner: 'Sam', notes: [] },
      { owner: 'Nick', notes: [] },
      { owner: 'Zack', notes: [] },
      { owner: 'Dylan', notes: [] },
      { owner: 'Jared', notes: [] },
    ],
    '4th Rounder': [
      { owner: 'Dedon', notes: [] },
      { owner: 'Caz', notes: [] },
      { owner: 'Perry P', notes: [] },
      { owner: 'Sam', notes: [] },
      { owner: 'Nick', notes: [] },
      { owner: 'Zack', notes: [] },
      { owner: 'Dylan', notes: [] },
      { owner: 'Jared', notes: [] },
    ],
  },
}

export const INITIAL_FOOTNOTES = [
  { id: 1, text: 'Antonio Brown and Tua for Daniel Jones and 3rd round pick - 10.13.21' },
  { id: 2, text: 'Jaylen Waren for a 2023 2nd round pick - 9.14.22' },
  { id: 3, text: 'Christian McCaffery, Daniel Jones, Kenyan Drake for Amon St. Brown, 2023 first round pick, 2023 second round pick, 2024 first round pick, 2024 4th round pick - 10.21.22' },
  { id: 4, text: 'Michael Thomas for 2023 second round pick (13) and 2024 third round pick - 8.9.23' },
  { id: 5, text: 'Perry trades Ryan Tannehill to Nick for a 2023 fourth round pick - 8.17.23' },
  { id: 6, text: "Jared trades Ken Walkers, 2023 first round pick, 2025 third round pick to Zach for Jaylen Waddle - 8.17.23" },
  { id: 7, text: 'Zack trades 1.08 in 2023 to Perri P for Kyler Murray and 4.05 - 8.17.23' },
  { id: 8, text: 'Zack trades Devin Singletary to Nick for 2024 and 2025 third round picks - preseason 2023' },
  { id: 9, text: 'Zack trades Joe Mixon to Nick for 2024 second round pick - 10.26.23' },
  { id: 10, text: "Zack trades Stefan Diggs and Jared's 2025 3rd round pick to Sam for George Pickens, 2025 1st, and 2026 2nd (and $20 if he quits league) - 10.28.23" },
  { id: 11, text: 'Sam trades Devon Achane and Pat Freiermuth to Dedon for Chubb and 2024 1st - 10.28.23' },
  { id: 12, text: 'Nick trades 2024 1.05 to Caz for 1.07, James Conner, and 2025 3rd round pick' },
  { id: 13, text: 'Nick trades 2025 2nd to Zack for Baker Mayfield' },
  { id: 14, text: 'Dedon trades 2024 2nd & 2025 1st to Jared for 2025 1st & David Montgomery' },
  { id: 15, text: 'Caz trades Josh Jacobs to Dylan for 2024 2.03' },
  { id: 16, text: 'Caz trades 2.08, 2025 2nd and Russell Wilson to Perri for 2.06' },
  { id: 17, text: 'Sam trades Zach Moss and 2025 2nd for 2.08' },
  { id: 18, text: 'Zack trades Kareem Hunt plus 2025 4th to Perri for 2025 2nd' },
  { id: 19, text: 'Nick trades James Connor to Sam for 2025 3rd and Khalil Shakir' },
  { id: 20, text: 'Zack trades Calvin Ridley to Dedon for 2026 1st (flexed from 2025 when Dedon made 25 championship)' },
  { id: 21, text: "Zack trades Trey McBride, Isaac Guerrendo, and Braelon Allen to Dedon for Brandon Aiyuk, Jared's 2025 1st, Dedon's 2027 1st, and 2028 2nd (flexes to 2028 1st if Dedon makes '27 championship)" },
  { id: 22, text: 'Zack trades Matt Stafford and 2026 4th to Perri for 2026 3rd' },
  { id: 23, text: 'Nick trades Olave for his own 2025 2nd (2.07) pick back' },
  { id: 24, text: 'Jared trades Brian Robinson to Nick for pick 2.07' },
  { id: 25, text: 'Jared trades Cooper Kupp and Keenan Allen to Dedon for 2026 2nd and 2027 2nd round picks' },
  { id: 26, text: 'Draft day trade Jared 2026 2nd rounder for 2 2025 3rd rounders from Perri' },
]
