export const LEAGUE_HISTORY = [
  {
    year: 2025,
    champion: 'The Evil Empire',
    runnerUp: 'Whatever who cares',
    third: 'Suave Shaheed',
    standings: [
      ['The Evil Empire', '8-7-0'],
      ['Whatever who cares', '8-7-0'],
      ['Suave Shaheed', '10-5-0'],
      ['Teddy Bongwater', '9-6-0'],
      ['Team Faircloth', '7-8-0'],
      ['Team caz', '6-9-0'],
      ["Hoidus' Hemmroid", '5-10-0'],
      ['Cheznovs Abduction', '7-8-0'],
    ],
  },
  {
    year: 2024,
    champion: "Perri's Brave Buffoons",
    runnerUp: 'Suavè Olave',
    third: "Hoidus' Hemmroid",
    standings: [
      ["Perri's Brave Buffoons", '11-4-0'],
      ['Suavè Olave', '8-7-0'],
      ["Hoidus' Hemmroid", '9-6-0'],
      ['Retribution.', '7-8-0'],
      ['Teddy Bongwater', '7-8-0'],
      ['Team Faircloth', '5-10-0'],
      ['DK Metcalf God Emperor', '6-9-0'],
      ['Team caz', '7-8-0'],
    ],
  },
  {
    year: 2023,
    champion: 'Team caz',
    runnerUp: 'Dallas, Texas Austin, Dedon',
    third: 'Suavè Olave',
    standings: [
      ['Team caz', '8-6-0'],
      ['Dallas, Texas Austin, Dedon', '10-4-0'],
      ['Suavè Olave', '8-6-0'],
      ['Team OffDemBeers', '9-5-0'],
      ['Team Faircloth', '4-10-0'],
      ['DK Metcalf God Emperor', '8-6-0'],
      ['Teddy Bongwater', '5-9-0'],
      ["Perri's Deli", '4-10-0'],
    ],
  },
  {
    year: 2022,
    champion: 'DK Metcalf God Emperor',
    runnerUp: 'Team OffDemBeers',
    third: 'Dallas, Texas Austin Dedon',
    standings: [
      ['DK Metcalf God Emperor', '10-4-0'],
      ['Team OffDemBeers', '9-5-0'],
      ['Dallas, Texas Austin Dedon', '9-5-0'],
      ['Suavè Olave', '8-6-0'],
      ['Teddy Bongwater', '7-7-0'],
      ['🍻 Hoppy Gentlemen', '4-10-0'],
      ['Team MEAT LORD', '7-7-0'],
      ['Team caz', '2-12-0'],
    ],
  },
  {
    year: 2021,
    champion: 'DK Metcalf God Emperor',
    runnerUp: 'Teddy Bongwater',
    third: 'Team OffDemBeers',
    standings: [
      ['DK Metcalf God Emperor', '9-5-0'],
      ['Teddy Bongwater', '8-6-0'],
      ['Team OffDemBeers', '9-5-0'],
      ['Dallas, Texas Austin Dedon', '8-6-0'],
      ['🍻 Hoppy Gentlemen', '6-8-0'],
      ['Team Dedon', '5-9-0'],
      ['Sweep It Under The Ruggs', '6-8-0'],
      ['Team caz', '5-9-0'],
    ],
  },
]

export const LINEAGE_MAP = {
  'The Evil Empire': { franchiseId: 1 },
  'Whatever who cares': { franchiseId: 2 },
  'Suave Shaheed': { franchiseId: 3 },
  'Teddy Bongwater': { franchiseId: 4 },
  'Team Faircloth': { franchiseId: 5 },
  'Team caz': { franchiseId: 6 },
  "Hoidus' Hemmroid": { franchiseId: 7 },
  'Cheznovs Abduction': { franchiseId: 8 },
  'Dallas, Texas Austin, Dedon': { franchiseId: 8 },
  'Dallas, Texas Austin Dedon': { franchiseId: 8 },
  'Team Dedon': { franchiseId: 8 },
}
