// KeepTradeCut dynasty superflex rankings (top 300), captured 2026-07-07
// Source: https://keeptradecut.com/dynasty-rankings
export const PLAYER_VALUES = [
  {
    "name": "Bijan Robinson",
    "position": "RB",
    "team": "ATL",
    "age": 24.4,
    "value": 9999,
    "rank": 1,
    "positionalRank": 1,
    "tier": 1,
    "trend": 1,
    "rookie": false
  },
  {
    "name": "Ja'Marr Chase",
    "position": "WR",
    "team": "CIN",
    "age": 26.4,
    "value": 9995,
    "rank": 2,
    "positionalRank": 1,
    "tier": 1,
    "trend": 1,
    "rookie": false
  },
  {
    "name": "Josh Allen",
    "position": "QB",
    "team": "BUF",
    "age": 30.1,
    "value": 9994,
    "rank": 3,
    "positionalRank": 1,
    "tier": 1,
    "trend": -2,
    "rookie": false
  },
  {
    "name": "Jahmyr Gibbs",
    "position": "RB",
    "team": "DET",
    "age": 24.3,
    "value": 9954,
    "rank": 4,
    "positionalRank": 2,
    "tier": 1,
    "trend": 0,
    "rookie": false
  },
  {
    "name": "Jaxon Smith-Njigba",
    "position": "WR",
    "team": "SEA",
    "age": 24.4,
    "value": 9551,
    "rank": 5,
    "positionalRank": 2,
    "tier": 2,
    "trend": 0,
    "rookie": false
  },
  {
    "name": "Drake Maye",
    "position": "QB",
    "team": "NEP",
    "age": 23.8,
    "value": 9413,
    "rank": 6,
    "positionalRank": 2,
    "tier": 2,
    "trend": 0,
    "rookie": false
  },
  {
    "name": "Puka Nacua",
    "position": "WR",
    "team": "LAR",
    "age": 25.1,
    "value": 8690,
    "rank": 7,
    "positionalRank": 3,
    "tier": 3,
    "trend": 0,
    "rookie": false
  },
  {
    "name": "Brock Bowers",
    "position": "TE",
    "team": "LVR",
    "age": 23.6,
    "value": 8150,
    "rank": 8,
    "positionalRank": 1,
    "tier": 4,
    "trend": 0,
    "rookie": false
  },
  {
    "name": "Caleb Williams",
    "position": "QB",
    "team": "CHI",
    "age": 24.6,
    "value": 8033,
    "rank": 9,
    "positionalRank": 3,
    "tier": 4,
    "trend": 0,
    "rookie": false
  },
  {
    "name": "Amon-Ra St. Brown",
    "position": "WR",
    "team": "DET",
    "age": 26.7,
    "value": 7902,
    "rank": 10,
    "positionalRank": 4,
    "tier": 4,
    "trend": 0,
    "rookie": false
  },
  {
    "name": "Jayden Daniels",
    "position": "QB",
    "team": "WAS",
    "age": 25.6,
    "value": 7813,
    "rank": 11,
    "positionalRank": 4,
    "tier": 4,
    "trend": 0,
    "rookie": false
  },
  {
    "name": "Ashton Jeanty",
    "position": "RB",
    "team": "LVR",
    "age": 22.6,
    "value": 7679,
    "rank": 12,
    "positionalRank": 3,
    "tier": 4,
    "trend": 3,
    "rookie": false
  },
  {
    "name": "Jeremiyah Love",
    "position": "RB",
    "team": "ARI",
    "age": 21.1,
    "value": 7609,
    "rank": 13,
    "positionalRank": 4,
    "tier": 4,
    "trend": 1,
    "rookie": true
  },
  {
    "name": "Justin Jefferson",
    "position": "WR",
    "team": "MIN",
    "age": 27.0,
    "value": 7585,
    "rank": 14,
    "positionalRank": 5,
    "tier": 4,
    "trend": -2,
    "rookie": false
  },
  {
    "name": "Lamar Jackson",
    "position": "QB",
    "team": "BAL",
    "age": 29.5,
    "value": 7553,
    "rank": 15,
    "positionalRank": 5,
    "tier": 4,
    "trend": -2,
    "rookie": false
  },
  {
    "name": "Malik Nabers",
    "position": "WR",
    "team": "NYG",
    "age": 22.9,
    "value": 7471,
    "rank": 16,
    "positionalRank": 6,
    "tier": 4,
    "trend": 0,
    "rookie": false
  },
  {
    "name": "Joe Burrow",
    "position": "QB",
    "team": "CIN",
    "age": 29.6,
    "value": 7467,
    "rank": 17,
    "positionalRank": 6,
    "tier": 4,
    "trend": 1,
    "rookie": false
  },
  {
    "name": "Trey McBride",
    "position": "TE",
    "team": "ARI",
    "age": 26.6,
    "value": 7343,
    "rank": 18,
    "positionalRank": 2,
    "tier": 5,
    "trend": -1,
    "rookie": false
  },
  {
    "name": "CeeDee Lamb",
    "position": "WR",
    "team": "DAL",
    "age": 27.2,
    "value": 7218,
    "rank": 19,
    "positionalRank": 7,
    "tier": 6,
    "trend": 0,
    "rookie": false
  },
  {
    "name": "Drake London",
    "position": "WR",
    "team": "ATL",
    "age": 25.0,
    "value": 7158,
    "rank": 20,
    "positionalRank": 8,
    "tier": 6,
    "trend": 1,
    "rookie": false
  },
  {
    "name": "2027 Early 1st",
    "position": "RDP",
    "team": "FA",
    "age": 0.0,
    "value": 7062,
    "rank": 21,
    "positionalRank": null,
    "tier": 6,
    "trend": -1,
    "rookie": false
  },
  {
    "name": "Justin Herbert",
    "position": "QB",
    "team": "LAC",
    "age": 28.3,
    "value": 6974,
    "rank": 22,
    "positionalRank": 7,
    "tier": 6,
    "trend": 0,
    "rookie": false
  },
  {
    "name": "Omarion Hampton",
    "position": "RB",
    "team": "LAC",
    "age": 23.3,
    "value": 6903,
    "rank": 23,
    "positionalRank": 5,
    "tier": 6,
    "trend": 1,
    "rookie": false
  },
  {
    "name": "De'Von Achane",
    "position": "RB",
    "team": "MIA",
    "age": 24.7,
    "value": 6873,
    "rank": 24,
    "positionalRank": 6,
    "tier": 6,
    "trend": -1,
    "rookie": false
  },
  {
    "name": "Patrick Mahomes",
    "position": "QB",
    "team": "KCC",
    "age": 30.8,
    "value": 6635,
    "rank": 25,
    "positionalRank": 8,
    "tier": 7,
    "trend": 0,
    "rookie": false
  },
  {
    "name": "Tetairoa McMillan",
    "position": "WR",
    "team": "CAR",
    "age": 23.2,
    "value": 6554,
    "rank": 26,
    "positionalRank": 9,
    "tier": 7,
    "trend": 1,
    "rookie": false
  },
  {
    "name": "Jaxson Dart",
    "position": "QB",
    "team": "NYG",
    "age": 23.2,
    "value": 6473,
    "rank": 27,
    "positionalRank": 9,
    "tier": 7,
    "trend": -1,
    "rookie": false
  },
  {
    "name": "Trevor Lawrence",
    "position": "QB",
    "team": "JAC",
    "age": 26.8,
    "value": 6338,
    "rank": 28,
    "positionalRank": 10,
    "tier": 8,
    "trend": 0,
    "rookie": false
  },
  {
    "name": "Colston Loveland",
    "position": "TE",
    "team": "CHI",
    "age": 22.2,
    "value": 6228,
    "rank": 29,
    "positionalRank": 3,
    "tier": 8,
    "trend": 0,
    "rookie": false
  },
  {
    "name": "Jalen Hurts",
    "position": "QB",
    "team": "PHI",
    "age": 27.9,
    "value": 6128,
    "rank": 30,
    "positionalRank": 11,
    "tier": 9,
    "trend": 0,
    "rookie": false
  },
  {
    "name": "Emeka Egbuka",
    "position": "WR",
    "team": "TBB",
    "age": 23.7,
    "value": 6100,
    "rank": 31,
    "positionalRank": 10,
    "tier": 9,
    "trend": 0,
    "rookie": false
  },
  {
    "name": "James Cook",
    "position": "RB",
    "team": "BUF",
    "age": 26.8,
    "value": 6064,
    "rank": 32,
    "positionalRank": 7,
    "tier": 9,
    "trend": 2,
    "rookie": false
  },
  {
    "name": "Bo Nix",
    "position": "QB",
    "team": "DEN",
    "age": 26.4,
    "value": 6008,
    "rank": 33,
    "positionalRank": 12,
    "tier": 9,
    "trend": -1,
    "rookie": false
  },
  {
    "name": "Jonathan Taylor",
    "position": "RB",
    "team": "IND",
    "age": 27.5,
    "value": 5991,
    "rank": 34,
    "positionalRank": 8,
    "tier": 9,
    "trend": -1,
    "rookie": false
  },
  {
    "name": "Carnell Tate",
    "position": "WR",
    "team": "TEN",
    "age": 21.5,
    "value": 5962,
    "rank": 35,
    "positionalRank": 11,
    "tier": 9,
    "trend": 0,
    "rookie": true
  },
  {
    "name": "George Pickens",
    "position": "WR",
    "team": "DAL",
    "age": 25.3,
    "value": 5947,
    "rank": 36,
    "positionalRank": 12,
    "tier": 9,
    "trend": 2,
    "rookie": false
  },
  {
    "name": "Tyler Warren",
    "position": "TE",
    "team": "IND",
    "age": 24.1,
    "value": 5864,
    "rank": 37,
    "positionalRank": 4,
    "tier": 9,
    "trend": 0,
    "rookie": false
  },
  {
    "name": "Brock Purdy",
    "position": "QB",
    "team": "SFO",
    "age": 26.5,
    "value": 5858,
    "rank": 38,
    "positionalRank": 13,
    "tier": 9,
    "trend": -2,
    "rookie": false
  },
  {
    "name": "Garrett Wilson",
    "position": "WR",
    "team": "NYJ",
    "age": 26.0,
    "value": 5681,
    "rank": 39,
    "positionalRank": 13,
    "tier": 10,
    "trend": 0,
    "rookie": false
  },
  {
    "name": "2027 Mid 1st",
    "position": "RDP",
    "team": "FA",
    "age": 0.0,
    "value": 5640,
    "rank": 40,
    "positionalRank": null,
    "tier": 10,
    "trend": 1,
    "rookie": false
  },
  {
    "name": "2026 Early 1st",
    "position": "RDP",
    "team": "FA",
    "age": 0.0,
    "value": 5631,
    "rank": 41,
    "positionalRank": null,
    "tier": 10,
    "trend": -1,
    "rookie": false
  },
  {
    "name": "Nico Collins",
    "position": "WR",
    "team": "HOU",
    "age": 27.3,
    "value": 5612,
    "rank": 42,
    "positionalRank": 14,
    "tier": 10,
    "trend": 1,
    "rookie": false
  },
  {
    "name": "Ladd McConkey",
    "position": "WR",
    "team": "LAC",
    "age": 24.7,
    "value": 5551,
    "rank": 43,
    "positionalRank": 15,
    "tier": 10,
    "trend": 4,
    "rookie": false
  },
  {
    "name": "Quinshon Judkins",
    "position": "RB",
    "team": "CLE",
    "age": 22.7,
    "value": 5541,
    "rank": 44,
    "positionalRank": 9,
    "tier": 10,
    "trend": 2,
    "rookie": false
  },
  {
    "name": "Fernando Mendoza",
    "position": "QB",
    "team": "LVR",
    "age": 22.8,
    "value": 5523,
    "rank": 45,
    "positionalRank": 14,
    "tier": 10,
    "trend": -3,
    "rookie": true
  },
  {
    "name": "Jordan Love",
    "position": "QB",
    "team": "GBP",
    "age": 27.7,
    "value": 5506,
    "rank": 46,
    "positionalRank": 15,
    "tier": 10,
    "trend": -3,
    "rookie": false
  },
  {
    "name": "TreVeyon Henderson",
    "position": "RB",
    "team": "NEP",
    "age": 23.7,
    "value": 5487,
    "rank": 47,
    "positionalRank": 10,
    "tier": 10,
    "trend": 5,
    "rookie": false
  },
  {
    "name": "Kenneth Walker III",
    "position": "RB",
    "team": "KCC",
    "age": 25.7,
    "value": 5482,
    "rank": 48,
    "positionalRank": 11,
    "tier": 10,
    "trend": 0,
    "rookie": false
  },
  {
    "name": "Chris Olave",
    "position": "WR",
    "team": "NOS",
    "age": 26.0,
    "value": 5479,
    "rank": 49,
    "positionalRank": 16,
    "tier": 10,
    "trend": -4,
    "rookie": false
  },
  {
    "name": "Luther Burden",
    "position": "WR",
    "team": "CHI",
    "age": 22.6,
    "value": 5458,
    "rank": 50,
    "positionalRank": 17,
    "tier": 10,
    "trend": 1,
    "rookie": false
  },
  {
    "name": "DeVonta Smith",
    "position": "WR",
    "team": "PHI",
    "age": 27.6,
    "value": 5423,
    "rank": 51,
    "positionalRank": 18,
    "tier": 10,
    "trend": -2,
    "rookie": false
  },
  {
    "name": "Breece Hall",
    "position": "RB",
    "team": "NYJ",
    "age": 25.1,
    "value": 5394,
    "rank": 52,
    "positionalRank": 12,
    "tier": 10,
    "trend": -2,
    "rookie": false
  },
  {
    "name": "Jordyn Tyson",
    "position": "WR",
    "team": "NOS",
    "age": 21.9,
    "value": 5388,
    "rank": 53,
    "positionalRank": 19,
    "tier": 10,
    "trend": 2,
    "rookie": true
  },
  {
    "name": "Cam Ward",
    "position": "QB",
    "team": "TEN",
    "age": 24.1,
    "value": 5384,
    "rank": 54,
    "positionalRank": 16,
    "tier": 10,
    "trend": -1,
    "rookie": false
  },
  {
    "name": "Rome Odunze",
    "position": "WR",
    "team": "CHI",
    "age": 24.1,
    "value": 5225,
    "rank": 55,
    "positionalRank": 20,
    "tier": 11,
    "trend": -1,
    "rookie": false
  },
  {
    "name": "Chase Brown",
    "position": "RB",
    "team": "CIN",
    "age": 26.3,
    "value": 5121,
    "rank": 56,
    "positionalRank": 13,
    "tier": 12,
    "trend": 1,
    "rookie": false
  },
  {
    "name": "Makai Lemon",
    "position": "WR",
    "team": "PHI",
    "age": 22.1,
    "value": 5082,
    "rank": 57,
    "positionalRank": 21,
    "tier": 12,
    "trend": -1,
    "rookie": true
  },
  {
    "name": "2028 Early 1st",
    "position": "RDP",
    "team": "FA",
    "age": 0.0,
    "value": 5031,
    "rank": 58,
    "positionalRank": null,
    "tier": 12,
    "trend": 0,
    "rookie": false
  },
  {
    "name": "A.J. Brown",
    "position": "WR",
    "team": "NEP",
    "age": 29.0,
    "value": 4985,
    "rank": 59,
    "positionalRank": 22,
    "tier": 12,
    "trend": 1,
    "rookie": false
  },
  {
    "name": "Christian McCaffrey",
    "position": "RB",
    "team": "SFO",
    "age": 30.1,
    "value": 4983,
    "rank": 60,
    "positionalRank": 14,
    "tier": 12,
    "trend": -1,
    "rookie": false
  },
  {
    "name": "Marvin Harrison Jr.",
    "position": "WR",
    "team": "ARI",
    "age": 23.9,
    "value": 4944,
    "rank": 61,
    "positionalRank": 23,
    "tier": 12,
    "trend": 1,
    "rookie": false
  },
  {
    "name": "Saquon Barkley",
    "position": "RB",
    "team": "PHI",
    "age": 29.4,
    "value": 4937,
    "rank": 62,
    "positionalRank": 15,
    "tier": 12,
    "trend": 2,
    "rookie": false
  },
  {
    "name": "Tucker Kraft",
    "position": "TE",
    "team": "GBP",
    "age": 25.7,
    "value": 4931,
    "rank": 63,
    "positionalRank": 5,
    "tier": 12,
    "trend": 6,
    "rookie": false
  },
  {
    "name": "Tee Higgins",
    "position": "WR",
    "team": "CIN",
    "age": 27.5,
    "value": 4912,
    "rank": 64,
    "positionalRank": 24,
    "tier": 12,
    "trend": 1,
    "rookie": false
  },
  {
    "name": "Zay Flowers",
    "position": "WR",
    "team": "BAL",
    "age": 25.8,
    "value": 4909,
    "rank": 65,
    "positionalRank": 25,
    "tier": 12,
    "trend": 7,
    "rookie": false
  },
  {
    "name": "2027 Late 1st",
    "position": "RDP",
    "team": "FA",
    "age": 0.0,
    "value": 4901,
    "rank": 66,
    "positionalRank": null,
    "tier": 12,
    "trend": -3,
    "rookie": false
  },
  {
    "name": "Brian Thomas Jr.",
    "position": "WR",
    "team": "JAC",
    "age": 23.7,
    "value": 4880,
    "rank": 67,
    "positionalRank": 26,
    "tier": 12,
    "trend": 6,
    "rookie": false
  },
  {
    "name": "Dak Prescott",
    "position": "QB",
    "team": "DAL",
    "age": 32.9,
    "value": 4876,
    "rank": 68,
    "positionalRank": 17,
    "tier": 12,
    "trend": -7,
    "rookie": false
  },
  {
    "name": "Kyren Williams",
    "position": "RB",
    "team": "LAR",
    "age": 25.9,
    "value": 4872,
    "rank": 69,
    "positionalRank": 16,
    "tier": 12,
    "trend": -1,
    "rookie": false
  },
  {
    "name": "Harold Fannin",
    "position": "TE",
    "team": "CLE",
    "age": 22.0,
    "value": 4856,
    "rank": 70,
    "positionalRank": 6,
    "tier": 12,
    "trend": -4,
    "rookie": false
  },
  {
    "name": "Tyler Shough",
    "position": "QB",
    "team": "NOS",
    "age": 26.8,
    "value": 4841,
    "rank": 71,
    "positionalRank": 18,
    "tier": 12,
    "trend": -1,
    "rookie": false
  },
  {
    "name": "Jadarian Price",
    "position": "RB",
    "team": "SEA",
    "age": 22.7,
    "value": 4810,
    "rank": 72,
    "positionalRank": 17,
    "tier": 12,
    "trend": -5,
    "rookie": true
  },
  {
    "name": "Cam Skattebo",
    "position": "RB",
    "team": "NYG",
    "age": 24.4,
    "value": 4800,
    "rank": 73,
    "positionalRank": 18,
    "tier": 12,
    "trend": 4,
    "rookie": false
  },
  {
    "name": "C.J. Stroud",
    "position": "QB",
    "team": "HOU",
    "age": 24.8,
    "value": 4762,
    "rank": 74,
    "positionalRank": 19,
    "tier": 12,
    "trend": -3,
    "rookie": false
  },
  {
    "name": "Jaylen Waddle",
    "position": "WR",
    "team": "DEN",
    "age": 27.6,
    "value": 4759,
    "rank": 75,
    "positionalRank": 27,
    "tier": 12,
    "trend": -1,
    "rookie": false
  },
  {
    "name": "Baker Mayfield",
    "position": "QB",
    "team": "TBB",
    "age": 31.2,
    "value": 4716,
    "rank": 76,
    "positionalRank": 20,
    "tier": 12,
    "trend": 0,
    "rookie": false
  },
  {
    "name": "Jared Goff",
    "position": "QB",
    "team": "DET",
    "age": 31.7,
    "value": 4715,
    "rank": 77,
    "positionalRank": 21,
    "tier": 12,
    "trend": 2,
    "rookie": false
  },
  {
    "name": "Rashee Rice",
    "position": "WR",
    "team": "KCC",
    "age": 26.2,
    "value": 4712,
    "rank": 78,
    "positionalRank": 28,
    "tier": 12,
    "trend": 3,
    "rookie": false
  },
  {
    "name": "Jameson Williams",
    "position": "WR",
    "team": "DET",
    "age": 25.3,
    "value": 4705,
    "rank": 79,
    "positionalRank": 29,
    "tier": 12,
    "trend": -1,
    "rookie": false
  },
  {
    "name": "Bucky Irving",
    "position": "RB",
    "team": "TBB",
    "age": 23.9,
    "value": 4695,
    "rank": 80,
    "positionalRank": 19,
    "tier": 12,
    "trend": -5,
    "rookie": false
  },
  {
    "name": "2026 Mid 1st",
    "position": "RDP",
    "team": "FA",
    "age": 0.0,
    "value": 4612,
    "rank": 81,
    "positionalRank": null,
    "tier": 13,
    "trend": 1,
    "rookie": false
  },
  {
    "name": "2028 Mid 1st",
    "position": "RDP",
    "team": "FA",
    "age": 0.0,
    "value": 4605,
    "rank": 82,
    "positionalRank": null,
    "tier": 13,
    "trend": 4,
    "rookie": false
  },
  {
    "name": "Kyle Pitts",
    "position": "TE",
    "team": "ATL",
    "age": 25.8,
    "value": 4540,
    "rank": 83,
    "positionalRank": 7,
    "tier": 13,
    "trend": 5,
    "rookie": false
  },
  {
    "name": "Sam Darnold",
    "position": "QB",
    "team": "SEA",
    "age": 29.1,
    "value": 4521,
    "rank": 84,
    "positionalRank": 22,
    "tier": 13,
    "trend": -4,
    "rookie": false
  },
  {
    "name": "Javonte Williams",
    "position": "RB",
    "team": "DAL",
    "age": 26.2,
    "value": 4508,
    "rank": 85,
    "positionalRank": 20,
    "tier": 13,
    "trend": -2,
    "rookie": false
  },
  {
    "name": "KC Concepcion",
    "position": "WR",
    "team": "CLE",
    "age": 21.8,
    "value": 4460,
    "rank": 86,
    "positionalRank": 30,
    "tier": 13,
    "trend": -1,
    "rookie": true
  },
  {
    "name": "Sam LaPorta",
    "position": "TE",
    "team": "DET",
    "age": 25.5,
    "value": 4459,
    "rank": 87,
    "positionalRank": 8,
    "tier": 13,
    "trend": -3,
    "rookie": false
  },
  {
    "name": "Travis Etienne",
    "position": "RB",
    "team": "NOS",
    "age": 27.4,
    "value": 4456,
    "rank": 88,
    "positionalRank": 21,
    "tier": 13,
    "trend": -1,
    "rookie": false
  },
  {
    "name": "Bryce Young",
    "position": "QB",
    "team": "CAR",
    "age": 25.0,
    "value": 4273,
    "rank": 89,
    "positionalRank": 23,
    "tier": 14,
    "trend": 0,
    "rookie": false
  },
  {
    "name": "Kyler Murray",
    "position": "QB",
    "team": "MIN",
    "age": 28.9,
    "value": 4140,
    "rank": 90,
    "positionalRank": 24,
    "tier": 15,
    "trend": 1,
    "rookie": false
  },
  {
    "name": "2028 Late 1st",
    "position": "RDP",
    "team": "FA",
    "age": 0.0,
    "value": 4109,
    "rank": 91,
    "positionalRank": null,
    "tier": 15,
    "trend": 1,
    "rookie": false
  },
  {
    "name": "Bhayshul Tuten",
    "position": "RB",
    "team": "JAC",
    "age": 23.4,
    "value": 4097,
    "rank": 92,
    "positionalRank": 22,
    "tier": 15,
    "trend": 2,
    "rookie": false
  },
  {
    "name": "Derrick Henry",
    "position": "RB",
    "team": "BAL",
    "age": 32.5,
    "value": 4029,
    "rank": 93,
    "positionalRank": 23,
    "tier": 15,
    "trend": 2,
    "rookie": false
  },
  {
    "name": "Kenyon Sadiq",
    "position": "TE",
    "team": "NYJ",
    "age": 21.3,
    "value": 4025,
    "rank": 94,
    "positionalRank": 9,
    "tier": 15,
    "trend": -4,
    "rookie": true
  },
  {
    "name": "Alec Pierce",
    "position": "WR",
    "team": "IND",
    "age": 26.2,
    "value": 3991,
    "rank": 95,
    "positionalRank": 31,
    "tier": 15,
    "trend": -2,
    "rookie": false
  },
  {
    "name": "Christian Watson",
    "position": "WR",
    "team": "GBP",
    "age": 27.2,
    "value": 3951,
    "rank": 96,
    "positionalRank": 32,
    "tier": 15,
    "trend": 6,
    "rookie": false
  },
  {
    "name": "Jordan Addison",
    "position": "WR",
    "team": "MIN",
    "age": 24.4,
    "value": 3942,
    "rank": 97,
    "positionalRank": 33,
    "tier": 15,
    "trend": -1,
    "rookie": false
  },
  {
    "name": "Daniel Jones",
    "position": "QB",
    "team": "IND",
    "age": 29.1,
    "value": 3902,
    "rank": 98,
    "positionalRank": 25,
    "tier": 15,
    "trend": 2,
    "rookie": false
  },
  {
    "name": "Josh Jacobs",
    "position": "RB",
    "team": "GBP",
    "age": 28.4,
    "value": 3901,
    "rank": 99,
    "positionalRank": 24,
    "tier": 15,
    "trend": 7,
    "rookie": false
  },
  {
    "name": "2027 Early 2nd",
    "position": "RDP",
    "team": "FA",
    "age": 0.0,
    "value": 3862,
    "rank": 100,
    "positionalRank": null,
    "tier": 15,
    "trend": -1,
    "rookie": false
  },
  {
    "name": "2026 Late 1st",
    "position": "RDP",
    "team": "FA",
    "age": 0.0,
    "value": 3860,
    "rank": 101,
    "positionalRank": null,
    "tier": 15,
    "trend": -3,
    "rookie": false
  },
  {
    "name": "Malik Willis",
    "position": "QB",
    "team": "MIA",
    "age": 27.1,
    "value": 3839,
    "rank": 102,
    "positionalRank": 26,
    "tier": 15,
    "trend": -5,
    "rookie": false
  },
  {
    "name": "Matthew Stafford",
    "position": "QB",
    "team": "LAR",
    "age": 38.4,
    "value": 3824,
    "rank": 103,
    "positionalRank": 27,
    "tier": 15,
    "trend": 0,
    "rookie": false
  },
  {
    "name": "Parker Washington",
    "position": "WR",
    "team": "JAC",
    "age": 24.3,
    "value": 3689,
    "rank": 104,
    "positionalRank": 34,
    "tier": 16,
    "trend": 7,
    "rookie": false
  },
  {
    "name": "Omar Cooper Jr.",
    "position": "WR",
    "team": "NYJ",
    "age": 22.6,
    "value": 3673,
    "rank": 105,
    "positionalRank": 35,
    "tier": 16,
    "trend": -4,
    "rookie": true
  },
  {
    "name": "Josh Downs",
    "position": "WR",
    "team": "IND",
    "age": 24.9,
    "value": 3636,
    "rank": 106,
    "positionalRank": 36,
    "tier": 16,
    "trend": 1,
    "rookie": false
  },
  {
    "name": "Matthew Golden",
    "position": "WR",
    "team": "GBP",
    "age": 22.9,
    "value": 3621,
    "rank": 107,
    "positionalRank": 37,
    "tier": 16,
    "trend": -2,
    "rookie": false
  },
  {
    "name": "Michael Wilson",
    "position": "WR",
    "team": "ARI",
    "age": 26.4,
    "value": 3615,
    "rank": 108,
    "positionalRank": 38,
    "tier": 16,
    "trend": 4,
    "rookie": false
  },
  {
    "name": "Oronde Gadsden",
    "position": "TE",
    "team": "LAC",
    "age": 23.0,
    "value": 3614,
    "rank": 109,
    "positionalRank": 10,
    "tier": 16,
    "trend": 1,
    "rookie": false
  },
  {
    "name": "D'Andre Swift",
    "position": "RB",
    "team": "CHI",
    "age": 27.5,
    "value": 3612,
    "rank": 110,
    "positionalRank": 25,
    "tier": 16,
    "trend": 4,
    "rookie": false
  },
  {
    "name": "D.J. Moore",
    "position": "WR",
    "team": "BUF",
    "age": 29.2,
    "value": 3599,
    "rank": 111,
    "positionalRank": 39,
    "tier": 16,
    "trend": -7,
    "rookie": false
  },
  {
    "name": "Eli Stowers",
    "position": "TE",
    "team": "PHI",
    "age": 23.2,
    "value": 3579,
    "rank": 112,
    "positionalRank": 11,
    "tier": 16,
    "trend": -3,
    "rookie": true
  },
  {
    "name": "Ty Simpson",
    "position": "QB",
    "team": "LAR",
    "age": 23.5,
    "value": 3573,
    "rank": 113,
    "positionalRank": 28,
    "tier": 16,
    "trend": -6,
    "rookie": true
  },
  {
    "name": "Quentin Johnston",
    "position": "WR",
    "team": "LAC",
    "age": 24.8,
    "value": 3545,
    "rank": 114,
    "positionalRank": 40,
    "tier": 16,
    "trend": 10,
    "rookie": false
  },
  {
    "name": "Kyle Monangai",
    "position": "RB",
    "team": "CHI",
    "age": 24.1,
    "value": 3522,
    "rank": 115,
    "positionalRank": 26,
    "tier": 16,
    "trend": -2,
    "rookie": false
  },
  {
    "name": "Terry McLaurin",
    "position": "WR",
    "team": "WAS",
    "age": 30.8,
    "value": 3512,
    "rank": 116,
    "positionalRank": 41,
    "tier": 16,
    "trend": 1,
    "rookie": false
  },
  {
    "name": "Wan'Dale Robinson",
    "position": "WR",
    "team": "TEN",
    "age": 25.5,
    "value": 3498,
    "rank": 117,
    "positionalRank": 42,
    "tier": 16,
    "trend": -2,
    "rookie": false
  },
  {
    "name": "Denzel Boston",
    "position": "WR",
    "team": "CLE",
    "age": -1.0,
    "value": 3467,
    "rank": 118,
    "positionalRank": 43,
    "tier": 16,
    "trend": 2,
    "rookie": true
  },
  {
    "name": "DK Metcalf",
    "position": "WR",
    "team": "PIT",
    "age": 28.6,
    "value": 3458,
    "rank": 119,
    "positionalRank": 44,
    "tier": 16,
    "trend": -3,
    "rookie": false
  },
  {
    "name": "Jayden Higgins",
    "position": "WR",
    "team": "HOU",
    "age": 23.6,
    "value": 3453,
    "rank": 120,
    "positionalRank": 45,
    "tier": 16,
    "trend": 3,
    "rookie": false
  },
  {
    "name": "2027 Mid 2nd",
    "position": "RDP",
    "team": "FA",
    "age": 0.0,
    "value": 3429,
    "rank": 121,
    "positionalRank": null,
    "tier": 16,
    "trend": -2,
    "rookie": false
  },
  {
    "name": "Jayden Reed",
    "position": "WR",
    "team": "GBP",
    "age": 26.2,
    "value": 3387,
    "rank": 122,
    "positionalRank": 46,
    "tier": 16,
    "trend": -4,
    "rookie": false
  },
  {
    "name": "Ricky Pearsall",
    "position": "WR",
    "team": "SFO",
    "age": 25.8,
    "value": 3384,
    "rank": 123,
    "positionalRank": 47,
    "tier": 16,
    "trend": -1,
    "rookie": false
  },
  {
    "name": "RJ Harvey",
    "position": "RB",
    "team": "DEN",
    "age": 25.4,
    "value": 3383,
    "rank": 124,
    "positionalRank": 27,
    "tier": 16,
    "trend": -3,
    "rookie": false
  },
  {
    "name": "Isaiah Likely",
    "position": "TE",
    "team": "NYG",
    "age": 26.2,
    "value": 3382,
    "rank": 125,
    "positionalRank": 12,
    "tier": 16,
    "trend": 0,
    "rookie": false
  },
  {
    "name": "David Montgomery",
    "position": "RB",
    "team": "HOU",
    "age": 29.1,
    "value": 3381,
    "rank": 126,
    "positionalRank": 28,
    "tier": 16,
    "trend": 0,
    "rookie": false
  },
  {
    "name": "Michael Pittman",
    "position": "WR",
    "team": "PIT",
    "age": 28.8,
    "value": 3370,
    "rank": 127,
    "positionalRank": 48,
    "tier": 16,
    "trend": 2,
    "rookie": false
  },
  {
    "name": "Blake Corum",
    "position": "RB",
    "team": "LAR",
    "age": 25.6,
    "value": 3351,
    "rank": 128,
    "positionalRank": 29,
    "tier": 16,
    "trend": 5,
    "rookie": false
  },
  {
    "name": "Zach Charbonnet",
    "position": "RB",
    "team": "SEA",
    "age": 25.5,
    "value": 3348,
    "rank": 129,
    "positionalRank": 30,
    "tier": 16,
    "trend": -1,
    "rookie": false
  },
  {
    "name": "Jonathon Brooks",
    "position": "RB",
    "team": "CAR",
    "age": 23.0,
    "value": 3345,
    "rank": 130,
    "positionalRank": 31,
    "tier": 16,
    "trend": 8,
    "rookie": false
  },
  {
    "name": "Xavier Worthy",
    "position": "WR",
    "team": "KCC",
    "age": 23.2,
    "value": 3345,
    "rank": 131,
    "positionalRank": 49,
    "tier": 16,
    "trend": 3,
    "rookie": false
  },
  {
    "name": "Davante Adams",
    "position": "WR",
    "team": "LAR",
    "age": 33.5,
    "value": 3344,
    "rank": 132,
    "positionalRank": 50,
    "tier": 16,
    "trend": -2,
    "rookie": false
  },
  {
    "name": "Travis Hunter",
    "position": "WR",
    "team": "JAC",
    "age": 23.1,
    "value": 3340,
    "rank": 133,
    "positionalRank": 51,
    "tier": 16,
    "trend": -6,
    "rookie": false
  },
  {
    "name": "Mike Evans",
    "position": "WR",
    "team": "SFO",
    "age": 32.9,
    "value": 3338,
    "rank": 134,
    "positionalRank": 52,
    "tier": 16,
    "trend": -3,
    "rookie": false
  },
  {
    "name": "2026 Early 2nd",
    "position": "RDP",
    "team": "FA",
    "age": 0.0,
    "value": 3294,
    "rank": 135,
    "positionalRank": null,
    "tier": 16,
    "trend": 0,
    "rookie": false
  },
  {
    "name": "Chuba Hubbard",
    "position": "RB",
    "team": "CAR",
    "age": 27.1,
    "value": 3279,
    "rank": 136,
    "positionalRank": 32,
    "tier": 16,
    "trend": -4,
    "rookie": false
  },
  {
    "name": "George Kittle",
    "position": "TE",
    "team": "SFO",
    "age": 32.7,
    "value": 3251,
    "rank": 137,
    "positionalRank": 13,
    "tier": 16,
    "trend": -1,
    "rookie": false
  },
  {
    "name": "2028 Early 2nd",
    "position": "RDP",
    "team": "FA",
    "age": 0.0,
    "value": 3227,
    "rank": 138,
    "positionalRank": null,
    "tier": 16,
    "trend": 3,
    "rookie": false
  },
  {
    "name": "Jaylen Warren",
    "position": "RB",
    "team": "PIT",
    "age": 27.7,
    "value": 3204,
    "rank": 139,
    "positionalRank": 33,
    "tier": 16,
    "trend": 0,
    "rookie": false
  },
  {
    "name": "Jonah Coleman",
    "position": "RB",
    "team": "DEN",
    "age": 22.9,
    "value": 3188,
    "rank": 140,
    "positionalRank": 34,
    "tier": 16,
    "trend": 5,
    "rookie": true
  },
  {
    "name": "Jalen Coker",
    "position": "WR",
    "team": "CAR",
    "age": 24.7,
    "value": 3179,
    "rank": 141,
    "positionalRank": 53,
    "tier": 16,
    "trend": 8,
    "rookie": false
  },
  {
    "name": "Jake Ferguson",
    "position": "TE",
    "team": "DAL",
    "age": 27.5,
    "value": 3175,
    "rank": 142,
    "positionalRank": 14,
    "tier": 16,
    "trend": -5,
    "rookie": false
  },
  {
    "name": "Rico Dowdle",
    "position": "RB",
    "team": "PIT",
    "age": 28.1,
    "value": 3160,
    "rank": 143,
    "positionalRank": 35,
    "tier": 16,
    "trend": 1,
    "rookie": false
  },
  {
    "name": "Dalton Kincaid",
    "position": "TE",
    "team": "BUF",
    "age": 26.7,
    "value": 3158,
    "rank": 144,
    "positionalRank": 15,
    "tier": 16,
    "trend": -4,
    "rookie": false
  },
  {
    "name": "2027 Late 2nd",
    "position": "RDP",
    "team": "FA",
    "age": 0.0,
    "value": 3135,
    "rank": 145,
    "positionalRank": null,
    "tier": 16,
    "trend": -3,
    "rookie": false
  },
  {
    "name": "Courtland Sutton",
    "position": "WR",
    "team": "DEN",
    "age": 30.7,
    "value": 3099,
    "rank": 146,
    "positionalRank": 54,
    "tier": 16,
    "trend": 1,
    "rookie": false
  },
  {
    "name": "Jalen McMillan",
    "position": "WR",
    "team": "TBB",
    "age": 24.6,
    "value": 3095,
    "rank": 147,
    "positionalRank": 55,
    "tier": 16,
    "trend": 3,
    "rookie": false
  },
  {
    "name": "Romeo Doubs",
    "position": "WR",
    "team": "NEP",
    "age": 26.2,
    "value": 3090,
    "rank": 148,
    "positionalRank": 56,
    "tier": 16,
    "trend": -5,
    "rookie": false
  },
  {
    "name": "Chris Bell",
    "position": "WR",
    "team": "MIA",
    "age": 22.1,
    "value": 3072,
    "rank": 149,
    "positionalRank": 57,
    "tier": 16,
    "trend": 3,
    "rookie": true
  },
  {
    "name": "Jakobi Meyers",
    "position": "WR",
    "team": "JAC",
    "age": 29.6,
    "value": 3062,
    "rank": 150,
    "positionalRank": 58,
    "tier": 16,
    "trend": -2,
    "rookie": false
  },
  {
    "name": "Antonio Williams",
    "position": "WR",
    "team": "WAS",
    "age": -1.0,
    "value": 3035,
    "rank": 151,
    "positionalRank": 59,
    "tier": 16,
    "trend": 0,
    "rookie": true
  },
  {
    "name": "Brenton Strange",
    "position": "TE",
    "team": "JAC",
    "age": 25.5,
    "value": 3027,
    "rank": 152,
    "positionalRank": 16,
    "tier": 16,
    "trend": 3,
    "rookie": false
  },
  {
    "name": "Michael Penix Jr.",
    "position": "QB",
    "team": "ATL",
    "age": 26.2,
    "value": 2988,
    "rank": 153,
    "positionalRank": 29,
    "tier": 16,
    "trend": -7,
    "rookie": false
  },
  {
    "name": "J.K. Dobbins",
    "position": "RB",
    "team": "DEN",
    "age": 27.6,
    "value": 2980,
    "rank": 154,
    "positionalRank": 36,
    "tier": 16,
    "trend": 2,
    "rookie": false
  },
  {
    "name": "2026 Mid 2nd",
    "position": "RDP",
    "team": "FA",
    "age": 0.0,
    "value": 2979,
    "rank": 155,
    "positionalRank": null,
    "tier": 16,
    "trend": -1,
    "rookie": false
  },
  {
    "name": "2028 Mid 2nd",
    "position": "RDP",
    "team": "FA",
    "age": 0.0,
    "value": 2976,
    "rank": 156,
    "positionalRank": null,
    "tier": 16,
    "trend": -3,
    "rookie": false
  },
  {
    "name": "Rhamondre Stevenson",
    "position": "RB",
    "team": "NEP",
    "age": 28.4,
    "value": 2964,
    "rank": 157,
    "positionalRank": 37,
    "tier": 16,
    "trend": 1,
    "rookie": false
  },
  {
    "name": "Jacory Croskey-Merritt",
    "position": "RB",
    "team": "WAS",
    "age": 25.2,
    "value": 2961,
    "rank": 158,
    "positionalRank": 38,
    "tier": 16,
    "trend": 2,
    "rookie": false
  },
  {
    "name": "Chris Godwin",
    "position": "WR",
    "team": "TBB",
    "age": 30.4,
    "value": 2951,
    "rank": 159,
    "positionalRank": 60,
    "tier": 16,
    "trend": 3,
    "rookie": false
  },
  {
    "name": "Germie Bernard",
    "position": "WR",
    "team": "PIT",
    "age": 22.6,
    "value": 2940,
    "rank": 160,
    "positionalRank": 61,
    "tier": 16,
    "trend": -2,
    "rookie": true
  },
  {
    "name": "Khalil Shakir",
    "position": "WR",
    "team": "BUF",
    "age": 26.4,
    "value": 2928,
    "rank": 161,
    "positionalRank": 62,
    "tier": 16,
    "trend": 0,
    "rookie": false
  },
  {
    "name": "Kenneth Gainwell",
    "position": "RB",
    "team": "TBB",
    "age": 27.3,
    "value": 2920,
    "rank": 162,
    "positionalRank": 39,
    "tier": 16,
    "trend": 1,
    "rookie": false
  },
  {
    "name": "Nicholas Singleton",
    "position": "RB",
    "team": "TEN",
    "age": -1.0,
    "value": 2899,
    "rank": 163,
    "positionalRank": 40,
    "tier": 16,
    "trend": -6,
    "rookie": true
  },
  {
    "name": "Chigoziem Okonkwo",
    "position": "TE",
    "team": "WAS",
    "age": 26.8,
    "value": 2828,
    "rank": 164,
    "positionalRank": 17,
    "tier": 17,
    "trend": 9,
    "rookie": false
  },
  {
    "name": "Tony Pollard",
    "position": "RB",
    "team": "TEN",
    "age": 29.2,
    "value": 2816,
    "rank": 165,
    "positionalRank": 41,
    "tier": 17,
    "trend": 2,
    "rookie": false
  },
  {
    "name": "2026 Late 2nd",
    "position": "RDP",
    "team": "FA",
    "age": 0.0,
    "value": 2794,
    "rank": 166,
    "positionalRank": null,
    "tier": 17,
    "trend": -1,
    "rookie": false
  },
  {
    "name": "AJ Barner",
    "position": "TE",
    "team": "SEA",
    "age": 24.2,
    "value": 2790,
    "rank": 167,
    "positionalRank": 18,
    "tier": 17,
    "trend": 3,
    "rookie": false
  },
  {
    "name": "2028 Late 2nd",
    "position": "RDP",
    "team": "FA",
    "age": 0.0,
    "value": 2789,
    "rank": 168,
    "positionalRank": null,
    "tier": 17,
    "trend": 1,
    "rookie": false
  },
  {
    "name": "Rachaad White",
    "position": "RB",
    "team": "WAS",
    "age": 27.5,
    "value": 2787,
    "rank": 169,
    "positionalRank": 42,
    "tier": 17,
    "trend": 8,
    "rookie": false
  },
  {
    "name": "Elijah Sarratt",
    "position": "WR",
    "team": "BAL",
    "age": -1.0,
    "value": 2781,
    "rank": 170,
    "positionalRank": 63,
    "tier": 17,
    "trend": 1,
    "rookie": true
  },
  {
    "name": "Mark Andrews",
    "position": "TE",
    "team": "BAL",
    "age": 30.8,
    "value": 2774,
    "rank": 171,
    "positionalRank": 19,
    "tier": 17,
    "trend": 9,
    "rookie": false
  },
  {
    "name": "Rashid Shaheed",
    "position": "WR",
    "team": "SEA",
    "age": 27.8,
    "value": 2759,
    "rank": 172,
    "positionalRank": 64,
    "tier": 17,
    "trend": -8,
    "rookie": false
  },
  {
    "name": "Isaac TeSlaa",
    "position": "WR",
    "team": "DET",
    "age": 24.4,
    "value": 2758,
    "rank": 173,
    "positionalRank": 65,
    "tier": 17,
    "trend": 2,
    "rookie": false
  },
  {
    "name": "Tua Tagovailoa",
    "position": "QB",
    "team": "ATL",
    "age": 28.4,
    "value": 2757,
    "rank": 174,
    "positionalRank": 30,
    "tier": 17,
    "trend": 5,
    "rookie": false
  },
  {
    "name": "Jaylin Noel",
    "position": "WR",
    "team": "HOU",
    "age": 23.8,
    "value": 2732,
    "rank": 175,
    "positionalRank": 66,
    "tier": 17,
    "trend": 8,
    "rookie": false
  },
  {
    "name": "Tre Harris",
    "position": "WR",
    "team": "LAC",
    "age": 24.4,
    "value": 2731,
    "rank": 176,
    "positionalRank": 67,
    "tier": 17,
    "trend": 2,
    "rookie": false
  },
  {
    "name": "Woody Marks",
    "position": "RB",
    "team": "HOU",
    "age": 25.5,
    "value": 2727,
    "rank": 177,
    "positionalRank": 43,
    "tier": 17,
    "trend": -5,
    "rookie": false
  },
  {
    "name": "J.J. McCarthy",
    "position": "QB",
    "team": "MIN",
    "age": 23.5,
    "value": 2726,
    "rank": 178,
    "positionalRank": 31,
    "tier": 17,
    "trend": -10,
    "rookie": false
  },
  {
    "name": "De'Zhaun Stribling",
    "position": "WR",
    "team": "SFO",
    "age": 23.6,
    "value": 2726,
    "rank": 179,
    "positionalRank": 68,
    "tier": 17,
    "trend": 26,
    "rookie": true
  },
  {
    "name": "T.J. Hockenson",
    "position": "TE",
    "team": "MIN",
    "age": 29.0,
    "value": 2724,
    "rank": 180,
    "positionalRank": 20,
    "tier": 17,
    "trend": -14,
    "rookie": false
  },
  {
    "name": "Tyler Allgeier",
    "position": "RB",
    "team": "ARI",
    "age": 26.2,
    "value": 2723,
    "rank": 181,
    "positionalRank": 44,
    "tier": 17,
    "trend": -7,
    "rookie": false
  },
  {
    "name": "Zachariah Branch",
    "position": "WR",
    "team": "ATL",
    "age": -1.0,
    "value": 2721,
    "rank": 182,
    "positionalRank": 69,
    "tier": 17,
    "trend": -1,
    "rookie": true
  },
  {
    "name": "Dylan Sampson",
    "position": "RB",
    "team": "CLE",
    "age": 21.8,
    "value": 2712,
    "rank": 183,
    "positionalRank": 45,
    "tier": 17,
    "trend": -1,
    "rookie": false
  },
  {
    "name": "Shedeur Sanders",
    "position": "QB",
    "team": "CLE",
    "age": 24.4,
    "value": 2709,
    "rank": 184,
    "positionalRank": 32,
    "tier": 17,
    "trend": -8,
    "rookie": false
  },
  {
    "name": "Malachi Fields",
    "position": "WR",
    "team": "NYG",
    "age": -1.0,
    "value": 2702,
    "rank": 185,
    "positionalRank": 70,
    "tier": 17,
    "trend": 0,
    "rookie": true
  },
  {
    "name": "Terrance Ferguson",
    "position": "TE",
    "team": "LAR",
    "age": 23.3,
    "value": 2690,
    "rank": 186,
    "positionalRank": 21,
    "tier": 17,
    "trend": 6,
    "rookie": false
  },
  {
    "name": "Braelon Allen",
    "position": "RB",
    "team": "NYJ",
    "age": 22.5,
    "value": 2670,
    "rank": 187,
    "positionalRank": 46,
    "tier": 17,
    "trend": 1,
    "rookie": false
  },
  {
    "name": "Tyrone Tracy",
    "position": "RB",
    "team": "NYG",
    "age": 26.6,
    "value": 2669,
    "rank": 188,
    "positionalRank": 47,
    "tier": 17,
    "trend": 1,
    "rookie": false
  },
  {
    "name": "Jordan Mason",
    "position": "RB",
    "team": "MIN",
    "age": 27.1,
    "value": 2668,
    "rank": 189,
    "positionalRank": 48,
    "tier": 17,
    "trend": -3,
    "rookie": false
  },
  {
    "name": "Jacoby Brissett",
    "position": "QB",
    "team": "ARI",
    "age": 33.6,
    "value": 2665,
    "rank": 190,
    "positionalRank": 33,
    "tier": 17,
    "trend": 2,
    "rookie": false
  },
  {
    "name": "Mac Jones",
    "position": "QB",
    "team": "SFO",
    "age": 27.8,
    "value": 2663,
    "rank": 191,
    "positionalRank": 34,
    "tier": 17,
    "trend": -4,
    "rookie": false
  },
  {
    "name": "Chris Rodriguez",
    "position": "RB",
    "team": "JAC",
    "age": 25.8,
    "value": 2647,
    "rank": 192,
    "positionalRank": 49,
    "tier": 17,
    "trend": 3,
    "rookie": false
  },
  {
    "name": "Tory Horton",
    "position": "WR",
    "team": "SEA",
    "age": 23.6,
    "value": 2637,
    "rank": 193,
    "positionalRank": 71,
    "tier": 17,
    "trend": -9,
    "rookie": false
  },
  {
    "name": "Gunnar Helm",
    "position": "TE",
    "team": "TEN",
    "age": 23.8,
    "value": 2635,
    "rank": 194,
    "positionalRank": 22,
    "tier": 17,
    "trend": 0,
    "rookie": false
  },
  {
    "name": "2027 Early 3rd",
    "position": "RDP",
    "team": "FA",
    "age": 0.0,
    "value": 2633,
    "rank": 195,
    "positionalRank": null,
    "tier": 17,
    "trend": 2,
    "rookie": false
  },
  {
    "name": "Dallas Goedert",
    "position": "TE",
    "team": "PHI",
    "age": 31.5,
    "value": 2622,
    "rank": 196,
    "positionalRank": 23,
    "tier": 17,
    "trend": 4,
    "rookie": false
  },
  {
    "name": "Jauan Jennings",
    "position": "WR",
    "team": "MIN",
    "age": 29.0,
    "value": 2592,
    "rank": 197,
    "positionalRank": 72,
    "tier": 17,
    "trend": -6,
    "rookie": false
  },
  {
    "name": "Troy Franklin",
    "position": "WR",
    "team": "DEN",
    "age": 23.4,
    "value": 2588,
    "rank": 198,
    "positionalRank": 73,
    "tier": 17,
    "trend": -8,
    "rookie": false
  },
  {
    "name": "Emmett Johnson",
    "position": "RB",
    "team": "KCC",
    "age": -1.0,
    "value": 2583,
    "rank": 199,
    "positionalRank": 50,
    "tier": 17,
    "trend": 5,
    "rookie": true
  },
  {
    "name": "Jerry Jeudy",
    "position": "WR",
    "team": "CLE",
    "age": 27.2,
    "value": 2581,
    "rank": 200,
    "positionalRank": 74,
    "tier": 17,
    "trend": -5,
    "rookie": false
  },
  {
    "name": "Tyjae Spears",
    "position": "RB",
    "team": "TEN",
    "age": 25.1,
    "value": 2576,
    "rank": 201,
    "positionalRank": 51,
    "tier": 17,
    "trend": -4,
    "rookie": false
  },
  {
    "name": "Adonai Mitchell",
    "position": "WR",
    "team": "NYJ",
    "age": 23.7,
    "value": 2572,
    "rank": 202,
    "positionalRank": 75,
    "tier": 17,
    "trend": 11,
    "rookie": false
  },
  {
    "name": "Kaytron Allen",
    "position": "RB",
    "team": "WAS",
    "age": -1.0,
    "value": 2571,
    "rank": 203,
    "positionalRank": 52,
    "tier": 17,
    "trend": -1,
    "rookie": true
  },
  {
    "name": "Ted Hurst",
    "position": "WR",
    "team": "TBB",
    "age": 22.0,
    "value": 2565,
    "rank": 204,
    "positionalRank": 76,
    "tier": 17,
    "trend": 16,
    "rookie": true
  },
  {
    "name": "Malik Washington",
    "position": "WR",
    "team": "MIA",
    "age": 25.5,
    "value": 2537,
    "rank": 205,
    "positionalRank": 77,
    "tier": 17,
    "trend": 5,
    "rookie": false
  },
  {
    "name": "2027 Mid 3rd",
    "position": "RDP",
    "team": "FA",
    "age": 0.0,
    "value": 2520,
    "rank": 206,
    "positionalRank": null,
    "tier": 17,
    "trend": 8,
    "rookie": false
  },
  {
    "name": "Chris Brazzell II",
    "position": "WR",
    "team": "CAR",
    "age": -1.0,
    "value": 2514,
    "rank": 207,
    "positionalRank": 78,
    "tier": 17,
    "trend": -6,
    "rookie": true
  },
  {
    "name": "Kayshon Boutte",
    "position": "WR",
    "team": "NEP",
    "age": 24.2,
    "value": 2510,
    "rank": 208,
    "positionalRank": 79,
    "tier": 17,
    "trend": -9,
    "rookie": false
  },
  {
    "name": "Tank Dell",
    "position": "WR",
    "team": "HOU",
    "age": 26.7,
    "value": 2501,
    "rank": 209,
    "positionalRank": 80,
    "tier": 17,
    "trend": -3,
    "rookie": false
  },
  {
    "name": "Keaton Mitchell",
    "position": "RB",
    "team": "LAC",
    "age": 24.5,
    "value": 2499,
    "rank": 210,
    "positionalRank": 53,
    "tier": 17,
    "trend": 9,
    "rookie": false
  },
  {
    "name": "Travis Kelce",
    "position": "TE",
    "team": "KCC",
    "age": 36.8,
    "value": 2496,
    "rank": 211,
    "positionalRank": 24,
    "tier": 17,
    "trend": 0,
    "rookie": false
  },
  {
    "name": "Tre Tucker",
    "position": "WR",
    "team": "LVR",
    "age": 25.3,
    "value": 2493,
    "rank": 212,
    "positionalRank": 81,
    "tier": 17,
    "trend": 4,
    "rookie": false
  },
  {
    "name": "Jack Bech",
    "position": "WR",
    "team": "LVR",
    "age": 23.6,
    "value": 2490,
    "rank": 213,
    "positionalRank": 82,
    "tier": 17,
    "trend": -6,
    "rookie": false
  },
  {
    "name": "Pat Bryant",
    "position": "WR",
    "team": "DEN",
    "age": 23.6,
    "value": 2466,
    "rank": 214,
    "positionalRank": 83,
    "tier": 17,
    "trend": -5,
    "rookie": false
  },
  {
    "name": "Skyler Bell",
    "position": "WR",
    "team": "BUF",
    "age": 24.0,
    "value": 2460,
    "rank": 215,
    "positionalRank": 84,
    "tier": 17,
    "trend": -7,
    "rookie": true
  },
  {
    "name": "Elic Ayomanor",
    "position": "WR",
    "team": "TEN",
    "age": 23.1,
    "value": 2457,
    "rank": 216,
    "positionalRank": 85,
    "tier": 17,
    "trend": -13,
    "rookie": false
  },
  {
    "name": "Tank Bigsby",
    "position": "RB",
    "team": "PHI",
    "age": 24.8,
    "value": 2439,
    "rank": 217,
    "positionalRank": 54,
    "tier": 17,
    "trend": 0,
    "rookie": false
  },
  {
    "name": "Jalen Nailor",
    "position": "WR",
    "team": "LVR",
    "age": 27.4,
    "value": 2436,
    "rank": 218,
    "positionalRank": 86,
    "tier": 17,
    "trend": 8,
    "rookie": false
  },
  {
    "name": "Elijah Arroyo",
    "position": "TE",
    "team": "SEA",
    "age": 23.2,
    "value": 2423,
    "rank": 219,
    "positionalRank": 25,
    "tier": 17,
    "trend": -4,
    "rookie": false
  },
  {
    "name": "David Njoku",
    "position": "TE",
    "team": "LAC",
    "age": 30.0,
    "value": 2421,
    "rank": 220,
    "positionalRank": 26,
    "tier": 17,
    "trend": -8,
    "rookie": false
  },
  {
    "name": "Keon Coleman",
    "position": "WR",
    "team": "BUF",
    "age": 23.1,
    "value": 2417,
    "rank": 221,
    "positionalRank": 87,
    "tier": 17,
    "trend": -3,
    "rookie": false
  },
  {
    "name": "Dontayvion Wicks",
    "position": "WR",
    "team": "PHI",
    "age": 25.0,
    "value": 2410,
    "rank": 222,
    "positionalRank": 88,
    "tier": 17,
    "trend": 5,
    "rookie": false
  },
  {
    "name": "Chimere Dike",
    "position": "WR",
    "team": "TEN",
    "age": 24.6,
    "value": 2410,
    "rank": 223,
    "positionalRank": 89,
    "tier": 17,
    "trend": 1,
    "rookie": false
  },
  {
    "name": "Ja'Kobi Lane",
    "position": "WR",
    "team": "BAL",
    "age": -1.0,
    "value": 2396,
    "rank": 224,
    "positionalRank": 90,
    "tier": 17,
    "trend": -1,
    "rookie": true
  },
  {
    "name": "Ollie Gordon",
    "position": "RB",
    "team": "MIA",
    "age": 22.5,
    "value": 2367,
    "rank": 225,
    "positionalRank": 55,
    "tier": 17,
    "trend": 0,
    "rookie": false
  },
  {
    "name": "Isiah Pacheco",
    "position": "RB",
    "team": "DET",
    "age": 27.4,
    "value": 2356,
    "rank": 226,
    "positionalRank": 56,
    "tier": 17,
    "trend": 7,
    "rookie": false
  },
  {
    "name": "Kyle Williams",
    "position": "WR",
    "team": "NEP",
    "age": 23.6,
    "value": 2355,
    "rank": 227,
    "positionalRank": 91,
    "tier": 17,
    "trend": -5,
    "rookie": false
  },
  {
    "name": "Max Klare",
    "position": "TE",
    "team": "LAR",
    "age": 23.0,
    "value": 2348,
    "rank": 228,
    "positionalRank": 27,
    "tier": 17,
    "trend": 7,
    "rookie": true
  },
  {
    "name": "Kaleb Johnson",
    "position": "RB",
    "team": "PIT",
    "age": 22.9,
    "value": 2347,
    "rank": 229,
    "positionalRank": 57,
    "tier": 17,
    "trend": -8,
    "rookie": false
  },
  {
    "name": "Mike Washington Jr.",
    "position": "RB",
    "team": "LVR",
    "age": -1.0,
    "value": 2336,
    "rank": 230,
    "positionalRank": 58,
    "tier": 17,
    "trend": 0,
    "rookie": true
  },
  {
    "name": "Mason Taylor",
    "position": "TE",
    "team": "NYJ",
    "age": 22.2,
    "value": 2331,
    "rank": 231,
    "positionalRank": 28,
    "tier": 17,
    "trend": -1,
    "rookie": false
  },
  {
    "name": "Brian Robinson",
    "position": "RB",
    "team": "ATL",
    "age": 27.3,
    "value": 2326,
    "rank": 232,
    "positionalRank": 59,
    "tier": 17,
    "trend": -4,
    "rookie": false
  },
  {
    "name": "Cade Otton",
    "position": "TE",
    "team": "TBB",
    "age": 27.2,
    "value": 2325,
    "rank": 233,
    "positionalRank": 29,
    "tier": 17,
    "trend": -1,
    "rookie": false
  },
  {
    "name": "Juwan Johnson",
    "position": "TE",
    "team": "NOS",
    "age": 29.8,
    "value": 2315,
    "rank": 234,
    "positionalRank": 30,
    "tier": 17,
    "trend": -6,
    "rookie": false
  },
  {
    "name": "Aaron Jones",
    "position": "RB",
    "team": "MIN",
    "age": 31.6,
    "value": 2308,
    "rank": 235,
    "positionalRank": 60,
    "tier": 17,
    "trend": -1,
    "rookie": false
  },
  {
    "name": "2026 Early 3rd",
    "position": "RDP",
    "team": "FA",
    "age": 0.0,
    "value": 2296,
    "rank": 236,
    "positionalRank": null,
    "tier": 17,
    "trend": 6,
    "rookie": false
  },
  {
    "name": "Sean Tucker",
    "position": "RB",
    "team": "TBB",
    "age": 24.7,
    "value": 2294,
    "rank": 237,
    "positionalRank": 61,
    "tier": 17,
    "trend": 8,
    "rookie": false
  },
  {
    "name": "Geno Smith",
    "position": "QB",
    "team": "NYJ",
    "age": 35.7,
    "value": 2249,
    "rank": 238,
    "positionalRank": 35,
    "tier": 17,
    "trend": 9,
    "rookie": false
  },
  {
    "name": "Hunter Henry",
    "position": "TE",
    "team": "NEP",
    "age": 31.6,
    "value": 2248,
    "rank": 239,
    "positionalRank": 31,
    "tier": 17,
    "trend": -1,
    "rookie": false
  },
  {
    "name": "Carson Beck",
    "position": "QB",
    "team": "ARI",
    "age": -1.0,
    "value": 2246,
    "rank": 240,
    "positionalRank": 36,
    "tier": 17,
    "trend": 45,
    "rookie": true
  },
  {
    "name": "2028 Early 3rd",
    "position": "RDP",
    "team": "FA",
    "age": 0.0,
    "value": 2243,
    "rank": 241,
    "positionalRank": null,
    "tier": 17,
    "trend": 11,
    "rookie": false
  },
  {
    "name": "Trey Benson",
    "position": "RB",
    "team": "ARI",
    "age": 24.0,
    "value": 2228,
    "rank": 242,
    "positionalRank": 62,
    "tier": 17,
    "trend": -5,
    "rookie": false
  },
  {
    "name": "2027 Late 3rd",
    "position": "RDP",
    "team": "FA",
    "age": 0.0,
    "value": 2227,
    "rank": 243,
    "positionalRank": null,
    "tier": 17,
    "trend": 0,
    "rookie": false
  },
  {
    "name": "Jake Tonges",
    "position": "TE",
    "team": "SFO",
    "age": 27.0,
    "value": 2226,
    "rank": 244,
    "positionalRank": 32,
    "tier": 17,
    "trend": -8,
    "rookie": false
  },
  {
    "name": "Michael Mayer",
    "position": "TE",
    "team": "LVR",
    "age": 25.0,
    "value": 2215,
    "rank": 245,
    "positionalRank": 33,
    "tier": 17,
    "trend": 9,
    "rookie": false
  },
  {
    "name": "Pat Freiermuth",
    "position": "TE",
    "team": "PIT",
    "age": 27.7,
    "value": 2210,
    "rank": 246,
    "positionalRank": 34,
    "tier": 17,
    "trend": -6,
    "rookie": false
  },
  {
    "name": "Jalen Milroe",
    "position": "QB",
    "team": "SEA",
    "age": 23.6,
    "value": 2210,
    "rank": 247,
    "positionalRank": 37,
    "tier": 17,
    "trend": 1,
    "rookie": false
  },
  {
    "name": "Jaylen Wright",
    "position": "RB",
    "team": "MIA",
    "age": 23.3,
    "value": 2209,
    "rank": 248,
    "positionalRank": 63,
    "tier": 17,
    "trend": 1,
    "rookie": false
  },
  {
    "name": "Anthony Richardson",
    "position": "QB",
    "team": "IND",
    "age": 24.1,
    "value": 2183,
    "rank": 249,
    "positionalRank": 38,
    "tier": 17,
    "trend": -10,
    "rookie": false
  },
  {
    "name": "Theo Johnson",
    "position": "TE",
    "team": "NYG",
    "age": 25.4,
    "value": 2174,
    "rank": 250,
    "positionalRank": 35,
    "tier": 17,
    "trend": -4,
    "rookie": false
  },
  {
    "name": "Kimani Vidal",
    "position": "RB",
    "team": "LAC",
    "age": 24.8,
    "value": 2161,
    "rank": 251,
    "positionalRank": 64,
    "tier": 17,
    "trend": -1,
    "rookie": false
  },
  {
    "name": "2026 Mid 3rd",
    "position": "RDP",
    "team": "FA",
    "age": 0.0,
    "value": 2160,
    "rank": 252,
    "positionalRank": null,
    "tier": 17,
    "trend": 1,
    "rookie": false
  },
  {
    "name": "Dalton Schultz",
    "position": "TE",
    "team": "HOU",
    "age": 30.0,
    "value": 2156,
    "rank": 253,
    "positionalRank": 36,
    "tier": 17,
    "trend": -9,
    "rookie": false
  },
  {
    "name": "MarShawn Lloyd",
    "position": "RB",
    "team": "GBP",
    "age": 25.5,
    "value": 2153,
    "rank": 254,
    "positionalRank": 65,
    "tier": 17,
    "trend": 10,
    "rookie": false
  },
  {
    "name": "Stefon Diggs",
    "position": "WR",
    "team": "FA",
    "age": 32.6,
    "value": 2140,
    "rank": 255,
    "positionalRank": 92,
    "tier": 17,
    "trend": 0,
    "rookie": false
  },
  {
    "name": "Brandon Aiyuk",
    "position": "WR",
    "team": "SFO",
    "age": 28.3,
    "value": 2138,
    "rank": 256,
    "positionalRank": 93,
    "tier": 17,
    "trend": -15,
    "rookie": false
  },
  {
    "name": "Deshaun Watson",
    "position": "QB",
    "team": "CLE",
    "age": 30.8,
    "value": 2129,
    "rank": 257,
    "positionalRank": 39,
    "tier": 17,
    "trend": -6,
    "rookie": false
  },
  {
    "name": "Jordan James",
    "position": "RB",
    "team": "SFO",
    "age": 22.3,
    "value": 2127,
    "rank": 258,
    "positionalRank": 66,
    "tier": 17,
    "trend": 0,
    "rookie": false
  },
  {
    "name": "2026 Late 3rd",
    "position": "RDP",
    "team": "FA",
    "age": 0.0,
    "value": 2121,
    "rank": 259,
    "positionalRank": null,
    "tier": 17,
    "trend": 12,
    "rookie": false
  },
  {
    "name": "Marvin Mims",
    "position": "WR",
    "team": "DEN",
    "age": 24.3,
    "value": 2105,
    "rank": 260,
    "positionalRank": 94,
    "tier": 17,
    "trend": -3,
    "rookie": false
  },
  {
    "name": "Jaydon Blue",
    "position": "RB",
    "team": "DAL",
    "age": 22.5,
    "value": 2090,
    "rank": 261,
    "positionalRank": 67,
    "tier": 17,
    "trend": 4,
    "rookie": false
  },
  {
    "name": "2028 Mid 3rd",
    "position": "RDP",
    "team": "FA",
    "age": 0.0,
    "value": 2087,
    "rank": 262,
    "positionalRank": null,
    "tier": 17,
    "trend": -3,
    "rookie": false
  },
  {
    "name": "Tez Johnson",
    "position": "WR",
    "team": "TBB",
    "age": 24.1,
    "value": 2078,
    "rank": 263,
    "positionalRank": 95,
    "tier": 17,
    "trend": -7,
    "rookie": false
  },
  {
    "name": "Rashod Bateman",
    "position": "WR",
    "team": "BAL",
    "age": 26.6,
    "value": 2077,
    "rank": 264,
    "positionalRank": 96,
    "tier": 17,
    "trend": -4,
    "rookie": false
  },
  {
    "name": "DJ Giddens",
    "position": "RB",
    "team": "IND",
    "age": 22.9,
    "value": 2076,
    "rank": 265,
    "positionalRank": 68,
    "tier": 17,
    "trend": 8,
    "rookie": false
  },
  {
    "name": "LeQuint Allen",
    "position": "RB",
    "team": "JAC",
    "age": 21.9,
    "value": 2064,
    "rank": 266,
    "positionalRank": 69,
    "tier": 17,
    "trend": 6,
    "rookie": false
  },
  {
    "name": "Greg Dulcich",
    "position": "TE",
    "team": "MIA",
    "age": 26.3,
    "value": 2055,
    "rank": 267,
    "positionalRank": 37,
    "tier": 17,
    "trend": 25,
    "rookie": false
  },
  {
    "name": "Justin Fields",
    "position": "QB",
    "team": "KCC",
    "age": 27.3,
    "value": 2044,
    "rank": 268,
    "positionalRank": 40,
    "tier": 17,
    "trend": 2,
    "rookie": false
  },
  {
    "name": "Alvin Kamara",
    "position": "RB",
    "team": "NOS",
    "age": 31.0,
    "value": 2033,
    "rank": 269,
    "positionalRank": 70,
    "tier": 17,
    "trend": -2,
    "rookie": false
  },
  {
    "name": "Trevor Etienne",
    "position": "RB",
    "team": "CAR",
    "age": 22.0,
    "value": 2028,
    "rank": 270,
    "positionalRank": 71,
    "tier": 17,
    "trend": -7,
    "rookie": false
  },
  {
    "name": "Darnell Mooney",
    "position": "WR",
    "team": "NYG",
    "age": 28.7,
    "value": 2025,
    "rank": 271,
    "positionalRank": 97,
    "tier": 17,
    "trend": -10,
    "rookie": false
  },
  {
    "name": "Ja'Tavion Sanders",
    "position": "TE",
    "team": "CAR",
    "age": 23.3,
    "value": 2020,
    "rank": 272,
    "positionalRank": 38,
    "tier": 17,
    "trend": -6,
    "rookie": false
  },
  {
    "name": "Emanuel Wilson",
    "position": "RB",
    "team": "SEA",
    "age": 27.2,
    "value": 2017,
    "rank": 273,
    "positionalRank": 72,
    "tier": 17,
    "trend": -11,
    "rookie": false
  },
  {
    "name": "Jaylin Lane",
    "position": "WR",
    "team": "WAS",
    "age": 24.2,
    "value": 2017,
    "rank": 274,
    "positionalRank": 98,
    "tier": 17,
    "trend": 8,
    "rookie": false
  },
  {
    "name": "2028 Late 3rd",
    "position": "RDP",
    "team": "FA",
    "age": 0.0,
    "value": 2017,
    "rank": 275,
    "positionalRank": null,
    "tier": 17,
    "trend": 2,
    "rookie": false
  },
  {
    "name": "Isaiah Bond",
    "position": "WR",
    "team": "CLE",
    "age": 22.3,
    "value": 2009,
    "rank": 276,
    "positionalRank": 99,
    "tier": 17,
    "trend": 0,
    "rookie": false
  },
  {
    "name": "Devin Neal",
    "position": "RB",
    "team": "NOS",
    "age": 22.9,
    "value": 1989,
    "rank": 277,
    "positionalRank": 73,
    "tier": 17,
    "trend": -8,
    "rookie": false
  },
  {
    "name": "Demond Claiborne",
    "position": "RB",
    "team": "MIN",
    "age": -1.0,
    "value": 1976,
    "rank": 278,
    "positionalRank": 74,
    "tier": 17,
    "trend": 16,
    "rookie": true
  },
  {
    "name": "Ray Davis",
    "position": "RB",
    "team": "BUF",
    "age": 26.6,
    "value": 1975,
    "rank": 279,
    "positionalRank": 75,
    "tier": 17,
    "trend": 4,
    "rookie": false
  },
  {
    "name": "Aaron Rodgers",
    "position": "QB",
    "team": "PIT",
    "age": 42.6,
    "value": 1964,
    "rank": 280,
    "positionalRank": 41,
    "tier": 17,
    "trend": 8,
    "rookie": false
  },
  {
    "name": "Christian Kirk",
    "position": "WR",
    "team": "SFO",
    "age": 29.6,
    "value": 1955,
    "rank": 281,
    "positionalRank": 100,
    "tier": 17,
    "trend": -1,
    "rookie": false
  },
  {
    "name": "Cole Kmet",
    "position": "TE",
    "team": "CHI",
    "age": 27.3,
    "value": 1952,
    "rank": 282,
    "positionalRank": 39,
    "tier": 17,
    "trend": -3,
    "rookie": false
  },
  {
    "name": "Deebo Samuel",
    "position": "WR",
    "team": "FA",
    "age": 30.5,
    "value": 1945,
    "rank": 283,
    "positionalRank": 101,
    "tier": 17,
    "trend": -15,
    "rookie": false
  },
  {
    "name": "Demario Douglas",
    "position": "WR",
    "team": "NEP",
    "age": 25.6,
    "value": 1939,
    "rank": 284,
    "positionalRank": 102,
    "tier": 17,
    "trend": -10,
    "rookie": false
  },
  {
    "name": "Kevin Coleman",
    "position": "WR",
    "team": "MIA",
    "age": 22.8,
    "value": 1933,
    "rank": 285,
    "positionalRank": 103,
    "tier": 17,
    "trend": 24,
    "rookie": true
  },
  {
    "name": "Dont'e Thornton",
    "position": "WR",
    "team": "LVR",
    "age": 23.6,
    "value": 1930,
    "rank": 286,
    "positionalRank": 104,
    "tier": 17,
    "trend": -8,
    "rookie": false
  },
  {
    "name": "Will Howard",
    "position": "QB",
    "team": "PIT",
    "age": 24.8,
    "value": 1919,
    "rank": 287,
    "positionalRank": 42,
    "tier": 17,
    "trend": -12,
    "rookie": false
  },
  {
    "name": "Darnell Washington",
    "position": "TE",
    "team": "PIT",
    "age": 24.9,
    "value": 1912,
    "rank": 288,
    "positionalRank": 40,
    "tier": 17,
    "trend": 9,
    "rookie": false
  },
  {
    "name": "Drew Allar",
    "position": "QB",
    "team": "PIT",
    "age": -1.0,
    "value": 1902,
    "rank": 289,
    "positionalRank": 43,
    "tier": 17,
    "trend": 31,
    "rookie": true
  },
  {
    "name": "Kirk Cousins",
    "position": "QB",
    "team": "LVR",
    "age": 37.9,
    "value": 1886,
    "rank": 290,
    "positionalRank": 44,
    "tier": 17,
    "trend": -6,
    "rookie": false
  },
  {
    "name": "2027 Early 4th",
    "position": "RDP",
    "team": "FA",
    "age": 0.0,
    "value": 1885,
    "rank": 291,
    "positionalRank": null,
    "tier": 17,
    "trend": -5,
    "rookie": false
  },
  {
    "name": "Xavier Legette",
    "position": "WR",
    "team": "CAR",
    "age": 25.4,
    "value": 1884,
    "rank": 292,
    "positionalRank": 105,
    "tier": 17,
    "trend": -5,
    "rookie": false
  },
  {
    "name": "Colby Parkinson",
    "position": "TE",
    "team": "LAR",
    "age": 27.5,
    "value": 1877,
    "rank": 293,
    "positionalRank": 41,
    "tier": 17,
    "trend": -2,
    "rookie": false
  },
  {
    "name": "Ryan Flournoy",
    "position": "WR",
    "team": "DAL",
    "age": 26.7,
    "value": 1870,
    "rank": 294,
    "positionalRank": 106,
    "tier": 17,
    "trend": 12,
    "rookie": false
  },
  {
    "name": "Cade Klubnik",
    "position": "QB",
    "team": "NYJ",
    "age": -1.0,
    "value": 1858,
    "rank": 295,
    "positionalRank": 45,
    "tier": 17,
    "trend": 7,
    "rookie": true
  },
  {
    "name": "Tyreek Hill",
    "position": "WR",
    "team": "FA",
    "age": 32.4,
    "value": 1853,
    "rank": 296,
    "positionalRank": 107,
    "tier": 17,
    "trend": -15,
    "rookie": false
  },
  {
    "name": "Calvin Ridley",
    "position": "WR",
    "team": "TEN",
    "age": 31.5,
    "value": 1844,
    "rank": 297,
    "positionalRank": 108,
    "tier": 17,
    "trend": -8,
    "rookie": false
  },
  {
    "name": "Kaelon Black",
    "position": "RB",
    "team": "SFO",
    "age": -1.0,
    "value": 1833,
    "rank": 298,
    "positionalRank": 76,
    "tier": 17,
    "trend": 30,
    "rookie": true
  },
  {
    "name": "Jalen Royals",
    "position": "WR",
    "team": "KCC",
    "age": 23.4,
    "value": 1800,
    "rank": 299,
    "positionalRank": 109,
    "tier": 17,
    "trend": -9,
    "rookie": false
  },
  {
    "name": "Isaiah Davis",
    "position": "RB",
    "team": "NYJ",
    "age": 24.4,
    "value": 1797,
    "rank": 300,
    "positionalRank": 77,
    "tier": 17,
    "trend": 1,
    "rookie": false
  }
]
