// KeepTradeCut dynasty superflex rankings (top 300), captured 2026-09-01
// Source: https://keeptradecut.com/dynasty-rankings
export const PLAYER_VALUES = [
  {
    "name": "Bijan Robinson",
    "position": "RB",
    "team": "ATL",
    "age": 24.6,
    "value": 9999,
    "rank": 1,
    "positionalRank": 1,
    "tier": 1,
    "trend": 1,
    "rookie": false
  },
  {
    "name": "Jahmyr Gibbs",
    "position": "RB",
    "team": "DET",
    "age": 24.4,
    "value": 9999,
    "rank": 2,
    "positionalRank": 2,
    "tier": 1,
    "trend": 0,
    "rookie": false
  },
  {
    "name": "Ja'Marr Chase",
    "position": "WR",
    "team": "CIN",
    "age": 26.5,
    "value": 9991,
    "rank": 3,
    "positionalRank": 1,
    "tier": 1,
    "trend": 1,
    "rookie": false
  },
  {
    "name": "Josh Allen",
    "position": "QB",
    "team": "BUF",
    "age": 30.3,
    "value": 9976,
    "rank": 4,
    "positionalRank": 1,
    "tier": 1,
    "trend": -3,
    "rookie": false
  },
  {
    "name": "Jaxon Smith-Njigba",
    "position": "WR",
    "team": "SEA",
    "age": 24.5,
    "value": 9191,
    "rank": 5,
    "positionalRank": 2,
    "tier": 2,
    "trend": 0,
    "rookie": false
  },
  {
    "name": "Drake Maye",
    "position": "QB",
    "team": "NEP",
    "age": 24.0,
    "value": 8891,
    "rank": 6,
    "positionalRank": 2,
    "tier": 2,
    "trend": 0,
    "rookie": false
  },
  {
    "name": "Puka Nacua",
    "position": "WR",
    "team": "LAR",
    "age": 25.3,
    "value": 8521,
    "rank": 7,
    "positionalRank": 3,
    "tier": 2,
    "trend": 0,
    "rookie": false
  },
  {
    "name": "Brock Bowers",
    "position": "TE",
    "team": "LVR",
    "age": 23.7,
    "value": 8278,
    "rank": 8,
    "positionalRank": 1,
    "tier": 2,
    "trend": 0,
    "rookie": false
  },
  {
    "name": "Amon-Ra St. Brown",
    "position": "WR",
    "team": "DET",
    "age": 26.8,
    "value": 8177,
    "rank": 9,
    "positionalRank": 4,
    "tier": 2,
    "trend": 1,
    "rookie": false
  },
  {
    "name": "Caleb Williams",
    "position": "QB",
    "team": "CHI",
    "age": 24.8,
    "value": 7768,
    "rank": 10,
    "positionalRank": 3,
    "tier": 3,
    "trend": -1,
    "rookie": false
  },
  {
    "name": "Lamar Jackson",
    "position": "QB",
    "team": "BAL",
    "age": 29.6,
    "value": 7538,
    "rank": 11,
    "positionalRank": 4,
    "tier": 3,
    "trend": 0,
    "rookie": false
  },
  {
    "name": "Justin Jefferson",
    "position": "WR",
    "team": "MIN",
    "age": 27.2,
    "value": 7373,
    "rank": 12,
    "positionalRank": 5,
    "tier": 3,
    "trend": 1,
    "rookie": false
  },
  {
    "name": "Malik Nabers",
    "position": "WR",
    "team": "NYG",
    "age": 23.1,
    "value": 7340,
    "rank": 13,
    "positionalRank": 6,
    "tier": 3,
    "trend": 5,
    "rookie": false
  },
  {
    "name": "Joe Burrow",
    "position": "QB",
    "team": "CIN",
    "age": 29.7,
    "value": 7326,
    "rank": 14,
    "positionalRank": 5,
    "tier": 3,
    "trend": 2,
    "rookie": false
  },
  {
    "name": "Jeremiyah Love",
    "position": "RB",
    "team": "ARI",
    "age": 21.2,
    "value": 7323,
    "rank": 15,
    "positionalRank": 3,
    "tier": 3,
    "trend": 0,
    "rookie": true
  },
  {
    "name": "Trey McBride",
    "position": "TE",
    "team": "ARI",
    "age": 26.8,
    "value": 7295,
    "rank": 16,
    "positionalRank": 2,
    "tier": 3,
    "trend": 1,
    "rookie": false
  },
  {
    "name": "Ashton Jeanty",
    "position": "RB",
    "team": "LVR",
    "age": 22.8,
    "value": 7275,
    "rank": 17,
    "positionalRank": 4,
    "tier": 3,
    "trend": -5,
    "rookie": false
  },
  {
    "name": "Jayden Daniels",
    "position": "QB",
    "team": "WAS",
    "age": 25.7,
    "value": 7225,
    "rank": 18,
    "positionalRank": 6,
    "tier": 3,
    "trend": -4,
    "rookie": false
  },
  {
    "name": "CeeDee Lamb",
    "position": "WR",
    "team": "DAL",
    "age": 27.4,
    "value": 7176,
    "rank": 19,
    "positionalRank": 7,
    "tier": 3,
    "trend": 0,
    "rookie": false
  },
  {
    "name": "De'Von Achane",
    "position": "RB",
    "team": "MIA",
    "age": 24.9,
    "value": 6960,
    "rank": 20,
    "positionalRank": 5,
    "tier": 4,
    "trend": 3,
    "rookie": false
  },
  {
    "name": "Justin Herbert",
    "position": "QB",
    "team": "LAC",
    "age": 28.5,
    "value": 6956,
    "rank": 21,
    "positionalRank": 7,
    "tier": 4,
    "trend": -1,
    "rookie": false
  },
  {
    "name": "Omarion Hampton",
    "position": "RB",
    "team": "LAC",
    "age": 23.5,
    "value": 6926,
    "rank": 22,
    "positionalRank": 6,
    "tier": 4,
    "trend": -1,
    "rookie": false
  },
  {
    "name": "Drake London",
    "position": "WR",
    "team": "ATL",
    "age": 25.1,
    "value": 6795,
    "rank": 23,
    "positionalRank": 8,
    "tier": 4,
    "trend": -1,
    "rookie": false
  },
  {
    "name": "James Cook",
    "position": "RB",
    "team": "BUF",
    "age": 26.9,
    "value": 6561,
    "rank": 24,
    "positionalRank": 7,
    "tier": 5,
    "trend": 8,
    "rookie": false
  },
  {
    "name": "Jonathan Taylor",
    "position": "RB",
    "team": "IND",
    "age": 27.6,
    "value": 6398,
    "rank": 25,
    "positionalRank": 8,
    "tier": 6,
    "trend": 6,
    "rookie": false
  },
  {
    "name": "Trevor Lawrence",
    "position": "QB",
    "team": "JAC",
    "age": 26.9,
    "value": 6322,
    "rank": 26,
    "positionalRank": 8,
    "tier": 6,
    "trend": 2,
    "rookie": false
  },
  {
    "name": "Colston Loveland",
    "position": "TE",
    "team": "CHI",
    "age": 22.4,
    "value": 6304,
    "rank": 27,
    "positionalRank": 3,
    "tier": 6,
    "trend": 0,
    "rookie": false
  },
  {
    "name": "George Pickens",
    "position": "WR",
    "team": "DAL",
    "age": 25.5,
    "value": 6265,
    "rank": 28,
    "positionalRank": 9,
    "tier": 6,
    "trend": 5,
    "rookie": false
  },
  {
    "name": "Tetairoa McMillan",
    "position": "WR",
    "team": "CAR",
    "age": 23.4,
    "value": 6236,
    "rank": 29,
    "positionalRank": 10,
    "tier": 6,
    "trend": -5,
    "rookie": false
  },
  {
    "name": "Emeka Egbuka",
    "position": "WR",
    "team": "TBB",
    "age": 23.9,
    "value": 6189,
    "rank": 30,
    "positionalRank": 11,
    "tier": 6,
    "trend": -4,
    "rookie": false
  },
  {
    "name": "Bo Nix",
    "position": "QB",
    "team": "DEN",
    "age": 26.5,
    "value": 6060,
    "rank": 31,
    "positionalRank": 9,
    "tier": 7,
    "trend": 3,
    "rookie": false
  },
  {
    "name": "Jalen Hurts",
    "position": "QB",
    "team": "PHI",
    "age": 28.1,
    "value": 6021,
    "rank": 32,
    "positionalRank": 10,
    "tier": 7,
    "trend": -2,
    "rookie": false
  },
  {
    "name": "Tyler Warren",
    "position": "TE",
    "team": "IND",
    "age": 24.3,
    "value": 5963,
    "rank": 33,
    "positionalRank": 4,
    "tier": 7,
    "trend": 3,
    "rookie": false
  },
  {
    "name": "Patrick Mahomes",
    "position": "QB",
    "team": "KCC",
    "age": 31.0,
    "value": 5933,
    "rank": 34,
    "positionalRank": 11,
    "tier": 7,
    "trend": -9,
    "rookie": false
  },
  {
    "name": "Jaxson Dart",
    "position": "QB",
    "team": "NYG",
    "age": 23.3,
    "value": 5825,
    "rank": 35,
    "positionalRank": 12,
    "tier": 8,
    "trend": -6,
    "rookie": false
  },
  {
    "name": "Ladd McConkey",
    "position": "WR",
    "team": "LAC",
    "age": 24.8,
    "value": 5786,
    "rank": 36,
    "positionalRank": 12,
    "tier": 8,
    "trend": 4,
    "rookie": false
  },
  {
    "name": "Kenneth Walker III",
    "position": "RB",
    "team": "KCC",
    "age": 25.9,
    "value": 5783,
    "rank": 37,
    "positionalRank": 9,
    "tier": 8,
    "trend": 2,
    "rookie": false
  },
  {
    "name": "Nico Collins",
    "position": "WR",
    "team": "HOU",
    "age": 27.4,
    "value": 5757,
    "rank": 38,
    "positionalRank": 13,
    "tier": 8,
    "trend": 6,
    "rookie": false
  },
  {
    "name": "Chris Olave",
    "position": "WR",
    "team": "NOS",
    "age": 26.2,
    "value": 5756,
    "rank": 39,
    "positionalRank": 14,
    "tier": 8,
    "trend": 3,
    "rookie": false
  },
  {
    "name": "Chase Brown",
    "position": "RB",
    "team": "CIN",
    "age": 26.4,
    "value": 5738,
    "rank": 40,
    "positionalRank": 10,
    "tier": 8,
    "trend": 10,
    "rookie": false
  },
  {
    "name": "Brock Purdy",
    "position": "QB",
    "team": "SFO",
    "age": 26.7,
    "value": 5638,
    "rank": 41,
    "positionalRank": 13,
    "tier": 9,
    "trend": -4,
    "rookie": false
  },
  {
    "name": "Garrett Wilson",
    "position": "WR",
    "team": "NYJ",
    "age": 26.1,
    "value": 5613,
    "rank": 42,
    "positionalRank": 15,
    "tier": 9,
    "trend": 3,
    "rookie": false
  },
  {
    "name": "DeVonta Smith",
    "position": "WR",
    "team": "PHI",
    "age": 27.8,
    "value": 5560,
    "rank": 43,
    "positionalRank": 16,
    "tier": 9,
    "trend": 4,
    "rookie": false
  },
  {
    "name": "Carnell Tate",
    "position": "WR",
    "team": "TEN",
    "age": 21.6,
    "value": 5549,
    "rank": 44,
    "positionalRank": 17,
    "tier": 9,
    "trend": -10,
    "rookie": true
  },
  {
    "name": "Luther Burden",
    "position": "WR",
    "team": "CHI",
    "age": 22.7,
    "value": 5506,
    "rank": 45,
    "positionalRank": 18,
    "tier": 9,
    "trend": -1,
    "rookie": false
  },
  {
    "name": "A.J. Brown",
    "position": "WR",
    "team": "NEP",
    "age": 29.2,
    "value": 5348,
    "rank": 46,
    "positionalRank": 19,
    "tier": 10,
    "trend": 13,
    "rookie": false
  },
  {
    "name": "Christian McCaffrey",
    "position": "RB",
    "team": "SFO",
    "age": 30.2,
    "value": 5339,
    "rank": 47,
    "positionalRank": 11,
    "tier": 10,
    "trend": 4,
    "rookie": false
  },
  {
    "name": "Zay Flowers",
    "position": "WR",
    "team": "BAL",
    "age": 26.0,
    "value": 5330,
    "rank": 48,
    "positionalRank": 20,
    "tier": 10,
    "trend": 10,
    "rookie": false
  },
  {
    "name": "Saquon Barkley",
    "position": "RB",
    "team": "PHI",
    "age": 29.6,
    "value": 5313,
    "rank": 49,
    "positionalRank": 12,
    "tier": 10,
    "trend": 7,
    "rookie": false
  },
  {
    "name": "Breece Hall",
    "position": "RB",
    "team": "NYJ",
    "age": 25.2,
    "value": 5302,
    "rank": 50,
    "positionalRank": 13,
    "tier": 10,
    "trend": 1,
    "rookie": false
  },
  {
    "name": "Jordan Love",
    "position": "QB",
    "team": "GBP",
    "age": 27.8,
    "value": 5264,
    "rank": 51,
    "positionalRank": 14,
    "tier": 10,
    "trend": -6,
    "rookie": false
  },
  {
    "name": "Quinshon Judkins",
    "position": "RB",
    "team": "CLE",
    "age": 22.8,
    "value": 5261,
    "rank": 52,
    "positionalRank": 14,
    "tier": 10,
    "trend": -11,
    "rookie": false
  },
  {
    "name": "Fernando Mendoza",
    "position": "QB",
    "team": "LVR",
    "age": 22.9,
    "value": 5246,
    "rank": 53,
    "positionalRank": 15,
    "tier": 10,
    "trend": -7,
    "rookie": true
  },
  {
    "name": "Rome Odunze",
    "position": "WR",
    "team": "CHI",
    "age": 24.2,
    "value": 5235,
    "rank": 54,
    "positionalRank": 21,
    "tier": 10,
    "trend": -2,
    "rookie": false
  },
  {
    "name": "Jaylen Waddle",
    "position": "WR",
    "team": "DEN",
    "age": 27.8,
    "value": 5218,
    "rank": 55,
    "positionalRank": 22,
    "tier": 10,
    "trend": 8,
    "rookie": false
  },
  {
    "name": "Jadarian Price",
    "position": "RB",
    "team": "SEA",
    "age": 22.9,
    "value": 5130,
    "rank": 56,
    "positionalRank": 15,
    "tier": 11,
    "trend": 11,
    "rookie": true
  },
  {
    "name": "Tee Higgins",
    "position": "WR",
    "team": "CIN",
    "age": 27.6,
    "value": 5117,
    "rank": 57,
    "positionalRank": 23,
    "tier": 11,
    "trend": 3,
    "rookie": false
  },
  {
    "name": "Dak Prescott",
    "position": "QB",
    "team": "DAL",
    "age": 33.1,
    "value": 5070,
    "rank": 58,
    "positionalRank": 16,
    "tier": 11,
    "trend": 5,
    "rookie": false
  },
  {
    "name": "Tucker Kraft",
    "position": "TE",
    "team": "GBP",
    "age": 25.8,
    "value": 5015,
    "rank": 59,
    "positionalRank": 5,
    "tier": 11,
    "trend": 3,
    "rookie": false
  },
  {
    "name": "Kyren Williams",
    "position": "RB",
    "team": "LAR",
    "age": 26.0,
    "value": 4952,
    "rank": 60,
    "positionalRank": 16,
    "tier": 11,
    "trend": -1,
    "rookie": false
  },
  {
    "name": "Jordyn Tyson",
    "position": "WR",
    "team": "NOS",
    "age": 22.0,
    "value": 4948,
    "rank": 61,
    "positionalRank": 24,
    "tier": 11,
    "trend": -12,
    "rookie": true
  },
  {
    "name": "TreVeyon Henderson",
    "position": "RB",
    "team": "NEP",
    "age": 23.9,
    "value": 4890,
    "rank": 62,
    "positionalRank": 17,
    "tier": 11,
    "trend": -15,
    "rookie": false
  },
  {
    "name": "Javonte Williams",
    "position": "RB",
    "team": "DAL",
    "age": 26.4,
    "value": 4837,
    "rank": 63,
    "positionalRank": 18,
    "tier": 11,
    "trend": 15,
    "rookie": false
  },
  {
    "name": "Rashee Rice",
    "position": "WR",
    "team": "KCC",
    "age": 26.4,
    "value": 4825,
    "rank": 64,
    "positionalRank": 25,
    "tier": 11,
    "trend": -4,
    "rookie": false
  },
  {
    "name": "Jameson Williams",
    "position": "WR",
    "team": "DET",
    "age": 25.4,
    "value": 4810,
    "rank": 65,
    "positionalRank": 26,
    "tier": 11,
    "trend": 6,
    "rookie": false
  },
  {
    "name": "Tyler Shough",
    "position": "QB",
    "team": "NOS",
    "age": 26.9,
    "value": 4796,
    "rank": 66,
    "positionalRank": 17,
    "tier": 11,
    "trend": 1,
    "rookie": false
  },
  {
    "name": "Marvin Harrison Jr.",
    "position": "WR",
    "team": "ARI",
    "age": 24.0,
    "value": 4750,
    "rank": 67,
    "positionalRank": 27,
    "tier": 11,
    "trend": 2,
    "rookie": false
  },
  {
    "name": "Makai Lemon",
    "position": "WR",
    "team": "PHI",
    "age": 22.2,
    "value": 4710,
    "rank": 68,
    "positionalRank": 28,
    "tier": 11,
    "trend": -13,
    "rookie": true
  },
  {
    "name": "Harold Fannin",
    "position": "TE",
    "team": "CLE",
    "age": 22.1,
    "value": 4674,
    "rank": 69,
    "positionalRank": 6,
    "tier": 11,
    "trend": -2,
    "rookie": false
  },
  {
    "name": "Cam Skattebo",
    "position": "RB",
    "team": "NYG",
    "age": 24.6,
    "value": 4644,
    "rank": 70,
    "positionalRank": 19,
    "tier": 11,
    "trend": -1,
    "rookie": false
  },
  {
    "name": "KC Concepcion",
    "position": "WR",
    "team": "CLE",
    "age": 21.9,
    "value": 4642,
    "rank": 71,
    "positionalRank": 29,
    "tier": 11,
    "trend": 11,
    "rookie": true
  },
  {
    "name": "Bucky Irving",
    "position": "RB",
    "team": "TBB",
    "age": 24.0,
    "value": 4641,
    "rank": 72,
    "positionalRank": 20,
    "tier": 11,
    "trend": -1,
    "rookie": false
  },
  {
    "name": "Parker Washington",
    "position": "WR",
    "team": "JAC",
    "age": 24.4,
    "value": 4608,
    "rank": 73,
    "positionalRank": 30,
    "tier": 11,
    "trend": 23,
    "rookie": false
  },
  {
    "name": "Brian Thomas Jr.",
    "position": "WR",
    "team": "JAC",
    "age": 23.9,
    "value": 4576,
    "rank": 74,
    "positionalRank": 31,
    "tier": 11,
    "trend": -10,
    "rookie": false
  },
  {
    "name": "Cam Ward",
    "position": "QB",
    "team": "TEN",
    "age": 24.3,
    "value": 4575,
    "rank": 75,
    "positionalRank": 18,
    "tier": 11,
    "trend": -24,
    "rookie": false
  },
  {
    "name": "Baker Mayfield",
    "position": "QB",
    "team": "TBB",
    "age": 31.4,
    "value": 4574,
    "rank": 76,
    "positionalRank": 19,
    "tier": 11,
    "trend": -3,
    "rookie": false
  },
  {
    "name": "Sam LaPorta",
    "position": "TE",
    "team": "DET",
    "age": 25.6,
    "value": 4562,
    "rank": 77,
    "positionalRank": 7,
    "tier": 11,
    "trend": -2,
    "rookie": false
  },
  {
    "name": "Jared Goff",
    "position": "QB",
    "team": "DET",
    "age": 31.9,
    "value": 4549,
    "rank": 78,
    "positionalRank": 20,
    "tier": 11,
    "trend": -7,
    "rookie": false
  },
  {
    "name": "C.J. Stroud",
    "position": "QB",
    "team": "HOU",
    "age": 24.9,
    "value": 4466,
    "rank": 79,
    "positionalRank": 21,
    "tier": 12,
    "trend": -6,
    "rookie": false
  },
  {
    "name": "Travis Etienne",
    "position": "RB",
    "team": "NOS",
    "age": 27.6,
    "value": 4448,
    "rank": 80,
    "positionalRank": 21,
    "tier": 12,
    "trend": 0,
    "rookie": false
  },
  {
    "name": "Bhayshul Tuten",
    "position": "RB",
    "team": "JAC",
    "age": 23.5,
    "value": 4384,
    "rank": 81,
    "positionalRank": 22,
    "tier": 12,
    "trend": 1,
    "rookie": false
  },
  {
    "name": "Kyle Pitts",
    "position": "TE",
    "team": "ATL",
    "age": 25.9,
    "value": 4327,
    "rank": 82,
    "positionalRank": 8,
    "tier": 12,
    "trend": -4,
    "rookie": false
  },
  {
    "name": "Sam Darnold",
    "position": "QB",
    "team": "SEA",
    "age": 29.2,
    "value": 4299,
    "rank": 83,
    "positionalRank": 22,
    "tier": 12,
    "trend": -4,
    "rookie": false
  },
  {
    "name": "Derrick Henry",
    "position": "RB",
    "team": "BAL",
    "age": 32.6,
    "value": 4249,
    "rank": 84,
    "positionalRank": 23,
    "tier": 12,
    "trend": -1,
    "rookie": false
  },
  {
    "name": "D'Andre Swift",
    "position": "RB",
    "team": "CHI",
    "age": 27.6,
    "value": 4064,
    "rank": 85,
    "positionalRank": 24,
    "tier": 13,
    "trend": 12,
    "rookie": false
  },
  {
    "name": "Christian Watson",
    "position": "WR",
    "team": "GBP",
    "age": 27.3,
    "value": 4021,
    "rank": 86,
    "positionalRank": 32,
    "tier": 13,
    "trend": 4,
    "rookie": false
  },
  {
    "name": "De'Zhaun Stribling",
    "position": "WR",
    "team": "SFO",
    "age": 23.7,
    "value": 3925,
    "rank": 87,
    "positionalRank": 33,
    "tier": 14,
    "trend": 46,
    "rookie": true
  },
  {
    "name": "Kyler Murray",
    "position": "QB",
    "team": "MIN",
    "age": 29.1,
    "value": 3854,
    "rank": 88,
    "positionalRank": 23,
    "tier": 15,
    "trend": -1,
    "rookie": false
  },
  {
    "name": "D.J. Moore",
    "position": "WR",
    "team": "BUF",
    "age": 29.4,
    "value": 3853,
    "rank": 89,
    "positionalRank": 34,
    "tier": 15,
    "trend": 9,
    "rookie": false
  },
  {
    "name": "Jonathon Brooks",
    "position": "RB",
    "team": "CAR",
    "age": 23.1,
    "value": 3787,
    "rank": 90,
    "positionalRank": 25,
    "tier": 16,
    "trend": 11,
    "rookie": false
  },
  {
    "name": "Matthew Stafford",
    "position": "QB",
    "team": "LAR",
    "age": 38.6,
    "value": 3775,
    "rank": 91,
    "positionalRank": 24,
    "tier": 16,
    "trend": 0,
    "rookie": false
  },
  {
    "name": "Jordan Addison",
    "position": "WR",
    "team": "MIN",
    "age": 24.6,
    "value": 3766,
    "rank": 92,
    "positionalRank": 35,
    "tier": 16,
    "trend": -2,
    "rookie": false
  },
  {
    "name": "Matthew Golden",
    "position": "WR",
    "team": "GBP",
    "age": 23.1,
    "value": 3748,
    "rank": 93,
    "positionalRank": 36,
    "tier": 16,
    "trend": 5,
    "rookie": false
  },
  {
    "name": "Malik Willis",
    "position": "QB",
    "team": "MIA",
    "age": 27.3,
    "value": 3727,
    "rank": 94,
    "positionalRank": 25,
    "tier": 16,
    "trend": 2,
    "rookie": false
  },
  {
    "name": "Alec Pierce",
    "position": "WR",
    "team": "IND",
    "age": 26.3,
    "value": 3726,
    "rank": 95,
    "positionalRank": 37,
    "tier": 16,
    "trend": -6,
    "rookie": false
  },
  {
    "name": "Michael Wilson",
    "position": "WR",
    "team": "ARI",
    "age": 26.5,
    "value": 3719,
    "rank": 96,
    "positionalRank": 38,
    "tier": 16,
    "trend": -2,
    "rookie": false
  },
  {
    "name": "Bryce Young",
    "position": "QB",
    "team": "CAR",
    "age": 25.1,
    "value": 3714,
    "rank": 97,
    "positionalRank": 26,
    "tier": 16,
    "trend": -14,
    "rookie": false
  },
  {
    "name": "Daniel Jones",
    "position": "QB",
    "team": "IND",
    "age": 29.3,
    "value": 3707,
    "rank": 98,
    "positionalRank": 27,
    "tier": 16,
    "trend": -11,
    "rookie": false
  },
  {
    "name": "Ty Simpson",
    "position": "QB",
    "team": "LAR",
    "age": 23.7,
    "value": 3663,
    "rank": 99,
    "positionalRank": 28,
    "tier": 16,
    "trend": 11,
    "rookie": true
  },
  {
    "name": "Kenyon Sadiq",
    "position": "TE",
    "team": "NYJ",
    "age": 21.5,
    "value": 3646,
    "rank": 100,
    "positionalRank": 9,
    "tier": 16,
    "trend": -16,
    "rookie": true
  },
  {
    "name": "Denzel Boston",
    "position": "WR",
    "team": "CLE",
    "age": 22.7,
    "value": 3630,
    "rank": 101,
    "positionalRank": 39,
    "tier": 16,
    "trend": 6,
    "rookie": true
  },
  {
    "name": "MarShawn Lloyd",
    "position": "RB",
    "team": "GBP",
    "age": 25.6,
    "value": 3537,
    "rank": 102,
    "positionalRank": 26,
    "tier": 17,
    "trend": 145,
    "rookie": false
  },
  {
    "name": "Quentin Johnston",
    "position": "WR",
    "team": "LAC",
    "age": 25.0,
    "value": 3524,
    "rank": 103,
    "positionalRank": 40,
    "tier": 17,
    "trend": -1,
    "rookie": false
  },
  {
    "name": "Terry McLaurin",
    "position": "WR",
    "team": "WAS",
    "age": 31.0,
    "value": 3517,
    "rank": 104,
    "positionalRank": 41,
    "tier": 17,
    "trend": -5,
    "rookie": false
  },
  {
    "name": "Davante Adams",
    "position": "WR",
    "team": "LAR",
    "age": 33.7,
    "value": 3503,
    "rank": 105,
    "positionalRank": 42,
    "tier": 17,
    "trend": 9,
    "rookie": false
  },
  {
    "name": "Josh Downs",
    "position": "WR",
    "team": "IND",
    "age": 25.0,
    "value": 3502,
    "rank": 106,
    "positionalRank": 43,
    "tier": 17,
    "trend": -6,
    "rookie": false
  },
  {
    "name": "David Montgomery",
    "position": "RB",
    "team": "HOU",
    "age": 29.2,
    "value": 3485,
    "rank": 107,
    "positionalRank": 27,
    "tier": 17,
    "trend": -1,
    "rookie": false
  },
  {
    "name": "Blake Corum",
    "position": "RB",
    "team": "LAR",
    "age": 25.8,
    "value": 3454,
    "rank": 108,
    "positionalRank": 28,
    "tier": 17,
    "trend": 1,
    "rookie": false
  },
  {
    "name": "Isaiah Likely",
    "position": "TE",
    "team": "NYG",
    "age": 26.4,
    "value": 3420,
    "rank": 109,
    "positionalRank": 10,
    "tier": 17,
    "trend": 2,
    "rookie": false
  },
  {
    "name": "Jayden Reed",
    "position": "WR",
    "team": "GBP",
    "age": 26.3,
    "value": 3341,
    "rank": 110,
    "positionalRank": 44,
    "tier": 17,
    "trend": 10,
    "rookie": false
  },
  {
    "name": "DK Metcalf",
    "position": "WR",
    "team": "PIT",
    "age": 28.7,
    "value": 3338,
    "rank": 111,
    "positionalRank": 45,
    "tier": 17,
    "trend": -8,
    "rookie": false
  },
  {
    "name": "Jaylen Warren",
    "position": "RB",
    "team": "PIT",
    "age": 27.8,
    "value": 3327,
    "rank": 112,
    "positionalRank": 29,
    "tier": 17,
    "trend": 11,
    "rookie": false
  },
  {
    "name": "George Kittle",
    "position": "TE",
    "team": "SFO",
    "age": 32.9,
    "value": 3318,
    "rank": 113,
    "positionalRank": 11,
    "tier": 17,
    "trend": 5,
    "rookie": false
  },
  {
    "name": "Kyle Monangai",
    "position": "RB",
    "team": "CHI",
    "age": 24.2,
    "value": 3307,
    "rank": 114,
    "positionalRank": 30,
    "tier": 17,
    "trend": -12,
    "rookie": false
  },
  {
    "name": "Jonah Coleman",
    "position": "RB",
    "team": "DEN",
    "age": 23.0,
    "value": 3290,
    "rank": 115,
    "positionalRank": 31,
    "tier": 17,
    "trend": 18,
    "rookie": true
  },
  {
    "name": "Jalen Coker",
    "position": "WR",
    "team": "CAR",
    "age": 24.8,
    "value": 3276,
    "rank": 116,
    "positionalRank": 46,
    "tier": 17,
    "trend": 13,
    "rookie": false
  },
  {
    "name": "Rhamondre Stevenson",
    "position": "RB",
    "team": "NEP",
    "age": 28.5,
    "value": 3267,
    "rank": 117,
    "positionalRank": 32,
    "tier": 17,
    "trend": 22,
    "rookie": false
  },
  {
    "name": "Michael Pittman",
    "position": "WR",
    "team": "PIT",
    "age": 28.9,
    "value": 3259,
    "rank": 118,
    "positionalRank": 47,
    "tier": 17,
    "trend": -4,
    "rookie": false
  },
  {
    "name": "Wan'Dale Robinson",
    "position": "WR",
    "team": "TEN",
    "age": 25.6,
    "value": 3258,
    "rank": 119,
    "positionalRank": 48,
    "tier": 17,
    "trend": -11,
    "rookie": false
  },
  {
    "name": "Ja'Kobi Lane",
    "position": "WR",
    "team": "BAL",
    "age": 22.1,
    "value": 3254,
    "rank": 120,
    "positionalRank": 49,
    "tier": 17,
    "trend": 83,
    "rookie": true
  },
  {
    "name": "Omar Cooper Jr.",
    "position": "WR",
    "team": "NYJ",
    "age": 22.7,
    "value": 3248,
    "rank": 121,
    "positionalRank": 50,
    "tier": 17,
    "trend": -21,
    "rookie": true
  },
  {
    "name": "RJ Harvey",
    "position": "RB",
    "team": "DEN",
    "age": 25.6,
    "value": 3246,
    "rank": 122,
    "positionalRank": 33,
    "tier": 17,
    "trend": -10,
    "rookie": false
  },
  {
    "name": "Dalton Kincaid",
    "position": "TE",
    "team": "BUF",
    "age": 26.9,
    "value": 3238,
    "rank": 123,
    "positionalRank": 12,
    "tier": 17,
    "trend": 3,
    "rookie": false
  },
  {
    "name": "Zach Charbonnet",
    "position": "RB",
    "team": "SEA",
    "age": 25.6,
    "value": 3233,
    "rank": 124,
    "positionalRank": 34,
    "tier": 17,
    "trend": -4,
    "rookie": false
  },
  {
    "name": "Mike Washington Jr.",
    "position": "RB",
    "team": "LVR",
    "age": 23.2,
    "value": 3219,
    "rank": 125,
    "positionalRank": 35,
    "tier": 17,
    "trend": 95,
    "rookie": true
  },
  {
    "name": "Jacory Croskey-Merritt",
    "position": "RB",
    "team": "WAS",
    "age": 25.4,
    "value": 3203,
    "rank": 126,
    "positionalRank": 36,
    "tier": 17,
    "trend": 16,
    "rookie": false
  },
  {
    "name": "Rico Dowdle",
    "position": "RB",
    "team": "PIT",
    "age": 28.2,
    "value": 3177,
    "rank": 127,
    "positionalRank": 37,
    "tier": 17,
    "trend": 3,
    "rookie": false
  },
  {
    "name": "Romeo Doubs",
    "position": "WR",
    "team": "NEP",
    "age": 26.4,
    "value": 3166,
    "rank": 128,
    "positionalRank": 51,
    "tier": 17,
    "trend": 12,
    "rookie": false
  },
  {
    "name": "Mike Evans",
    "position": "WR",
    "team": "SFO",
    "age": 33.0,
    "value": 3143,
    "rank": 129,
    "positionalRank": 52,
    "tier": 17,
    "trend": -17,
    "rookie": false
  },
  {
    "name": "Courtland Sutton",
    "position": "WR",
    "team": "DEN",
    "age": 30.9,
    "value": 3124,
    "rank": 130,
    "positionalRank": 53,
    "tier": 17,
    "trend": 1,
    "rookie": false
  },
  {
    "name": "Chris Bell",
    "position": "WR",
    "team": "MIA",
    "age": 22.2,
    "value": 3062,
    "rank": 131,
    "positionalRank": 54,
    "tier": 18,
    "trend": 10,
    "rookie": true
  },
  {
    "name": "Chris Godwin",
    "position": "WR",
    "team": "TBB",
    "age": 30.5,
    "value": 3057,
    "rank": 132,
    "positionalRank": 55,
    "tier": 18,
    "trend": 9,
    "rookie": false
  },
  {
    "name": "Xavier Worthy",
    "position": "WR",
    "team": "KCC",
    "age": 23.4,
    "value": 3040,
    "rank": 133,
    "positionalRank": 56,
    "tier": 18,
    "trend": -15,
    "rookie": false
  },
  {
    "name": "Jordan Mason",
    "position": "RB",
    "team": "MIN",
    "age": 27.3,
    "value": 3034,
    "rank": 134,
    "positionalRank": 38,
    "tier": 18,
    "trend": 28,
    "rookie": false
  },
  {
    "name": "Terrance Ferguson",
    "position": "TE",
    "team": "LAR",
    "age": 23.5,
    "value": 3033,
    "rank": 135,
    "positionalRank": 13,
    "tier": 18,
    "trend": 19,
    "rookie": false
  },
  {
    "name": "Chuba Hubbard",
    "position": "RB",
    "team": "CAR",
    "age": 27.2,
    "value": 3031,
    "rank": 136,
    "positionalRank": 39,
    "tier": 18,
    "trend": -9,
    "rookie": false
  },
  {
    "name": "Jake Ferguson",
    "position": "TE",
    "team": "DAL",
    "age": 27.6,
    "value": 3022,
    "rank": 137,
    "positionalRank": 14,
    "tier": 18,
    "trend": -13,
    "rookie": false
  },
  {
    "name": "Oronde Gadsden",
    "position": "TE",
    "team": "LAC",
    "age": 23.2,
    "value": 3019,
    "rank": 138,
    "positionalRank": 15,
    "tier": 18,
    "trend": -36,
    "rookie": false
  },
  {
    "name": "J.K. Dobbins",
    "position": "RB",
    "team": "DEN",
    "age": 27.7,
    "value": 2998,
    "rank": 139,
    "positionalRank": 40,
    "tier": 18,
    "trend": -6,
    "rookie": false
  },
  {
    "name": "Jayden Higgins",
    "position": "WR",
    "team": "HOU",
    "age": 23.7,
    "value": 2981,
    "rank": 140,
    "positionalRank": 57,
    "tier": 18,
    "trend": -33,
    "rookie": false
  },
  {
    "name": "Eli Stowers",
    "position": "TE",
    "team": "PHI",
    "age": 23.4,
    "value": 2980,
    "rank": 141,
    "positionalRank": 16,
    "tier": 18,
    "trend": -26,
    "rookie": true
  },
  {
    "name": "Kenneth Gainwell",
    "position": "RB",
    "team": "TBB",
    "age": 27.5,
    "value": 2978,
    "rank": 142,
    "positionalRank": 41,
    "tier": 18,
    "trend": 0,
    "rookie": false
  },
  {
    "name": "Travis Hunter",
    "position": "WR",
    "team": "JAC",
    "age": 23.3,
    "value": 2947,
    "rank": 143,
    "positionalRank": 58,
    "tier": 18,
    "trend": -30,
    "rookie": false
  },
  {
    "name": "Brenton Strange",
    "position": "TE",
    "team": "JAC",
    "age": 25.7,
    "value": 2900,
    "rank": 144,
    "positionalRank": 17,
    "tier": 18,
    "trend": -8,
    "rookie": false
  },
  {
    "name": "Malachi Fields",
    "position": "WR",
    "team": "NYG",
    "age": 23.0,
    "value": 2898,
    "rank": 145,
    "positionalRank": 59,
    "tier": 18,
    "trend": 35,
    "rookie": true
  },
  {
    "name": "Woody Marks",
    "position": "RB",
    "team": "HOU",
    "age": 25.7,
    "value": 2895,
    "rank": 146,
    "positionalRank": 42,
    "tier": 18,
    "trend": 11,
    "rookie": false
  },
  {
    "name": "Germie Bernard",
    "position": "WR",
    "team": "PIT",
    "age": 22.8,
    "value": 2889,
    "rank": 147,
    "positionalRank": 60,
    "tier": 18,
    "trend": -4,
    "rookie": true
  },
  {
    "name": "Antonio Williams",
    "position": "WR",
    "team": "WAS",
    "age": 22.1,
    "value": 2889,
    "rank": 148,
    "positionalRank": 61,
    "tier": 18,
    "trend": -17,
    "rookie": true
  },
  {
    "name": "Cyrus Allen",
    "position": "WR",
    "team": "KCC",
    "age": 23.6,
    "value": 2870,
    "rank": 149,
    "positionalRank": 62,
    "tier": 18,
    "trend": 123,
    "rookie": true
  },
  {
    "name": "Jalen McMillan",
    "position": "WR",
    "team": "TBB",
    "age": 24.7,
    "value": 2820,
    "rank": 150,
    "positionalRank": 63,
    "tier": 18,
    "trend": -19,
    "rookie": false
  },
  {
    "name": "Jakobi Meyers",
    "position": "WR",
    "team": "JAC",
    "age": 29.8,
    "value": 2816,
    "rank": 151,
    "positionalRank": 64,
    "tier": 18,
    "trend": -17,
    "rookie": false
  },
  {
    "name": "Tyler Allgeier",
    "position": "RB",
    "team": "ARI",
    "age": 26.4,
    "value": 2794,
    "rank": 152,
    "positionalRank": 43,
    "tier": 18,
    "trend": 5,
    "rookie": false
  },
  {
    "name": "Zachariah Branch",
    "position": "WR",
    "team": "ATL",
    "age": 22.4,
    "value": 2781,
    "rank": 153,
    "positionalRank": 65,
    "tier": 18,
    "trend": 6,
    "rookie": true
  },
  {
    "name": "Khalil Shakir",
    "position": "WR",
    "team": "BUF",
    "age": 26.6,
    "value": 2779,
    "rank": 154,
    "positionalRank": 66,
    "tier": 18,
    "trend": -10,
    "rookie": false
  },
  {
    "name": "Caleb Douglas",
    "position": "WR",
    "team": "MIA",
    "age": 23.0,
    "value": 2771,
    "rank": 155,
    "positionalRank": 67,
    "tier": 18,
    "trend": 90,
    "rookie": true
  },
  {
    "name": "Kayshon Boutte",
    "position": "WR",
    "team": "HOU",
    "age": 24.3,
    "value": 2768,
    "rank": 156,
    "positionalRank": 68,
    "tier": 18,
    "trend": 26,
    "rookie": false
  },
  {
    "name": "Carson Beck",
    "position": "QB",
    "team": "ARI",
    "age": 24.8,
    "value": 2762,
    "rank": 157,
    "positionalRank": 29,
    "tier": 18,
    "trend": 33,
    "rookie": true
  },
  {
    "name": "Tony Pollard",
    "position": "RB",
    "team": "TEN",
    "age": 29.3,
    "value": 2757,
    "rank": 158,
    "positionalRank": 44,
    "tier": 18,
    "trend": -12,
    "rookie": false
  },
  {
    "name": "Michael Penix Jr.",
    "position": "QB",
    "team": "ATL",
    "age": 26.3,
    "value": 2756,
    "rank": 159,
    "positionalRank": 30,
    "tier": 18,
    "trend": -8,
    "rookie": false
  },
  {
    "name": "Josh Jacobs",
    "position": "RB",
    "team": "GBP",
    "age": 28.6,
    "value": 2725,
    "rank": 160,
    "positionalRank": 45,
    "tier": 18,
    "trend": -87,
    "rookie": false
  },
  {
    "name": "Nicholas Singleton",
    "position": "RB",
    "team": "TEN",
    "age": 22.6,
    "value": 2722,
    "rank": 161,
    "positionalRank": 46,
    "tier": 18,
    "trend": -18,
    "rookie": true
  },
  {
    "name": "Malik Washington",
    "position": "WR",
    "team": "MIA",
    "age": 25.6,
    "value": 2685,
    "rank": 162,
    "positionalRank": 69,
    "tier": 18,
    "trend": 27,
    "rookie": false
  },
  {
    "name": "AJ Barner",
    "position": "TE",
    "team": "SEA",
    "age": 24.3,
    "value": 2654,
    "rank": 163,
    "positionalRank": 18,
    "tier": 18,
    "trend": -15,
    "rookie": false
  },
  {
    "name": "Rachaad White",
    "position": "RB",
    "team": "WAS",
    "age": 27.6,
    "value": 2640,
    "rank": 164,
    "positionalRank": 47,
    "tier": 18,
    "trend": -15,
    "rookie": false
  },
  {
    "name": "Stefon Diggs",
    "position": "WR",
    "team": "WAS",
    "age": 32.8,
    "value": 2639,
    "rank": 165,
    "positionalRank": 70,
    "tier": 18,
    "trend": 75,
    "rookie": false
  },
  {
    "name": "Pat Bryant",
    "position": "WR",
    "team": "DEN",
    "age": 23.7,
    "value": 2632,
    "rank": 166,
    "positionalRank": 71,
    "tier": 18,
    "trend": 30,
    "rookie": false
  },
  {
    "name": "Chigoziem Okonkwo",
    "position": "TE",
    "team": "WAS",
    "age": 27.0,
    "value": 2631,
    "rank": 167,
    "positionalRank": 19,
    "tier": 18,
    "trend": -14,
    "rookie": false
  },
  {
    "name": "Emmett Johnson",
    "position": "RB",
    "team": "KCC",
    "age": 22.9,
    "value": 2631,
    "rank": 168,
    "positionalRank": 48,
    "tier": 18,
    "trend": 31,
    "rookie": true
  },
  {
    "name": "Rashid Shaheed",
    "position": "WR",
    "team": "SEA",
    "age": 28.0,
    "value": 2625,
    "rank": 169,
    "positionalRank": 72,
    "tier": 18,
    "trend": -24,
    "rookie": false
  },
  {
    "name": "Braelon Allen",
    "position": "RB",
    "team": "NYJ",
    "age": 22.6,
    "value": 2622,
    "rank": 170,
    "positionalRank": 49,
    "tier": 18,
    "trend": 10,
    "rookie": false
  },
  {
    "name": "Dallas Goedert",
    "position": "TE",
    "team": "PHI",
    "age": 31.7,
    "value": 2618,
    "rank": 171,
    "positionalRank": 20,
    "tier": 18,
    "trend": 3,
    "rookie": false
  },
  {
    "name": "Chris Rodriguez",
    "position": "RB",
    "team": "JAC",
    "age": 25.9,
    "value": 2610,
    "rank": 172,
    "positionalRank": 50,
    "tier": 18,
    "trend": -3,
    "rookie": false
  },
  {
    "name": "Keaton Mitchell",
    "position": "RB",
    "team": "LAC",
    "age": 24.6,
    "value": 2601,
    "rank": 173,
    "positionalRank": 51,
    "tier": 18,
    "trend": 12,
    "rookie": false
  },
  {
    "name": "Tre Harris",
    "position": "WR",
    "team": "LAC",
    "age": 24.5,
    "value": 2596,
    "rank": 174,
    "positionalRank": 73,
    "tier": 18,
    "trend": -13,
    "rookie": false
  },
  {
    "name": "Tank Bigsby",
    "position": "RB",
    "team": "PHI",
    "age": 25.0,
    "value": 2592,
    "rank": 175,
    "positionalRank": 52,
    "tier": 18,
    "trend": 2,
    "rookie": false
  },
  {
    "name": "Mark Andrews",
    "position": "TE",
    "team": "BAL",
    "age": 31.0,
    "value": 2586,
    "rank": 176,
    "positionalRank": 21,
    "tier": 18,
    "trend": -21,
    "rookie": false
  },
  {
    "name": "Tre Tucker",
    "position": "WR",
    "team": "LVR",
    "age": 25.5,
    "value": 2585,
    "rank": 177,
    "positionalRank": 74,
    "tier": 18,
    "trend": 14,
    "rookie": false
  },
  {
    "name": "Dylan Sampson",
    "position": "RB",
    "team": "CLE",
    "age": 22.0,
    "value": 2585,
    "rank": 178,
    "positionalRank": 53,
    "tier": 18,
    "trend": -21,
    "rookie": false
  },
  {
    "name": "Dontayvion Wicks",
    "position": "WR",
    "team": "PHI",
    "age": 25.2,
    "value": 2572,
    "rank": 179,
    "positionalRank": 75,
    "tier": 18,
    "trend": 15,
    "rookie": false
  },
  {
    "name": "Travis Kelce",
    "position": "TE",
    "team": "KCC",
    "age": 36.9,
    "value": 2551,
    "rank": 180,
    "positionalRank": 22,
    "tier": 18,
    "trend": -17,
    "rookie": false
  },
  {
    "name": "Drew Allar",
    "position": "QB",
    "team": "PIT",
    "age": 22.5,
    "value": 2547,
    "rank": 181,
    "positionalRank": 31,
    "tier": 18,
    "trend": 68,
    "rookie": true
  },
  {
    "name": "Ted Hurst",
    "position": "WR",
    "team": "TBB",
    "age": 22.2,
    "value": 2547,
    "rank": 182,
    "positionalRank": 76,
    "tier": 18,
    "trend": -1,
    "rookie": true
  },
  {
    "name": "Adonai Mitchell",
    "position": "WR",
    "team": "NYJ",
    "age": 23.9,
    "value": 2529,
    "rank": 183,
    "positionalRank": 77,
    "tier": 18,
    "trend": -11,
    "rookie": false
  },
  {
    "name": "Ricky Pearsall",
    "position": "WR",
    "team": "SFO",
    "age": 26.0,
    "value": 2527,
    "rank": 184,
    "positionalRank": 78,
    "tier": 18,
    "trend": -1,
    "rookie": false
  },
  {
    "name": "Tyjae Spears",
    "position": "RB",
    "team": "TEN",
    "age": 25.2,
    "value": 2523,
    "rank": 185,
    "positionalRank": 54,
    "tier": 18,
    "trend": 0,
    "rookie": false
  },
  {
    "name": "Kaelon Black",
    "position": "RB",
    "team": "SFO",
    "age": 24.9,
    "value": 2522,
    "rank": 186,
    "positionalRank": 55,
    "tier": 18,
    "trend": 47,
    "rookie": true
  },
  {
    "name": "Juwan Johnson",
    "position": "TE",
    "team": "NOS",
    "age": 30.0,
    "value": 2509,
    "rank": 187,
    "positionalRank": 23,
    "tier": 18,
    "trend": 24,
    "rookie": false
  },
  {
    "name": "Isaac TeSlaa",
    "position": "WR",
    "team": "DET",
    "age": 24.5,
    "value": 2508,
    "rank": 188,
    "positionalRank": 79,
    "tier": 18,
    "trend": -35,
    "rookie": false
  },
  {
    "name": "Gunnar Helm",
    "position": "TE",
    "team": "TEN",
    "age": 24.0,
    "value": 2503,
    "rank": 189,
    "positionalRank": 24,
    "tier": 18,
    "trend": -26,
    "rookie": false
  },
  {
    "name": "Jalen Nailor",
    "position": "WR",
    "team": "LVR",
    "age": 27.5,
    "value": 2496,
    "rank": 190,
    "positionalRank": 80,
    "tier": 18,
    "trend": -15,
    "rookie": false
  },
  {
    "name": "T.J. Hockenson",
    "position": "TE",
    "team": "MIN",
    "age": 29.2,
    "value": 2495,
    "rank": 191,
    "positionalRank": 25,
    "tier": 18,
    "trend": -28,
    "rookie": false
  },
  {
    "name": "Elijah Sarratt",
    "position": "WR",
    "team": "BAL",
    "age": 23.3,
    "value": 2490,
    "rank": 192,
    "positionalRank": 81,
    "tier": 18,
    "trend": -26,
    "rookie": true
  },
  {
    "name": "Jaylin Noel",
    "position": "WR",
    "team": "HOU",
    "age": 24.0,
    "value": 2479,
    "rank": 193,
    "positionalRank": 82,
    "tier": 18,
    "trend": -28,
    "rookie": false
  },
  {
    "name": "Jacoby Brissett",
    "position": "QB",
    "team": "ARI",
    "age": 33.7,
    "value": 2457,
    "rank": 194,
    "positionalRank": 32,
    "tier": 18,
    "trend": -23,
    "rookie": false
  },
  {
    "name": "Kaytron Allen",
    "position": "RB",
    "team": "WAS",
    "age": 23.6,
    "value": 2447,
    "rank": 195,
    "positionalRank": 56,
    "tier": 18,
    "trend": -5,
    "rookie": true
  },
  {
    "name": "Deebo Samuel",
    "position": "WR",
    "team": "SFO",
    "age": 30.6,
    "value": 2442,
    "rank": 196,
    "positionalRank": 83,
    "tier": 18,
    "trend": 20,
    "rookie": false
  },
  {
    "name": "Eli Raridon",
    "position": "TE",
    "team": "NEP",
    "age": 22.6,
    "value": 2441,
    "rank": 197,
    "positionalRank": 26,
    "tier": 18,
    "trend": 27,
    "rookie": true
  },
  {
    "name": "Shedeur Sanders",
    "position": "QB",
    "team": "CLE",
    "age": 24.6,
    "value": 2408,
    "rank": 198,
    "positionalRank": 33,
    "tier": 18,
    "trend": -38,
    "rookie": false
  },
  {
    "name": "Tank Dell",
    "position": "WR",
    "team": "HOU",
    "age": 26.8,
    "value": 2403,
    "rank": 199,
    "positionalRank": 84,
    "tier": 18,
    "trend": -30,
    "rookie": false
  },
  {
    "name": "Tory Horton",
    "position": "WR",
    "team": "SEA",
    "age": 23.8,
    "value": 2403,
    "rank": 200,
    "positionalRank": 85,
    "tier": 18,
    "trend": -15,
    "rookie": false
  },
  {
    "name": "Hunter Henry",
    "position": "TE",
    "team": "NEP",
    "age": 31.7,
    "value": 2387,
    "rank": 201,
    "positionalRank": 27,
    "tier": 18,
    "trend": 3,
    "rookie": false
  },
  {
    "name": "Kaleb Johnson",
    "position": "RB",
    "team": "GBP",
    "age": 23.0,
    "value": 2367,
    "rank": 202,
    "positionalRank": 57,
    "tier": 18,
    "trend": 11,
    "rookie": false
  },
  {
    "name": "Troy Franklin",
    "position": "WR",
    "team": "DEN",
    "age": 23.6,
    "value": 2356,
    "rank": 203,
    "positionalRank": 86,
    "tier": 18,
    "trend": -12,
    "rookie": false
  },
  {
    "name": "Elic Ayomanor",
    "position": "WR",
    "team": "TEN",
    "age": 23.2,
    "value": 2315,
    "rank": 204,
    "positionalRank": 87,
    "tier": 18,
    "trend": -9,
    "rookie": false
  },
  {
    "name": "Elijah Arroyo",
    "position": "TE",
    "team": "SEA",
    "age": 23.4,
    "value": 2314,
    "rank": 205,
    "positionalRank": 28,
    "tier": 18,
    "trend": -14,
    "rookie": false
  },
  {
    "name": "Keon Coleman",
    "position": "WR",
    "team": "BUF",
    "age": 23.3,
    "value": 2304,
    "rank": 206,
    "positionalRank": 88,
    "tier": 18,
    "trend": -5,
    "rookie": false
  },
  {
    "name": "Kyle Williams",
    "position": "WR",
    "team": "NEP",
    "age": 23.8,
    "value": 2296,
    "rank": 207,
    "positionalRank": 89,
    "tier": 18,
    "trend": 28,
    "rookie": false
  },
  {
    "name": "Dalton Schultz",
    "position": "TE",
    "team": "HOU",
    "age": 30.1,
    "value": 2293,
    "rank": 208,
    "positionalRank": 29,
    "tier": 18,
    "trend": 23,
    "rookie": false
  },
  {
    "name": "Jack Bech",
    "position": "WR",
    "team": "LVR",
    "age": 23.7,
    "value": 2293,
    "rank": 209,
    "positionalRank": 90,
    "tier": 18,
    "trend": -11,
    "rookie": false
  },
  {
    "name": "Demond Claiborne",
    "position": "RB",
    "team": "MIN",
    "age": 22.9,
    "value": 2290,
    "rank": 210,
    "positionalRank": 58,
    "tier": 18,
    "trend": 17,
    "rookie": true
  },
  {
    "name": "Skyler Bell",
    "position": "WR",
    "team": "BUF",
    "age": 24.2,
    "value": 2287,
    "rank": 211,
    "positionalRank": 91,
    "tier": 18,
    "trend": -13,
    "rookie": true
  },
  {
    "name": "Mac Jones",
    "position": "QB",
    "team": "SFO",
    "age": 28.0,
    "value": 2286,
    "rank": 212,
    "positionalRank": 34,
    "tier": 18,
    "trend": -47,
    "rookie": false
  },
  {
    "name": "Mason Taylor",
    "position": "TE",
    "team": "NYJ",
    "age": 22.3,
    "value": 2277,
    "rank": 213,
    "positionalRank": 30,
    "tier": 18,
    "trend": -8,
    "rookie": false
  },
  {
    "name": "Chris Brazzell II",
    "position": "WR",
    "team": "CAR",
    "age": 22.8,
    "value": 2257,
    "rank": 214,
    "positionalRank": 92,
    "tier": 18,
    "trend": -12,
    "rookie": true
  },
  {
    "name": "Max Klare",
    "position": "TE",
    "team": "LAR",
    "age": 23.2,
    "value": 2252,
    "rank": 215,
    "positionalRank": 31,
    "tier": 18,
    "trend": -8,
    "rookie": true
  },
  {
    "name": "Brian Robinson",
    "position": "RB",
    "team": "ATL",
    "age": 27.4,
    "value": 2247,
    "rank": 216,
    "positionalRank": 59,
    "tier": 18,
    "trend": -17,
    "rookie": false
  },
  {
    "name": "Aaron Jones",
    "position": "RB",
    "team": "MIN",
    "age": 31.8,
    "value": 2240,
    "rank": 217,
    "positionalRank": 60,
    "tier": 18,
    "trend": -15,
    "rookie": false
  },
  {
    "name": "Jerry Jeudy",
    "position": "WR",
    "team": "CLE",
    "age": 27.4,
    "value": 2228,
    "rank": 218,
    "positionalRank": 93,
    "tier": 18,
    "trend": -32,
    "rookie": false
  },
  {
    "name": "Jauan Jennings",
    "position": "WR",
    "team": "MIN",
    "age": 29.1,
    "value": 2213,
    "rank": 219,
    "positionalRank": 94,
    "tier": 18,
    "trend": -24,
    "rookie": false
  },
  {
    "name": "Geno Smith",
    "position": "QB",
    "team": "NYJ",
    "age": 35.9,
    "value": 2180,
    "rank": 220,
    "positionalRank": 35,
    "tier": 18,
    "trend": 4,
    "rookie": false
  },
  {
    "name": "Greg Dulcich",
    "position": "TE",
    "team": "MIA",
    "age": 26.4,
    "value": 2176,
    "rank": 221,
    "positionalRank": 32,
    "tier": 18,
    "trend": -20,
    "rookie": false
  },
  {
    "name": "Jaylen Wright",
    "position": "RB",
    "team": "MIA",
    "age": 23.4,
    "value": 2168,
    "rank": 222,
    "positionalRank": 61,
    "tier": 18,
    "trend": -3,
    "rookie": false
  },
  {
    "name": "Tyrone Tracy",
    "position": "RB",
    "team": "NYG",
    "age": 26.8,
    "value": 2164,
    "rank": 223,
    "positionalRank": 62,
    "tier": 18,
    "trend": -49,
    "rookie": false
  },
  {
    "name": "Cade Otton",
    "position": "TE",
    "team": "TBB",
    "age": 27.4,
    "value": 2156,
    "rank": 224,
    "positionalRank": 33,
    "tier": 18,
    "trend": -17,
    "rookie": false
  },
  {
    "name": "Kimani Vidal",
    "position": "RB",
    "team": "LAC",
    "age": 25.0,
    "value": 2154,
    "rank": 225,
    "positionalRank": 63,
    "tier": 18,
    "trend": -11,
    "rookie": false
  },
  {
    "name": "Pat Freiermuth",
    "position": "TE",
    "team": "PIT",
    "age": 27.8,
    "value": 2144,
    "rank": 226,
    "positionalRank": 34,
    "tier": 18,
    "trend": -13,
    "rookie": false
  },
  {
    "name": "Tua Tagovailoa",
    "position": "QB",
    "team": "ATL",
    "age": 28.5,
    "value": 2134,
    "rank": 227,
    "positionalRank": 36,
    "tier": 18,
    "trend": -73,
    "rookie": false
  },
  {
    "name": "Oscar Delp",
    "position": "TE",
    "team": "NOS",
    "age": 23.1,
    "value": 2131,
    "rank": 228,
    "positionalRank": 35,
    "tier": 18,
    "trend": -1,
    "rookie": true
  },
  {
    "name": "Jordan James",
    "position": "RB",
    "team": "SFO",
    "age": 22.4,
    "value": 2127,
    "rank": 229,
    "positionalRank": 64,
    "tier": 18,
    "trend": -9,
    "rookie": false
  },
  {
    "name": "Ollie Gordon",
    "position": "RB",
    "team": "MIA",
    "age": 22.6,
    "value": 2122,
    "rank": 230,
    "positionalRank": 65,
    "tier": 18,
    "trend": -13,
    "rookie": false
  },
  {
    "name": "Michael Mayer",
    "position": "TE",
    "team": "LVR",
    "age": 25.2,
    "value": 2121,
    "rank": 231,
    "positionalRank": 36,
    "tier": 18,
    "trend": 4,
    "rookie": false
  },
  {
    "name": "Sean Tucker",
    "position": "RB",
    "team": "TBB",
    "age": 24.8,
    "value": 2120,
    "rank": 232,
    "positionalRank": 66,
    "tier": 18,
    "trend": -10,
    "rookie": false
  },
  {
    "name": "David Njoku",
    "position": "TE",
    "team": "LAC",
    "age": 30.1,
    "value": 2113,
    "rank": 233,
    "positionalRank": 37,
    "tier": 18,
    "trend": -17,
    "rookie": false
  },
  {
    "name": "Zavion Thomas",
    "position": "WR",
    "team": "CHI",
    "age": 22.5,
    "value": 2113,
    "rank": 234,
    "positionalRank": 95,
    "tier": 18,
    "trend": 64,
    "rookie": true
  },
  {
    "name": "Chimere Dike",
    "position": "WR",
    "team": "TEN",
    "age": 24.7,
    "value": 2111,
    "rank": 235,
    "positionalRank": 96,
    "tier": 18,
    "trend": -26,
    "rookie": false
  },
  {
    "name": "Jalen Milroe",
    "position": "QB",
    "team": "SEA",
    "age": 23.7,
    "value": 2102,
    "rank": 236,
    "positionalRank": 37,
    "tier": 18,
    "trend": -15,
    "rookie": false
  },
  {
    "name": "J.J. McCarthy",
    "position": "QB",
    "team": "MIN",
    "age": 23.6,
    "value": 2097,
    "rank": 237,
    "positionalRank": 38,
    "tier": 18,
    "trend": -75,
    "rookie": false
  },
  {
    "name": "Tez Johnson",
    "position": "WR",
    "team": "TBB",
    "age": 24.3,
    "value": 2093,
    "rank": 238,
    "positionalRank": 97,
    "tier": 18,
    "trend": 0,
    "rookie": false
  },
  {
    "name": "Isiah Pacheco",
    "position": "RB",
    "team": "DET",
    "age": 27.5,
    "value": 2086,
    "rank": 239,
    "positionalRank": 67,
    "tier": 18,
    "trend": -28,
    "rookie": false
  },
  {
    "name": "Adam Randall",
    "position": "RB",
    "team": "BAL",
    "age": 22.1,
    "value": 2078,
    "rank": 240,
    "positionalRank": 68,
    "tier": 18,
    "trend": 87,
    "rookie": true
  },
  {
    "name": "Ryan Flournoy",
    "position": "WR",
    "team": "DAL",
    "age": 26.8,
    "value": 2052,
    "rank": 241,
    "positionalRank": 98,
    "tier": 18,
    "trend": 7,
    "rookie": false
  },
  {
    "name": "Cade Klubnik",
    "position": "QB",
    "team": "NYJ",
    "age": 22.9,
    "value": 2050,
    "rank": 242,
    "positionalRank": 39,
    "tier": 18,
    "trend": 21,
    "rookie": true
  },
  {
    "name": "Rashod Bateman",
    "position": "WR",
    "team": "BAL",
    "age": 26.8,
    "value": 2035,
    "rank": 243,
    "positionalRank": 99,
    "tier": 18,
    "trend": 6,
    "rookie": false
  },
  {
    "name": "Kevin Coleman",
    "position": "WR",
    "team": "MIA",
    "age": 23.0,
    "value": 2024,
    "rank": 244,
    "positionalRank": 100,
    "tier": 18,
    "trend": 1,
    "rookie": true
  },
  {
    "name": "Demario Douglas",
    "position": "WR",
    "team": "NEP",
    "age": 25.7,
    "value": 2021,
    "rank": 245,
    "positionalRank": 101,
    "tier": 18,
    "trend": 21,
    "rookie": false
  },
  {
    "name": "LeQuint Allen",
    "position": "RB",
    "team": "JAC",
    "age": 22.1,
    "value": 2016,
    "rank": 246,
    "positionalRank": 69,
    "tier": 18,
    "trend": -3,
    "rookie": false
  },
  {
    "name": "Trevor Etienne",
    "position": "RB",
    "team": "CAR",
    "age": 22.2,
    "value": 2013,
    "rank": 247,
    "positionalRank": 70,
    "tier": 18,
    "trend": 5,
    "rookie": false
  },
  {
    "name": "Isaiah Bond",
    "position": "WR",
    "team": "CLE",
    "age": 22.5,
    "value": 2007,
    "rank": 248,
    "positionalRank": 102,
    "tier": 18,
    "trend": -2,
    "rookie": false
  },
  {
    "name": "Colby Parkinson",
    "position": "TE",
    "team": "LAR",
    "age": 27.6,
    "value": 2005,
    "rank": 249,
    "positionalRank": 38,
    "tier": 18,
    "trend": 6,
    "rookie": false
  },
  {
    "name": "Marvin Mims",
    "position": "WR",
    "team": "DEN",
    "age": 24.4,
    "value": 1992,
    "rank": 250,
    "positionalRank": 103,
    "tier": 18,
    "trend": -11,
    "rookie": false
  },
  {
    "name": "Ray Davis",
    "position": "RB",
    "team": "BUF",
    "age": 26.8,
    "value": 1986,
    "rank": 251,
    "positionalRank": 71,
    "tier": 18,
    "trend": 8,
    "rookie": false
  },
  {
    "name": "Kirk Cousins",
    "position": "QB",
    "team": "LVR",
    "age": 38.0,
    "value": 1975,
    "rank": 252,
    "positionalRank": 40,
    "tier": 18,
    "trend": 15,
    "rookie": false
  },
  {
    "name": "Jake Tonges",
    "position": "TE",
    "team": "SFO",
    "age": 27.2,
    "value": 1968,
    "rank": 253,
    "positionalRank": 39,
    "tier": 18,
    "trend": -10,
    "rookie": false
  },
  {
    "name": "Xavier Hutchinson",
    "position": "WR",
    "team": "HOU",
    "age": 26.2,
    "value": 1960,
    "rank": 254,
    "positionalRank": 104,
    "tier": 18,
    "trend": 52,
    "rookie": false
  },
  {
    "name": "Theo Johnson",
    "position": "TE",
    "team": "NYG",
    "age": 25.5,
    "value": 1959,
    "rank": 255,
    "positionalRank": 40,
    "tier": 18,
    "trend": -21,
    "rookie": false
  },
  {
    "name": "Jaylin Lane",
    "position": "WR",
    "team": "WAS",
    "age": 24.3,
    "value": 1954,
    "rank": 256,
    "positionalRank": 105,
    "tier": 18,
    "trend": -4,
    "rookie": false
  },
  {
    "name": "Cole Kmet",
    "position": "TE",
    "team": "CHI",
    "age": 27.5,
    "value": 1950,
    "rank": 257,
    "positionalRank": 41,
    "tier": 18,
    "trend": -7,
    "rookie": false
  },
  {
    "name": "Isaiah Davis",
    "position": "RB",
    "team": "NYJ",
    "age": 24.5,
    "value": 1931,
    "rank": 258,
    "positionalRank": 72,
    "tier": 18,
    "trend": 11,
    "rookie": false
  },
  {
    "name": "Bryce Lance",
    "position": "WR",
    "team": "NOS",
    "age": 24.0,
    "value": 1926,
    "rank": 259,
    "positionalRank": 106,
    "tier": 18,
    "trend": 11,
    "rookie": true
  },
  {
    "name": "Xavier Legette",
    "position": "WR",
    "team": "CAR",
    "age": 25.6,
    "value": 1912,
    "rank": 260,
    "positionalRank": 107,
    "tier": 18,
    "trend": 4,
    "rookie": false
  },
  {
    "name": "Darnell Washington",
    "position": "TE",
    "team": "PIT",
    "age": 25.0,
    "value": 1911,
    "rank": 261,
    "positionalRank": 42,
    "tier": 18,
    "trend": 5,
    "rookie": false
  },
  {
    "name": "Aaron Rodgers",
    "position": "QB",
    "team": "PIT",
    "age": 42.8,
    "value": 1910,
    "rank": 262,
    "positionalRank": 41,
    "tier": 18,
    "trend": -6,
    "rookie": false
  },
  {
    "name": "Anthony Richardson",
    "position": "QB",
    "team": "IND",
    "age": 24.3,
    "value": 1904,
    "rank": 263,
    "positionalRank": 42,
    "tier": 18,
    "trend": -35,
    "rookie": false
  },
  {
    "name": "Alvin Kamara",
    "position": "RB",
    "team": "NOS",
    "age": 31.1,
    "value": 1900,
    "rank": 264,
    "positionalRank": 73,
    "tier": 18,
    "trend": -23,
    "rookie": false
  },
  {
    "name": "Dont'e Thornton",
    "position": "WR",
    "team": "LVR",
    "age": 23.8,
    "value": 1896,
    "rank": 265,
    "positionalRank": 108,
    "tier": 18,
    "trend": -2,
    "rookie": false
  },
  {
    "name": "DJ Giddens",
    "position": "RB",
    "team": "IND",
    "age": 23.0,
    "value": 1877,
    "rank": 266,
    "positionalRank": 74,
    "tier": 18,
    "trend": -20,
    "rookie": false
  },
  {
    "name": "Justin Joly",
    "position": "TE",
    "team": "FA",
    "age": 22.2,
    "value": 1864,
    "rank": 267,
    "positionalRank": 43,
    "tier": 18,
    "trend": 6,
    "rookie": true
  },
  {
    "name": "Devin Neal",
    "position": "RB",
    "team": "NOS",
    "age": 23.0,
    "value": 1862,
    "rank": 268,
    "positionalRank": 75,
    "tier": 18,
    "trend": -8,
    "rookie": false
  },
  {
    "name": "Roman Wilson",
    "position": "WR",
    "team": "PIT",
    "age": 25.2,
    "value": 1825,
    "rank": 269,
    "positionalRank": 109,
    "tier": 18,
    "trend": 30,
    "rookie": false
  },
  {
    "name": "Trey Benson",
    "position": "RB",
    "team": "ARI",
    "age": 24.1,
    "value": 1817,
    "rank": 270,
    "positionalRank": 76,
    "tier": 18,
    "trend": -33,
    "rookie": false
  },
  {
    "name": "Malik Benson",
    "position": "WR",
    "team": "LVR",
    "age": 23.9,
    "value": 1816,
    "rank": 271,
    "positionalRank": 110,
    "tier": 18,
    "trend": 172,
    "rookie": true
  },
  {
    "name": "Brenen Thompson",
    "position": "WR",
    "team": "LAC",
    "age": 23.1,
    "value": 1813,
    "rank": 272,
    "positionalRank": 111,
    "tier": 18,
    "trend": 12,
    "rookie": true
  },
  {
    "name": "Seth McGowan",
    "position": "RB",
    "team": "IND",
    "age": 24.8,
    "value": 1801,
    "rank": 273,
    "positionalRank": 77,
    "tier": 18,
    "trend": 63,
    "rookie": true
  },
  {
    "name": "Jalen Royals",
    "position": "WR",
    "team": "KCC",
    "age": 23.5,
    "value": 1797,
    "rank": 274,
    "positionalRank": 112,
    "tier": 18,
    "trend": -5,
    "rookie": false
  },
  {
    "name": "Deshaun Watson",
    "position": "QB",
    "team": "CLE",
    "age": 31.0,
    "value": 1793,
    "rank": 275,
    "positionalRank": 43,
    "tier": 18,
    "trend": -17,
    "rookie": false
  },
  {
    "name": "Ja'Tavion Sanders",
    "position": "TE",
    "team": "CAR",
    "age": 23.4,
    "value": 1788,
    "rank": 276,
    "positionalRank": 44,
    "tier": 18,
    "trend": -23,
    "rookie": false
  },
  {
    "name": "Darnell Mooney",
    "position": "WR",
    "team": "NYG",
    "age": 28.8,
    "value": 1787,
    "rank": 277,
    "positionalRank": 113,
    "tier": 18,
    "trend": -26,
    "rookie": false
  },
  {
    "name": "Barion Brown",
    "position": "WR",
    "team": "NOS",
    "age": 22.7,
    "value": 1782,
    "rank": 278,
    "positionalRank": 114,
    "tier": 18,
    "trend": 142,
    "rookie": true
  },
  {
    "name": "Tyquan Thornton",
    "position": "WR",
    "team": "KCC",
    "age": 26.1,
    "value": 1774,
    "rank": 279,
    "positionalRank": 115,
    "tier": 18,
    "trend": 2,
    "rookie": false
  },
  {
    "name": "Justin Fields",
    "position": "QB",
    "team": "KCC",
    "age": 27.5,
    "value": 1768,
    "rank": 280,
    "positionalRank": 44,
    "tier": 18,
    "trend": -26,
    "rookie": false
  },
  {
    "name": "Devaughn Vele",
    "position": "WR",
    "team": "NOS",
    "age": 28.7,
    "value": 1767,
    "rank": 281,
    "positionalRank": 116,
    "tier": 18,
    "trend": 55,
    "rookie": false
  },
  {
    "name": "Kendre Miller",
    "position": "RB",
    "team": "NOS",
    "age": 24.2,
    "value": 1758,
    "rank": 282,
    "positionalRank": 78,
    "tier": 18,
    "trend": 10,
    "rookie": false
  },
  {
    "name": "Calvin Ridley",
    "position": "WR",
    "team": "TEN",
    "age": 31.7,
    "value": 1753,
    "rank": 283,
    "positionalRank": 117,
    "tier": 18,
    "trend": -5,
    "rookie": false
  },
  {
    "name": "Will Howard",
    "position": "QB",
    "team": "PIT",
    "age": 24.9,
    "value": 1752,
    "rank": 284,
    "positionalRank": 45,
    "tier": 18,
    "trend": -10,
    "rookie": false
  },
  {
    "name": "Keenan Allen",
    "position": "WR",
    "team": "IND",
    "age": 34.4,
    "value": 1729,
    "rank": 285,
    "positionalRank": 118,
    "tier": 18,
    "trend": 84,
    "rookie": false
  },
  {
    "name": "Emanuel Wilson",
    "position": "RB",
    "team": "SEA",
    "age": 27.3,
    "value": 1700,
    "rank": 286,
    "positionalRank": 79,
    "tier": 18,
    "trend": -22,
    "rookie": false
  },
  {
    "name": "Brashard Smith",
    "position": "RB",
    "team": "KCC",
    "age": 23.4,
    "value": 1700,
    "rank": 287,
    "positionalRank": 80,
    "tier": 18,
    "trend": -5,
    "rookie": false
  },
  {
    "name": "George Holani",
    "position": "RB",
    "team": "SEA",
    "age": 26.7,
    "value": 1686,
    "rank": 288,
    "positionalRank": 81,
    "tier": 18,
    "trend": 10,
    "rookie": false
  },
  {
    "name": "Malik Davis",
    "position": "RB",
    "team": "DAL",
    "age": 27.8,
    "value": 1682,
    "rank": 289,
    "positionalRank": 82,
    "tier": 18,
    "trend": 29,
    "rookie": false
  },
  {
    "name": "Najee Harris",
    "position": "RB",
    "team": "NYG",
    "age": 28.5,
    "value": 1673,
    "rank": 290,
    "positionalRank": 83,
    "tier": 18,
    "trend": 90,
    "rookie": false
  },
  {
    "name": "Jahan Dotson",
    "position": "WR",
    "team": "ATL",
    "age": 26.4,
    "value": 1663,
    "rank": 291,
    "positionalRank": 119,
    "tier": 18,
    "trend": 6,
    "rookie": false
  },
  {
    "name": "Christian Kirk",
    "position": "WR",
    "team": "SFO",
    "age": 29.8,
    "value": 1662,
    "rank": 292,
    "positionalRank": 120,
    "tier": 18,
    "trend": -21,
    "rookie": false
  },
  {
    "name": "Joe Milton",
    "position": "QB",
    "team": "DAL",
    "age": 26.5,
    "value": 1660,
    "rank": 293,
    "positionalRank": 46,
    "tier": 18,
    "trend": 10,
    "rookie": false
  },
  {
    "name": "Cooper Kupp",
    "position": "WR",
    "team": "SEA",
    "age": 33.2,
    "value": 1653,
    "rank": 294,
    "positionalRank": 121,
    "tier": 18,
    "trend": -9,
    "rookie": false
  },
  {
    "name": "Eli Heidenreich",
    "position": "RB",
    "team": "PIT",
    "age": 23.2,
    "value": 1651,
    "rank": 295,
    "positionalRank": 84,
    "tier": 18,
    "trend": -22,
    "rookie": true
  },
  {
    "name": "Evan Engram",
    "position": "TE",
    "team": "DEN",
    "age": 32.0,
    "value": 1648,
    "rank": 296,
    "positionalRank": 45,
    "tier": 18,
    "trend": -21,
    "rookie": false
  },
  {
    "name": "Jalen Tolbert",
    "position": "WR",
    "team": "MIA",
    "age": 27.5,
    "value": 1623,
    "rank": 297,
    "positionalRank": 122,
    "tier": 18,
    "trend": -27,
    "rookie": false
  },
  {
    "name": "Andrei Iosivas",
    "position": "WR",
    "team": "CIN",
    "age": 26.9,
    "value": 1610,
    "rank": 298,
    "positionalRank": 123,
    "tier": 18,
    "trend": -9,
    "rookie": false
  },
  {
    "name": "Savion Williams",
    "position": "WR",
    "team": "GBP",
    "age": 24.8,
    "value": 1601,
    "rank": 299,
    "positionalRank": 124,
    "tier": 18,
    "trend": -12,
    "rookie": false
  },
  {
    "name": "Chris Brooks",
    "position": "RB",
    "team": "GBP",
    "age": 26.6,
    "value": 1596,
    "rank": 300,
    "positionalRank": 85,
    "tier": 18,
    "trend": 9,
    "rookie": false
  }
]
