// Rookie prospect detail, keyed by prospect id.
// KTC market values, ranks, tiers and 30-day trends refreshed 2026-08-25 (draft day).
// Sources: https://keeptradecut.com/dynasty-rankings/rookie-rankings
//          https://www.draftsharks.com/dynasty-rankings/rookies/superflex
export const ROOKIE_DETAILS = {
  "1001": {
    "fullName": "Jeremiyah Love",
    "college": "Notre Dame",
    "age": 21.2,
    "height": "6'0\"",
    "weight": 190,
    "draftCapital": "Round 1, Pick 3",
    "ktcValue": 7393,
    "ktcOverallRank": 13,
    "ktcRookieRank": 1,
    "ktcPositionalRank": 3,
    "ktcTier": 1,
    "dsRank": 1,
    "dsTier": 2,
    "dsRookieAdp": "2.06",
    "dsValue": 58.8,
    "projPtsYear1": 203,
    "projPts3Yr": 608,
    "projPts5Yr": 1012,
    "scoutingReport": "Love was a force at Notre Dame, posting back-to-back 1,100-yard rushing seasons with 35 total rushing TDs. His contact balance and power rank among the best RB traits in recent draft classes, and his profile stacks up favorably with Ashton Jeanty’s. Arizona doesn't supply an excellent situation in 2026, as the OL and QB spots lack talent. Still, Love brings true three-down upside and will be just 21 years old as a rookie. He's an easy fit inside the top-five dynasty RBs.",
    "ktcRookieTrend30": 0,
    "ktcOverallTrend30": 2,
    "ktcRookieAdp": 1.0,
    "fpEcrRank": 1
  },
  "1002": {
    "fullName": "Fernando Mendoza",
    "college": "Indiana",
    "age": 22.9,
    "height": "6'5\"",
    "weight": 225,
    "draftCapital": "Round 1, Pick 1",
    "ktcValue": 5405,
    "ktcOverallRank": 49,
    "ktcRookieRank": 3,
    "ktcPositionalRank": 14,
    "ktcTier": 2,
    "dsRank": 2,
    "dsTier": 5,
    "dsRookieAdp": "4.03",
    "dsValue": 30.5,
    "projPtsYear1": 198,
    "projPts3Yr": 812,
    "projPts5Yr": 1363,
    "scoutingReport": "Mendoza posted two straight 3,000-yard passing seasons at Cal and Indiana. He displays a strong arm and great mid-range accuracy while showing toughness in the pocket. Mendoza can scramble some, too, which should help his fantasy output. He lacks the upside of recent top QBs like Caleb Williams, but Mendoza has the potential to be a top-10 fantasy QB. Mendoza gets a true centerpiece target in Brock Bowers and a play-caller in Klint Kubiak who has shown the ability to scheme an efficient offense.",
    "ktcRookieTrend30": 0,
    "ktcOverallTrend30": 0,
    "ktcRookieAdp": 4.0,
    "fpEcrRank": 9
  },
  "1003": {
    "fullName": "Jordyn Tyson",
    "college": "Arizona State",
    "age": 22.0,
    "height": "6'2\"",
    "weight": 195,
    "draftCapital": "Round 1, Pick 8",
    "ktcValue": 4978,
    "ktcOverallRank": 67,
    "ktcRookieRank": 5,
    "ktcPositionalRank": 24,
    "ktcTier": 2,
    "dsRank": 5,
    "dsTier": 5,
    "dsRookieAdp": "5.09",
    "dsValue": 26.9,
    "projPtsYear1": 127,
    "projPts3Yr": 422,
    "projPts5Yr": 714,
    "scoutingReport": "Tyson broke out at Arizona State in 2024 with a 74-1,101-10 line. He looked on track for another big season in 2025, scoring 7 TDs in five games before a hamstring injury cut things short. Durability is the concern. His history includes a torn ACL, PCL, and MCL in 2022, plus a broken collarbone in 2024. When healthy, Tyson brings an appealing blend of size, speed, and run-after-catch ability. Those traits give him WR1-level upside. The Saints boosted his outlook by taking him 8th overall. Tyson lands with QB Tyler Shough and could see opportunity open quickly if Chris Olave moves on after his contract year.",
    "ktcRookieTrend30": -1,
    "ktcOverallTrend30": -13,
    "ktcRookieAdp": 7.0,
    "fpEcrRank": 3
  },
  "1004": {
    "fullName": "Makai Lemon",
    "college": "USC",
    "age": 22.2,
    "height": "5'11\"",
    "weight": 190,
    "draftCapital": "Round 1, Pick 20",
    "ktcValue": 4886,
    "ktcOverallRank": 69,
    "ktcRookieRank": 6,
    "ktcPositionalRank": 26,
    "ktcTier": 2,
    "dsRank": 6,
    "dsTier": 5,
    "dsRookieAdp": "6.07",
    "dsValue": 26.6,
    "projPtsYear1": 111,
    "projPts3Yr": 425,
    "projPts5Yr": 720,
    "scoutingReport": "Lemon might be the best contested-catch WR in this class despite a 5’11, 195-pound frame. He aligned both in the slot and outside at USC, winning the Biletnikoff Award in 2025. His ball tracking and run-after-catch burst make him a dangerous, high-volume PPR weapon. Philadelphia adds to the appeal. The Eagles took him 20th overall, and both GM Howie Roseman and HC Nick Sirianni emphasized his ability to move across the formation. That versatility matters with A.J. Brown expected to be traded. His departure would free up 121 targets.",
    "ktcRookieTrend30": -1,
    "ktcOverallTrend30": -6,
    "ktcRookieAdp": 8.0,
    "fpEcrRank": 4
  },
  "1005": {
    "fullName": "Carnell Tate",
    "college": "Ohio State",
    "age": 21.6,
    "height": "6'2\"",
    "weight": 192,
    "draftCapital": "Round 1, Pick 4",
    "ktcValue": 5727,
    "ktcOverallRank": 37,
    "ktcRookieRank": 2,
    "ktcPositionalRank": 12,
    "ktcTier": 2,
    "dsRank": 7,
    "dsTier": 6,
    "dsRookieAdp": "5.02",
    "dsValue": 24.2,
    "projPtsYear1": 127,
    "projPts3Yr": 396,
    "projPts5Yr": 677,
    "scoutingReport": "Tate took a backseat to Ohio State phenom Jeremiah Smith but still flashed elite ball skills. He consistently tracked the ball well, beat press coverage, and showed no hesitation working the middle. That skill set, paired with top-five draft capital, points to early production in Tennessee. The depth chart helps, too. Targets are available, and Tate lands with an upside QB in Cam Ward.",
    "ktcRookieTrend30": 0,
    "ktcOverallTrend30": -1,
    "ktcRookieAdp": 4.0,
    "fpEcrRank": 2
  },
  "1006": {
    "fullName": "Jadarian Price",
    "college": "Notre Dame",
    "age": 22.9,
    "height": "5'11\"",
    "weight": 205,
    "draftCapital": "Round 1, Pick 32",
    "ktcValue": 5039,
    "ktcOverallRank": 60,
    "ktcRookieRank": 4,
    "ktcPositionalRank": 16,
    "ktcTier": 2,
    "dsRank": 8,
    "dsTier": 6,
    "dsRookieAdp": "7.09",
    "dsValue": 22.7,
    "projPtsYear1": 149,
    "projPts3Yr": 406,
    "projPts5Yr": 644,
    "scoutingReport": "Price profiles as a power runner with enough burst to rip off long TDs. He ran for 674 yards and 11 scores this past season while working behind stud teammate Jeremiyah Love. His contact balance and short-area agility translate well to the next level. And there’s reason to believe he offers more in the passing game than his 15 career catches suggest. The landing spot boosts his early outlook. Seattle has an opening with Kenneth Walker gone and Zach Charbonnet recovering from a January ACL tear.",
    "ktcRookieTrend30": 2,
    "ktcOverallTrend30": 14,
    "ktcRookieAdp": 7.0,
    "fpEcrRank": 5
  },
  "1007": {
    "fullName": "KC Concepcion",
    "college": "Texas A&M",
    "age": 21.9,
    "height": "5'11\"",
    "weight": 195,
    "draftCapital": "Round 1, Pick 24",
    "ktcValue": 4668,
    "ktcOverallRank": 78,
    "ktcRookieRank": 7,
    "ktcPositionalRank": 29,
    "ktcTier": 2,
    "dsRank": 11,
    "dsTier": 7,
    "dsRookieAdp": "8.01",
    "dsValue": 17.8,
    "projPtsYear1": 113,
    "projPts3Yr": 355,
    "projPts5Yr": 601,
    "scoutingReport": "Concepcion built on his NC State flashes with a true breakout at Texas A&M in 2025, finishing 61-919-9 while running 65% of his routes out wide. He added 10 carries for 75 yards and a TD, plus two return scores. He runs crisp routes and presents strong run-after-catch ability. Drops showed up at times, but the usage and playmaking traits should translate. Cleveland brings QB questions, but also a clear path to Year 1 fantasy value. The target tree is thin, with TE Harold Fannin Jr. as the primary competition. That leaves room for Concepcion to earn early volume and emerge as a usable fantasy option right away.",
    "ktcRookieTrend30": 0,
    "ktcOverallTrend30": 10,
    "ktcRookieAdp": 9.0,
    "fpEcrRank": 6
  },
  "1008": {
    "fullName": "Ty Simpson",
    "college": "Alabama",
    "age": 23.7,
    "height": "6'2\"",
    "weight": 203,
    "draftCapital": "Round 1, Pick 13",
    "ktcValue": 3707,
    "ktcOverallRank": 109,
    "ktcRookieRank": 11,
    "ktcPositionalRank": 28,
    "ktcTier": 3,
    "dsRank": 12,
    "dsTier": 7,
    "dsRookieAdp": "9.08",
    "dsValue": 16.0,
    "projPtsYear1": 30,
    "projPts3Yr": 751,
    "projPts5Yr": 1274,
    "scoutingReport": "Simpson threw for 3,567 yards with 28 TDs and 5 INTs at Alabama this past season. He shows solid pocket feel and enough mobility to extend plays, but his inexperience pops up when he holds the ball too long. The Rams made him a surprise pick at No. 13 overall, signaling belief in his long-term upside. Short term, though, this is Matthew Stafford’s job. Simpson’s path to the field hinges on Stafford’s health and timeline.",
    "ktcRookieTrend30": 0,
    "ktcOverallTrend30": 7,
    "ktcRookieAdp": 13.0,
    "fpEcrRank": 21
  },
  "1009": {
    "fullName": "Kenyon Sadiq",
    "college": "Oregon",
    "age": 21.5,
    "height": "6'3\"",
    "weight": 235,
    "draftCapital": "Round 1, Pick 16",
    "ktcValue": 3806,
    "ktcOverallRank": 100,
    "ktcRookieRank": 9,
    "ktcPositionalRank": 9,
    "ktcTier": 3,
    "dsRank": 14,
    "dsTier": 8,
    "dsRookieAdp": "8.03",
    "dsValue": 13.5,
    "projPtsYear1": 90,
    "projPts3Yr": 267,
    "projPts5Yr": 461,
    "scoutingReport": "Sadiq (6’3, 241) brings an elite athletic profile with the footwork and leaping ability to separate and win at the catch point. He’s a matchup problem, especially in tight coverage, and adds value after the catch. He led Oregon in receptions in 2025, though drops showed up at times. The Jets made him a mid-Round 1 pick, signaling a long-term featured role. Short term, the path to volume looks crowded. Garrett Wilson remains locked in as the top target, and the addition of Omar Cooper Jr. adds another high-percentage option underneath.",
    "ktcRookieTrend30": -1,
    "ktcOverallTrend30": -7,
    "ktcRookieAdp": 9.0,
    "fpEcrRank": 10
  },
  "1010": {
    "fullName": "Omar Cooper Jr.",
    "college": "Indiana",
    "age": 22.7,
    "height": "6'1\"",
    "weight": 200,
    "draftCapital": "Round 1, Pick 30",
    "ktcValue": 3348,
    "ktcOverallRank": 125,
    "ktcRookieRank": 12,
    "ktcPositionalRank": 46,
    "ktcTier": 4,
    "dsRank": 16,
    "dsTier": 8,
    "dsRookieAdp": "8.11",
    "dsValue": 12.4,
    "projPtsYear1": 94,
    "projPts3Yr": 313,
    "projPts5Yr": 524,
    "scoutingReport": "Cooper led Indiana in receiving in 2025, posting a 64-866-13 line. His body control and strong hands made him a go-to option for Heisman QB Fernando Mendoza, especially in the red zone. He pairs that reliability with strong competitiveness and run-after-catch ability. The Jets traded up to select him 30th overall, making him the WR5 in this class. But the situation adds risk. Garrett Wilson remains locked in as the top target, and the Jets drafted athletic TE Kenyon Sadiq earlier in Round 1. The QB position also lacks a long-term answer.",
    "ktcRookieTrend30": -3,
    "ktcOverallTrend30": -15,
    "ktcRookieAdp": 13.0,
    "fpEcrRank": 7
  },
  "1011": {
    "fullName": "Eli Stowers",
    "college": "Vanderbilt",
    "age": 23.4,
    "height": "6'4\"",
    "weight": 235,
    "draftCapital": "Round 2, Pick 22",
    "ktcValue": 3226,
    "ktcOverallRank": 136,
    "ktcRookieRank": 14,
    "ktcPositionalRank": 13,
    "ktcTier": 4,
    "dsRank": 17,
    "dsTier": 9,
    "dsRookieAdp": "11.10",
    "dsValue": 11.2,
    "projPtsYear1": 48,
    "projPts3Yr": 262,
    "projPts5Yr": 448,
    "scoutingReport": "Stowers is a former QB converted to TE. He will be more slot WR than TE, sitting at 6'4, 235 pounds. He led Vanderbilt with 62 catches last year and was a reliable option for QB Diego Pavia. Stowers has elite explosiveness and short-area quickness, and that was reflected in his excellent Combine performance. Stowers will be the future starting TE for the Eagles. Dallas Goedert is set to be a free agent after this season.",
    "ktcRookieTrend30": -2,
    "ktcOverallTrend30": -13,
    "ktcRookieAdp": 13.0,
    "fpEcrRank": 11
  },
  "1012": {
    "fullName": "Antonio Williams",
    "college": "Clemson",
    "age": 22.1,
    "height": "5'11\"",
    "weight": 195,
    "draftCapital": "Round 3, Pick 7",
    "ktcValue": 2861,
    "ktcOverallRank": 166,
    "ktcRookieRank": 22,
    "ktcPositionalRank": 61,
    "ktcTier": 6,
    "dsRank": 18,
    "dsTier": 9,
    "dsRookieAdp": "17.07",
    "dsValue": 10.3,
    "projPtsYear1": 73,
    "projPts3Yr": 299,
    "projPts5Yr": 501,
    "scoutingReport": "Williams looked like a top WR after he led Clemson in receiving as a true freshman in 2022. But lower body injuries in 2023 derailed him before a 74-904-11 season in 2024. Clemson's weak pass offense hurt Williams in 2025, but he is a versatile WR with good route running and hands. He also lands on a weak Commanders depth chart where Williams can ascend to becoming their No. 2 WR.",
    "ktcRookieTrend30": -8,
    "ktcOverallTrend30": -18,
    "ktcRookieAdp": 17.0,
    "fpEcrRank": 14
  },
  "1013": {
    "fullName": "Denzel Boston",
    "college": "Washington",
    "age": 22.7,
    "height": "6'4\"",
    "weight": 212,
    "draftCapital": "Round 2, Pick 7",
    "ktcValue": 3736,
    "ktcOverallRank": 105,
    "ktcRookieRank": 10,
    "ktcPositionalRank": 36,
    "ktcTier": 3,
    "dsRank": 19,
    "dsTier": 9,
    "dsRookieAdp": "10.05",
    "dsValue": 10.1,
    "projPtsYear1": 93,
    "projPts3Yr": 293,
    "projPts5Yr": 496,
    "scoutingReport": "Boston sat behind the trio of Rome Odunze, Ja'Lynn Polk, and Jalen McMillan in 2023, but the 6'4, 210-pound WR flashed in 2024. He had his best season this year as an X WR, going 63-834-9 on a Huskies team that prioritized the run. He joins the Browns, paired with first-round pick KC Concepcion. Boston should start immediately outside and could turn into the team's top WR.",
    "ktcRookieTrend30": 0,
    "ktcOverallTrend30": 10,
    "ktcRookieAdp": 16.0,
    "fpEcrRank": 8
  },
  "1014": {
    "fullName": "Germie Bernard",
    "college": "Alabama",
    "age": 22.7,
    "height": "6'1\"",
    "weight": 204,
    "draftCapital": "Round 2, Pick 15",
    "ktcValue": 2881,
    "ktcOverallRank": 162,
    "ktcRookieRank": 20,
    "ktcPositionalRank": 59,
    "ktcTier": 6,
    "dsRank": 20,
    "dsTier": 9,
    "dsRookieAdp": "12.07",
    "dsValue": 8.9,
    "projPtsYear1": 86,
    "projPts3Yr": 284,
    "projPts5Yr": 476,
    "scoutingReport": "Bernard followed HC Kalen DeBoer from Washington to Alabama. He had his best season in 2025 at 64-862-7. Bernard has good size and hands as a savvy route runner who works in the slot and outside. He may not have No. 1 WR upside, but Bernard will likely play the slot role for the Steelers. He has a low ceiling, but a high floor.",
    "ktcRookieTrend30": -4,
    "ktcOverallTrend30": -2,
    "ktcRookieAdp": 20.0,
    "fpEcrRank": 15
  },
  "1015": {
    "fullName": "Elijah Sarratt",
    "college": "Indiana",
    "age": 23.2,
    "height": "6'2\"",
    "weight": 209,
    "draftCapital": "Round 4, Pick 15",
    "ktcValue": 2510,
    "ktcOverallRank": 206,
    "ktcRookieRank": 30,
    "ktcPositionalRank": 81,
    "ktcTier": 8,
    "dsRank": 22,
    "dsTier": 10,
    "dsRookieAdp": "14.01",
    "dsValue": 7.5,
    "projPtsYear1": 56,
    "projPts3Yr": 279,
    "projPts5Yr": 473,
    "scoutingReport": "Sarratt flashed in 2024 going 53-957-8. He missed a few games due to a hamstring injury, but he did score 13 TDs in 2025 with Fernando Mendoza at QB. Sarratt has high-end size at 6'2, 213 pounds. His high pointing is among the best in the class. The Ravens drafted WR Ja'Kobi Lane over Sarratt, but they will likely compete for targets as rookies.",
    "ktcRookieTrend30": -10,
    "ktcOverallTrend30": -19,
    "ktcRookieAdp": 34.0,
    "fpEcrRank": 22
  },
  "1016": {
    "fullName": "De'Zhaun Stribling",
    "college": "Mississippi",
    "age": 23.7,
    "height": "6'2\"",
    "weight": 205,
    "draftCapital": "Round 2, Pick 1",
    "ktcValue": 3867,
    "ktcOverallRank": 97,
    "ktcRookieRank": 8,
    "ktcPositionalRank": 33,
    "ktcTier": 3,
    "dsRank": 23,
    "dsTier": 10,
    "dsRookieAdp": "24.11",
    "dsValue": 6.9,
    "projPtsYear1": 65,
    "projPts3Yr": 275,
    "projPts5Yr": 458,
    "scoutingReport": "Stribling broke out at Washington State before joining Ole Miss in 2025. He went 55-811-6 in the SEC showcasing great hands and after catch ability. Stribling was overdrafted as an early Round 2 pick by the 49ers, but he does offer a vertical element for the team. He could be the No. 3 WR on the 49ers as a rookie.",
    "ktcRookieTrend30": 9,
    "ktcOverallTrend30": 64,
    "ktcRookieAdp": 21.0,
    "fpEcrRank": 13
  },
  "1017": {
    "fullName": "Zachariah Branch",
    "college": "Georgia",
    "age": 22.4,
    "height": "5'10\"",
    "weight": 180,
    "draftCapital": "Round 3, Pick 15",
    "ktcValue": 2769,
    "ktcOverallRank": 174,
    "ktcRookieRank": 24,
    "ktcPositionalRank": 66,
    "ktcTier": 7,
    "dsRank": 25,
    "dsTier": 10,
    "dsRookieAdp": "16.07",
    "dsValue": 6.1,
    "projPtsYear1": 70,
    "projPts3Yr": 259,
    "projPts5Yr": 438,
    "scoutingReport": "Branch is an intriguing prospect. The former five-star recruit is a jack-of-all-trades at 5'10, 180 pounds. He flashed at USC but transferred to Georgia to have his best season yet. Branch went 81-811-6 for the Dawgs. He also is one of the best returners in the country. Branch lands on a weak Falcons depth chart where he will serve as an offensive weapon immediately.",
    "ktcRookieTrend30": -5,
    "ktcOverallTrend30": 5,
    "ktcRookieAdp": 28.0,
    "fpEcrRank": 26
  },
  "1018": {
    "fullName": "Ja'Kobi Lane",
    "college": "USC",
    "age": 22.0,
    "height": "6'4\"",
    "weight": 200,
    "draftCapital": "Round 3, Pick 16",
    "ktcValue": 3187,
    "ktcOverallRank": 140,
    "ktcRookieRank": 15,
    "ktcPositionalRank": 51,
    "ktcTier": 4,
    "ktcRookieTrend30": 13,
    "ktcOverallTrend30": 80,
    "ktcRookieAdp": 35.0,
    "fpEcrRank": 19
  },
  "1019": {
    "fullName": "Chris Bell",
    "college": "Louisville",
    "age": 22.2,
    "height": "6'2\"",
    "weight": 222,
    "draftCapital": "Round 3, Pick 30",
    "ktcValue": 2930,
    "ktcOverallRank": 158,
    "ktcRookieRank": 17,
    "ktcPositionalRank": 58,
    "ktcTier": 6,
    "ktcRookieTrend30": -2,
    "ktcOverallTrend30": -2,
    "ktcRookieAdp": 19.0,
    "fpEcrRank": 18
  },
  "1020": {
    "fullName": "Max Klare",
    "college": "Ohio State",
    "age": 23.1,
    "height": "6'5\"",
    "weight": 246,
    "draftCapital": "Round 2, Pick 29",
    "ktcValue": 2206,
    "ktcOverallRank": 242,
    "ktcRookieRank": 35,
    "ktcPositionalRank": 30,
    "ktcTier": 10,
    "ktcRookieTrend30": -6,
    "ktcOverallTrend30": -15,
    "ktcRookieAdp": 30.0,
    "fpEcrRank": 31
  },
  "1021": {
    "fullName": "Brenen Thompson",
    "college": "Mississippi State",
    "age": 23.1,
    "height": "5'9\"",
    "weight": 164,
    "draftCapital": "Round 4, Pick 5",
    "ktcValue": 1862,
    "ktcOverallRank": 297,
    "ktcRookieRank": 44,
    "ktcPositionalRank": 109,
    "ktcTier": 12,
    "ktcRookieTrend30": -2,
    "ktcOverallTrend30": 24,
    "ktcRookieAdp": 45.0,
    "fpEcrRank": 43
  },
  "1022": {
    "fullName": "Ted Hurst",
    "college": "Georgia State",
    "age": 22.2,
    "height": "6'3\"",
    "weight": 195,
    "draftCapital": "Round 3, Pick 20",
    "ktcValue": 2554,
    "ktcOverallRank": 196,
    "ktcRookieRank": 27,
    "ktcPositionalRank": 76,
    "ktcTier": 8,
    "ktcRookieTrend30": -5,
    "ktcOverallTrend30": -2,
    "ktcRookieAdp": 26.0,
    "fpEcrRank": 20
  },
  "1023": {
    "fullName": "Chris Brazzell II",
    "college": "Tennessee",
    "age": 22.8,
    "height": "6'4\"",
    "weight": 198,
    "draftCapital": "Round 3, Pick 19",
    "ktcValue": 2261,
    "ktcOverallRank": 240,
    "ktcRookieRank": 34,
    "ktcPositionalRank": 92,
    "ktcTier": 10,
    "ktcRookieTrend30": -7,
    "ktcOverallTrend30": -26,
    "ktcRookieAdp": 28.0,
    "fpEcrRank": 38
  },
  "1024": {
    "fullName": "Caleb Douglas",
    "college": "Texas Tech",
    "age": 23.0,
    "height": "6'4\"",
    "weight": 206,
    "draftCapital": "Round 3, Pick 11",
    "ktcValue": 2753,
    "ktcOverallRank": 177,
    "ktcRookieRank": 25,
    "ktcPositionalRank": 68,
    "ktcTier": 7,
    "ktcRookieTrend30": 11,
    "ktcOverallTrend30": 95,
    "ktcRookieAdp": 42.0,
    "fpEcrRank": 36
  },
  "1025": {
    "fullName": "Bryce Lance",
    "college": "North Dakota State",
    "age": 24.0,
    "height": "6'3\"",
    "weight": 209,
    "draftCapital": "Round 4, Pick 36",
    "ktcValue": 1951,
    "ktcOverallRank": 285,
    "ktcRookieRank": 43,
    "ktcPositionalRank": 105,
    "ktcTier": 11,
    "ktcRookieTrend30": -3,
    "ktcOverallTrend30": 23,
    "ktcRookieAdp": 43.0,
    "fpEcrRank": 34
  },
  "1026": {
    "fullName": "Oscar Delp",
    "college": "Georgia",
    "age": 23.0,
    "height": "6'5\"",
    "weight": 245,
    "draftCapital": "Round 3, Pick 9",
    "ktcValue": 2087,
    "ktcOverallRank": 263,
    "ktcRookieRank": 38,
    "ktcPositionalRank": 36,
    "ktcTier": 10,
    "ktcRookieTrend30": -6,
    "ktcOverallTrend30": -5,
    "ktcRookieAdp": 32.0,
    "fpEcrRank": 29
  },
  "1027": {
    "fullName": "Eli Raridon",
    "college": "Notre Dame",
    "age": 22.5,
    "height": "6'7\"",
    "weight": 252,
    "draftCapital": "Round 3, Pick 31",
    "ktcValue": 2421,
    "ktcOverallRank": 219,
    "ktcRookieRank": 32,
    "ktcPositionalRank": 26,
    "ktcTier": 9,
    "ktcRookieTrend30": 1,
    "ktcOverallTrend30": 40,
    "ktcRookieAdp": 30.0,
    "fpEcrRank": 28
  },
  "1028": {
    "fullName": "Zavion Thomas",
    "college": "LSU",
    "age": 22.5,
    "height": "5'10\"",
    "weight": 190,
    "draftCapital": "Round 3, Pick 25",
    "ktcValue": 1967,
    "ktcOverallRank": 279,
    "ktcRookieRank": 41,
    "ktcPositionalRank": 103,
    "ktcTier": 11,
    "ktcRookieTrend30": 2,
    "ktcOverallTrend30": 44,
    "ktcRookieAdp": 44.0,
    "fpEcrRank": 59
  },
  "1029": {
    "fullName": "Justin Joly",
    "college": "NC State",
    "age": 22.1,
    "height": "6'3\"",
    "weight": 241,
    "draftCapital": "Round 5, Pick 12",
    "ktcValue": 1988,
    "ktcOverallRank": 275,
    "ktcRookieRank": 40,
    "ktcPositionalRank": 38,
    "ktcTier": 11,
    "ktcRookieTrend30": -1,
    "ktcOverallTrend30": 22,
    "ktcRookieAdp": 38.0,
    "fpEcrRank": 35
  },
  "1030": {
    "fullName": "Nicholas Singleton",
    "college": "Penn State",
    "age": 22.6,
    "height": "6'0\"",
    "weight": 219,
    "draftCapital": "Round 5, Pick 25",
    "ktcValue": 2919,
    "ktcOverallRank": 159,
    "ktcRookieRank": 18,
    "ktcPositionalRank": 41,
    "ktcTier": 6,
    "ktcRookieTrend30": 0,
    "ktcOverallTrend30": 8,
    "ktcRookieAdp": 20.0,
    "fpEcrRank": 16
  },
  "1031": {
    "fullName": "Kaytron Allen",
    "college": "Penn State",
    "age": 23.6,
    "height": "5'11\"",
    "weight": 217,
    "draftCapital": "Round 6, Pick 6",
    "ktcValue": 2517,
    "ktcOverallRank": 204,
    "ktcRookieRank": 29,
    "ktcPositionalRank": 54,
    "ktcTier": 8,
    "ktcRookieTrend30": -5,
    "ktcOverallTrend30": 2,
    "ktcRookieAdp": 29.0,
    "fpEcrRank": 24
  },
  "1032": {
    "fullName": "Kaelon Black",
    "college": "Indiana",
    "age": 24.8,
    "height": "5'9\"",
    "weight": 208,
    "draftCapital": "Round 3, Pick 26",
    "ktcValue": 2422,
    "ktcOverallRank": 218,
    "ktcRookieRank": 31,
    "ktcPositionalRank": 56,
    "ktcTier": 9,
    "ktcRookieTrend30": 4,
    "ktcOverallTrend30": 53,
    "ktcRookieAdp": 30.0,
    "fpEcrRank": 27
  },
  "1036": {
    "fullName": "Mike Washington Jr.",
    "college": "Arkansas",
    "age": 23.1,
    "height": "6'2\"",
    "weight": 228,
    "draftCapital": "Round 4, Pick 22",
    "ktcValue": 3019,
    "ktcOverallRank": 151,
    "ktcRookieRank": 16,
    "ktcPositionalRank": 37,
    "ktcTier": 5,
    "ktcRookieTrend30": 14,
    "ktcOverallTrend30": 79,
    "ktcRookieAdp": 29.0,
    "fpEcrRank": 25
  },
  "1038": {
    "fullName": "Sam Roush",
    "college": "Stanford",
    "age": 23.0,
    "height": "6'5\"",
    "weight": 267,
    "draftCapital": "Round 3, Pick 5",
    "ktcValue": 1030,
    "ktcOverallRank": 428,
    "ktcRookieRank": 61,
    "ktcPositionalRank": 66,
    "ktcTier": 15,
    "ktcRookieTrend30": -7,
    "ktcOverallTrend30": 28,
    "ktcRookieAdp": 54.0,
    "fpEcrRank": 48
  },
  "1039": {
    "fullName": "Kevin Coleman",
    "college": "Missouri",
    "age": 23.0,
    "height": "5'10\"",
    "weight": 179,
    "draftCapital": "Round 5, Pick 37",
    "ktcValue": 2028,
    "ktcOverallRank": 269,
    "ktcRookieRank": 39,
    "ktcPositionalRank": 99,
    "ktcTier": 11,
    "ktcRookieTrend30": -5,
    "ktcOverallTrend30": 1,
    "ktcRookieAdp": 56.0,
    "fpEcrRank": 44
  },
  "1040": {
    "fullName": "Emmett Johnson",
    "college": "Nebraska",
    "age": 22.9,
    "height": "5'11\"",
    "weight": 200,
    "draftCapital": "Round 5, Pick 21",
    "ktcValue": 2537,
    "ktcOverallRank": 199,
    "ktcRookieRank": 28,
    "ktcPositionalRank": 52,
    "ktcTier": 8,
    "ktcRookieTrend30": -3,
    "ktcOverallTrend30": 11,
    "ktcRookieAdp": 25.0,
    "fpEcrRank": 17
  },
  "1041": {
    "fullName": "Skyler Bell",
    "college": "UConn",
    "age": 24.1,
    "height": "6'0\"",
    "weight": 185,
    "draftCapital": "Round 4, Pick 25",
    "ktcValue": 2174,
    "ktcOverallRank": 252,
    "ktcRookieRank": 36,
    "ktcPositionalRank": 94,
    "ktcTier": 10,
    "ktcRookieTrend30": -10,
    "ktcOverallTrend30": -40,
    "ktcRookieAdp": 34.0,
    "fpEcrRank": 30
  },
  "1042": {
    "fullName": "Jonah Coleman",
    "college": "Washington",
    "age": 23.0,
    "height": "5'9\"",
    "weight": 228,
    "draftCapital": "Round 4, Pick 8",
    "ktcValue": 3283,
    "ktcOverallRank": 128,
    "ktcRookieRank": 13,
    "ktcPositionalRank": 31,
    "ktcTier": 4,
    "ktcRookieTrend30": 0,
    "ktcOverallTrend30": 12,
    "ktcRookieAdp": 16.0,
    "fpEcrRank": 12
  },
  "1045": {
    "fullName": "Jack Endries",
    "college": "Texas",
    "age": 22.4,
    "height": "6'5\"",
    "weight": 245,
    "draftCapital": "Round 7, Pick 5",
    "ktcValue": 999,
    "ktcOverallRank": 434,
    "ktcRookieRank": 62,
    "ktcPositionalRank": 67,
    "ktcTier": 15,
    "ktcRookieTrend30": -3,
    "ktcOverallTrend30": 39,
    "ktcRookieAdp": 64.0,
    "fpEcrRank": 58
  },
  "1047": {
    "fullName": "Adam Randall",
    "college": "Clemson",
    "age": 22.1,
    "height": "6'3\"",
    "weight": 232,
    "draftCapital": "Round 5, Pick 34",
    "ktcValue": 1957,
    "ktcOverallRank": 283,
    "ktcRookieRank": 42,
    "ktcPositionalRank": 72,
    "ktcTier": 11,
    "ktcRookieTrend30": 3,
    "ktcOverallTrend30": 68,
    "ktcRookieAdp": 39.0,
    "fpEcrRank": 39
  },
  "1050": {
    "fullName": "CJ Daniels",
    "college": "Miami",
    "age": 24.6,
    "height": "6'2\"",
    "weight": 205,
    "draftCapital": "Round 6, Pick 16",
    "ktcValue": 1175,
    "ktcOverallRank": 403,
    "ktcRookieRank": 56,
    "ktcPositionalRank": 154,
    "ktcTier": 14,
    "ktcRookieTrend30": -5,
    "ktcOverallTrend30": 16,
    "ktcRookieAdp": 69.0
  },
  "1051": {
    "fullName": "Barion Brown",
    "college": "LSU",
    "age": 22.7,
    "height": "5'11\"",
    "weight": 185,
    "draftCapital": "Round 6, Pick 9",
    "ktcValue": 1742,
    "ktcOverallRank": 311,
    "ktcRookieRank": 45,
    "ktcPositionalRank": 116,
    "ktcTier": 13,
    "ktcRookieTrend30": 12,
    "ktcOverallTrend30": 155,
    "ktcRookieAdp": 79.0
  },
  "1052": {
    "fullName": "Cyrus Allen",
    "college": "Cincinnati",
    "age": 23.5,
    "height": "5'11\"",
    "weight": 180,
    "draftCapital": "Round 5, Pick 36",
    "ktcValue": 2875,
    "ktcOverallRank": 163,
    "ktcRookieRank": 21,
    "ktcPositionalRank": 60,
    "ktcTier": 6,
    "ktcRookieTrend30": 29,
    "ktcOverallTrend30": 253,
    "ktcRookieAdp": 52.0,
    "fpEcrRank": 37
  },
  "1054": {
    "fullName": "Deion Burks",
    "college": "Oklahoma",
    "age": 23.6,
    "height": "5'9\"",
    "weight": 180,
    "draftCapital": "Round 7, Pick 38",
    "ktcValue": 1372,
    "ktcOverallRank": 364,
    "ktcRookieRank": 51,
    "ktcPositionalRank": 135,
    "ktcTier": 14,
    "ktcRookieTrend30": -2,
    "ktcOverallTrend30": 42,
    "ktcRookieAdp": 65.0,
    "fpEcrRank": 57
  },
  "1057": {
    "fullName": "Drew Allar",
    "college": "Penn State",
    "age": 22.5,
    "height": "6'5\"",
    "weight": 228,
    "draftCapital": "Round 3, Pick 12",
    "ktcValue": 2583,
    "ktcOverallRank": 192,
    "ktcRookieRank": 26,
    "ktcPositionalRank": 31,
    "ktcTier": 8,
    "ktcRookieTrend30": 11,
    "ktcOverallTrend30": 91,
    "ktcRookieAdp": 33.0,
    "fpEcrRank": 42
  },
  "1058": {
    "fullName": "Malachi Fields",
    "college": "Notre Dame",
    "age": 23.0,
    "height": "6'4\"",
    "weight": 222,
    "draftCapital": "Round 3, Pick 10",
    "ktcValue": 2859,
    "ktcOverallRank": 168,
    "ktcRookieRank": 23,
    "ktcPositionalRank": 63,
    "ktcTier": 6,
    "ktcRookieTrend30": -2,
    "ktcOverallTrend30": 23,
    "ktcRookieAdp": 30.0,
    "fpEcrRank": 23
  },
  "1059": {
    "fullName": "Carson Beck",
    "college": "Miami",
    "age": 24.8,
    "height": "6'5\"",
    "weight": 233,
    "draftCapital": "Round 3, Pick 1",
    "ktcValue": 2897,
    "ktcOverallRank": 160,
    "ktcRookieRank": 19,
    "ktcPositionalRank": 29,
    "ktcTier": 6,
    "ktcRookieTrend30": 4,
    "ktcOverallTrend30": 42,
    "ktcRookieAdp": 27.0,
    "fpEcrRank": 33
  },
  "1060": {
    "fullName": "Matthew Hibner",
    "college": "SMU",
    "age": 24.5,
    "height": "6'4\"",
    "weight": 251,
    "draftCapital": "Round 4, Pick 33",
    "ktcValue": 1206,
    "ktcOverallRank": 396,
    "ktcRookieRank": 55,
    "ktcPositionalRank": 60,
    "ktcTier": 14,
    "ktcRookieTrend30": 1,
    "ktcOverallTrend30": 67,
    "ktcRookieAdp": 49.0
  },
  "1062": {
    "fullName": "Demond Claiborne",
    "college": "Wake Forest",
    "age": 22.9,
    "height": "5'10\"",
    "weight": 188,
    "draftCapital": "Round 6, Pick 17",
    "ktcValue": 2358,
    "ktcOverallRank": 227,
    "ktcRookieRank": 33,
    "ktcPositionalRank": 57,
    "ktcTier": 9,
    "ktcRookieTrend30": -2,
    "ktcOverallTrend30": 23,
    "ktcRookieAdp": 34.0,
    "fpEcrRank": 32
  },
  "1065": {
    "fullName": "Cade Klubnik",
    "college": "Clemson",
    "age": 22.9,
    "height": "6'2\"",
    "weight": 207,
    "draftCapital": "Round 4, Pick 10",
    "ktcValue": 2125,
    "ktcOverallRank": 257,
    "ktcRookieRank": 37,
    "ktcPositionalRank": 37,
    "ktcTier": 10,
    "ktcRookieTrend30": 1,
    "ktcOverallTrend30": 30,
    "ktcRookieAdp": 44.0,
    "fpEcrRank": 46
  },
  "1068": {
    "fullName": "Seth McGowan",
    "college": "Kentucky",
    "age": 24.8,
    "height": "6'1\"",
    "weight": 215,
    "draftCapital": "Round 7, Pick 21",
    "ktcValue": 1702,
    "ktcOverallRank": 316,
    "ktcRookieRank": 46,
    "ktcPositionalRank": 79,
    "ktcTier": 13,
    "ktcRookieTrend30": 0,
    "ktcOverallTrend30": 65,
    "ktcRookieAdp": 48.0,
    "fpEcrRank": 40
  },
  "1073": {
    "fullName": "Michael Trigg",
    "college": "Baylor",
    "age": 24.2,
    "height": "6'4\"",
    "weight": 240,
    "draftCapital": "Undrafted free agent",
    "ktcValue": 1259,
    "ktcOverallRank": 388,
    "ktcRookieRank": 53,
    "ktcPositionalRank": 56,
    "ktcTier": 14,
    "ktcRookieTrend30": -6,
    "ktcOverallTrend30": 8,
    "ktcRookieAdp": 57.0
  },
  "1074": {
    "fullName": "Jam Miller",
    "college": "Alabama",
    "age": 22.3,
    "height": "5'10\"",
    "weight": 209,
    "draftCapital": "Round 7, Pick 29",
    "ktcValue": 1166,
    "ktcOverallRank": 405,
    "ktcRookieRank": 58,
    "ktcPositionalRank": 101,
    "ktcTier": 14,
    "ktcRookieTrend30": 0,
    "ktcOverallTrend30": 63,
    "ktcRookieAdp": 74.0,
    "fpEcrRank": 50
  },
  "1076": {
    "fullName": "Eli Heidenreich",
    "college": "Navy",
    "age": 23.2,
    "height": "6'0\"",
    "weight": 206,
    "draftCapital": "Round 7, Pick 14",
    "ktcValue": 1680,
    "ktcOverallRank": 319,
    "ktcRookieRank": 48,
    "ktcPositionalRank": 80,
    "ktcTier": 13,
    "ktcRookieTrend30": -7,
    "ktcOverallTrend30": -5,
    "ktcRookieAdp": 48.0,
    "fpEcrRank": 41
  },
  "1079": {
    "fullName": "Taylen Green",
    "college": "Arkansas",
    "age": 23.8,
    "height": "6'6\"",
    "weight": 230,
    "draftCapital": "Round 6, Pick 1",
    "ktcValue": 1442,
    "ktcOverallRank": 353,
    "ktcRookieRank": 50,
    "ktcPositionalRank": 50,
    "ktcTier": 14,
    "ktcRookieTrend30": -2,
    "ktcOverallTrend30": 47,
    "ktcRookieAdp": 50.0,
    "fpEcrRank": 55
  },
  "1095": {
    "fullName": "Garrett Nussmeier",
    "college": "LSU",
    "age": 24.6,
    "height": "6'1\"",
    "weight": 205,
    "draftCapital": "Round 7, Pick 33",
    "ktcValue": 1466,
    "ktcOverallRank": 349,
    "ktcRookieRank": 49,
    "ktcPositionalRank": 49,
    "ktcTier": 14,
    "ktcRookieTrend30": -5,
    "ktcOverallTrend30": -5,
    "ktcRookieAdp": 61.0,
    "fpEcrRank": 53
  },
  "1098": {
    "fullName": "J'Mari Taylor",
    "college": "Virginia",
    "age": 24.6,
    "height": "5'9\"",
    "weight": 199,
    "draftCapital": "Undrafted free agent",
    "ktcValue": 1170,
    "ktcOverallRank": 404,
    "ktcRookieRank": 57,
    "ktcPositionalRank": 100,
    "ktcTier": 14,
    "ktcRookieTrend30": -5,
    "ktcOverallTrend30": 38,
    "ktcRookieAdp": 90.0,
    "fpEcrRank": 47
  },
  "1048": {
    "fullName": "Malik Benson",
    "age": 23.8,
    "height": "6'0\"",
    "weight": 189,
    "draftCapital": "Round 6, Pick 14",
    "ktcValue": 1694,
    "ktcOverallRank": 317,
    "ktcRookieRank": 47,
    "ktcPositionalRank": 118,
    "ktcTier": 13,
    "ktcRookieTrend30": 17,
    "ktcOverallTrend30": 424,
    "ktcRookieAdp": 75.0
  },
  "1034": {
    "fullName": "Marlin Klein",
    "age": 23.9,
    "height": "6'6\"",
    "weight": 248,
    "draftCapital": "Round 2, Pick 27",
    "ktcValue": 1304,
    "ktcOverallRank": 369,
    "ktcRookieRank": 52,
    "ktcPositionalRank": 52,
    "ktcTier": 14,
    "ktcRookieTrend30": 15,
    "ktcOverallTrend30": 386,
    "ktcRookieAdp": 44.0,
    "fpEcrRank": 54
  },
  "1114": {
    "fullName": "Jack Strand",
    "age": 22.2,
    "height": "6'5\"",
    "weight": 240,
    "draftCapital": "Undrafted free agent",
    "ktcValue": 1245,
    "ktcOverallRank": 390,
    "ktcRookieRank": 54,
    "ktcPositionalRank": 52,
    "ktcTier": 14,
    "ktcRookieTrend30": 0,
    "ktcOverallTrend30": -1,
    "ktcRookieAdp": null
  },
  "1046": {
    "fullName": "Colbie Young",
    "age": 24.1,
    "height": "6'5\"",
    "weight": 218,
    "draftCapital": "Round 4, Pick 40",
    "ktcValue": 1155,
    "ktcOverallRank": 408,
    "ktcRookieRank": 59,
    "ktcPositionalRank": 155,
    "ktcTier": 14,
    "ktcRookieTrend30": 5,
    "ktcOverallTrend30": 246,
    "ktcRookieAdp": 58.0
  },
  "1033": {
    "fullName": "Tanner Koziol",
    "age": 23.6,
    "height": "6'7\"",
    "weight": 250,
    "draftCapital": "Round 5, Pick 24",
    "ktcValue": 1137,
    "ktcOverallRank": 412,
    "ktcRookieRank": 60,
    "ktcPositionalRank": 63,
    "ktcTier": 14,
    "ktcRookieTrend30": 9,
    "ktcOverallTrend30": 347,
    "ktcRookieAdp": 56.0,
    "fpEcrRank": 45
  },
  "1115": {
    "fullName": "Le'Veon Moss",
    "age": 23.8,
    "height": "5'11\"",
    "weight": 210,
    "draftCapital": "Undrafted free agent",
    "ktcValue": 877,
    "ktcOverallRank": 457,
    "ktcRookieRank": 63,
    "ktcPositionalRank": 117,
    "ktcTier": 15,
    "ktcRookieTrend30": -10,
    "ktcOverallTrend30": -4,
    "ktcRookieAdp": 92.0
  },
  "1043": {
    "fullName": "Reggie Virgil",
    "age": 22.3,
    "height": "6'3\"",
    "weight": 187,
    "draftCapital": "Round 5, Pick 3",
    "ktcValue": 804,
    "ktcOverallRank": 466,
    "ktcRookieRank": 64,
    "ktcPositionalRank": 176,
    "ktcTier": 15,
    "ktcRookieTrend30": -4,
    "ktcOverallTrend30": 37,
    "ktcRookieAdp": 97.0,
    "fpEcrRank": 56
  },
  "1116": {
    "fullName": "Cole Payton",
    "age": 23.8,
    "height": "6'2\"",
    "weight": 232,
    "draftCapital": "Round 5, Pick 38",
    "ktcValue": 774,
    "ktcOverallRank": 470,
    "ktcRookieRank": 65,
    "ktcPositionalRank": 67,
    "ktcTier": 15,
    "ktcRookieTrend30": -10,
    "ktcOverallTrend30": -10,
    "ktcRookieAdp": 56.0,
    "fpEcrRank": 49
  },
  "1117": {
    "fullName": "Luke Altmyer",
    "age": 23.8,
    "height": "6'1\"",
    "weight": 213,
    "draftCapital": "Undrafted free agent",
    "ktcValue": 466,
    "ktcOverallRank": 499,
    "ktcRookieRank": 66,
    "ktcPositionalRank": 71,
    "ktcTier": 16,
    "ktcRookieTrend30": -5,
    "ktcOverallTrend30": 4,
    "ktcRookieAdp": 46.0
  },
  "1099": {
    "fullName": "Roman Hemby",
    "fpEcrRank": 51
  },
  "1090": {
    "fullName": "Robert Henry Jr.",
    "fpEcrRank": 52
  },
  "1093": {
    "fullName": "Jaydn Ott",
    "fpEcrRank": 60
  }
}
